### ISSUE TITLE
SemanticSegmentationLabler for Terrain

### ISSUE THREAD

**Issue by ChristianWiele** [Unity-Technologies/com.unity.perception#102]
Hi,

are there plans to support terrains (incl. trees/vegetation/layers) for semantic segmentation?  

Regards, Christian

**Comment by JonathanHUnity** [comment]
Terrain support just landed in https://github.com/Unity-Technologies/com.unity.perception/pull/103. Now, labeling terrians should just work, with a few caveats mentioned in the PR. Check it out!

**Comment by StuartGJohnson** [comment]
Hmm, so you can do semantic segmentation of terrain, but not any components of terrain. This is apparently hard. Is there a two sentence reason it is so hard? :) Is it a matter of new terrain assets?
