### ISSUE TITLE
Output Directory

### ISSUE THREAD

**Issue by rrmlgroup** [Unity-Technologies/com.unity.perception#107]
Hello,
Is there an easy way to control the output directory? Is there a command line argument, a way to access it in script, or a config setting that I'm missing?
I have been unable to find a way yet. I'm trying to run a simple build on Windows and need to control where the output goes other than the default location: C:/Users/User/AppData/LocalLow/CompanyName/ProjectName/GUIDString. This is because the C drive has limited space.

Thanks!

**Comment by JonathanHUnity** [comment]
This is a limitation in the package at the moment, but we plan to change this to be configurable in an upcoming release. Thanks for the report, and watch this issue for more info.

**Comment by rrmlgroup** [comment]
Thanks for the info!

**Comment by lessw2020** [comment]
Just wanted to bump this - is there an ETA on when this might be implemented?  
For my specific work case with medical, due to HIPAA requirements our HD's have to be encrypted...but that's not a good perf thing for writing out large amounts of synthetic images.  
Thus if I can point the output dir to an unencrypted drive, I can meet HIPAA for my main/system drive while not losing performance for synthetic which has no ePHII/HIPAA requirements.

**Comment by JonathanHUnity** [comment]
I do have some news on this. There is an API now for assigning the directory in which datasets are generated. Here is a sample script that assigns it at startup:
```
using Unity.Simulation;
using UnityEngine;

public class SetOutputDirectory : MonoBehaviour
{
    void Start()
    {
        Configuration.localPersistentDataPath = "C:/data";
    }
}
```

We plan on exposing this as a project setting in our next release, which should come in 4-5 weeks.

**Comment by lessw2020** [comment]
@JonathanHUnity  - great, thanks very much.  Really nice to see all these improvements that are being added.

**Comment by Mercury-ML** [comment]
```
using Unity.Simulation;
using UnityEngine;

public class SetOutputDirectory : MonoBehaviour
{
    void Start()
    {
        Configuration.localPersistentDataPath = "C:/data";
    }
}

```

I'm getting an error:  The type or namespace name 'Simulation' does not exist in the namespace 'Unity' (are you missing an assembly reference?)
I tried:
using Unity.Simulation
using Unity.Perception
using Unity.Perception.Simulation
etc.

Any help would be greatly appreciated.  Also, I put the script in assets/scripts, it that correct?

BTW, I need to set the path to an external drive, such as:
` /Volumes/Ext2TB/output-files `
Do I need to re-map the drive or does that look OK?
