### ISSUE TITLE
Is there a way to prevent objects from colliding when generating the data?

### ISSUE THREAD

**Issue by rajshekarreddy97** [Unity-Technologies/com.unity.perception#120]
Since I will be randomizing the positions of the object, there is a good chance any two objects will collide. How do I prevent that from happening?

**Comment by sleal-unity** [comment]
Hello! The foreground and background randomizers utilized in the [perception package tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Tutorial/TUTORIAL.md) use an algorithm called Poisson disk placement to ensure that all objects randomly placed within a 2D region are spaced at least X meters apart. By adjusting this separation distance to a large enough value you can ensure that no two placed objects will collide.

**Comment by rajshekarreddy97** [comment]
I see, thank you very much!
