### ISSUE TITLE
Could not get a unique color for 255

### ISSUE THREAD

**Issue by HenrikWerner** [Unity-Technologies/com.unity.perception#130]
I get this new log message "Could not get a unique color for 255" (using RC-0.6.0-preview.1). I found that this is printed in InstanceSegmentationCrossPipelinePass.cs and caused by InstanceIdToColorMapping.cs if the instance id is 255. But why is the instance id set to 255 (that is causing this error) and how can this be solved, so that the instance id is not 255?

**Comment by StevenBorkman** [comment]
Henrik, thanks for the report. This is a bug and we have captured it and are going to work on a fix for this soon. The IDs are set programmatically and the ID for the 255th item added to a scene should certainly be supported. We will update this issue when we have a fix.

**Comment by StevenBorkman** [comment]
Hi Henrik,

I have added a fix for the issue that you discovered and it is now in our master branch. The current state of master is our 0.6.0-preview1 release along with this bug fix and some updates to the tutorial.
