### ISSUE TITLE
Control the synthetic generated image size ie Height and Width and zoom ratio.

### ISSUE THREAD

**Issue by Gowtham171996** [Unity-Technologies/com.unity.perception#138]
I am able to generate a huge dataset. Thanks to you guys.
Aim: To train with the Faster RCNN model and I am successful.
Improvements: 

1. When the image is generated, we had margin-left and margin-right of the image which are just background which is non-required data. Is there any way we can crop it? or focus mainly on our foreground window only?
2. Certain DNN models required fixed-size input images. (of course, we handle it while preprocessing) But it would be great if we could restrict it somehow to a certain dimension.

**Comment by StevenBorkman** [comment]
Hi, thanks for reaching out to us. We're really excited that you are able to get good results from our product, that is awesome to hear.

As for your issues, I think the easiest way to solve both questions is by choosing the 'Game' resolution from the aspect drop down menu. Unity defaults to 'Free Aspect' which fills the screen of the editor. But you can choose custom resolutions to use via the drop down, including defining your own resolution with the '+' button. Now when you hit play,  the game will be in your chosen resolution as will all of the generated image files. Choosing a non-widescreen resolution  will also probably help to crop the extra screen space on the sides of the image.

![image](https://user-images.githubusercontent.com/66975693/102115587-c2dfb280-3e09-11eb-9bb4-835a3422c7c9.png)

If you would like to fine tune your setup, you can also play with the location of your camera in your scene, and depending on your camera projection, you can change some parameters (such as Field of View).

I hope this helps. Please respond if you have any more (or other) issues.

**Comment by Gowtham171996** [comment]
@StevenBorkman  Thank you. The solution was helpful.
However, I found out that by selecting the Game -> Free Aspect -> "+" we can explicit specify the height and width of the image we need.
