### ISSUE TITLE
Key points annotations

### ISSUE THREAD

**Issue by soans1994** [Unity-Technologies/com.unity.perception#141]
Can the unity perception tool export keypoints location from 3d model to 2d coordinates into a text file?
Thank you

**Comment by JonathanHUnity** [comment]
Pose capture support is on our near-term roadmap, so stay tuned. In the meantime, you can compute and export this information yourself using a [custom annotation](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/DatasetCapture.md#custom-annotations-and-metrics)

**Comment by soans1994** [comment]
Thank you for you kind support. We will be waiting for the future updates. I will look into custom annotations.

**Comment by sleal-unity** [comment]
@soans1994 I'm happy to note that we've just released our new our keypoint and pose estimation tools as part of the latest update to the perception package (0.7.0).

To get started, I'd recommend pursuing the new [Human Pose Estimation Tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/HPETutorial/TUTORIAL.md) which will walk your through the major features of the new tooling.

**Comment by soans1994** [comment]
@sleal-unity 
Thank you so much for the update. The tutorial looks very promising.

**Comment by soans1994** [comment]
Hello again, 

I have some queries regarding the human pose estimation keypoints extraction. 
1. The skeleton objects under the player model are the keypoints we extract. Are those the same objects responsible for the movement of the 3d model? 
2. I want to create a simple 3d mesh of a sleeping person, how can i perform this?

**Comment by JonathanHUnity** [comment]
1. These objects' locations are driven by the animation system that move the geometry in the 3d model, yes. Here is an overview of the animation system in Unity https://docs.unity3d.com/2017.4/Documentation/Manual/AnimationOverview.html
2. You are free to do either one by writing your own randomizers.
3. You need an animation of a sleeping person. One useful resource for this is Mixamo. Here are some results I found with a quick search https://www.mixamo.com/#/?page=1&query=sleeping&type=Motion%2CMotionPack

**Comment by soans1994** [comment]
@JonathanHUnity Thank you for your suppport, i will cehck out the useful links provided.

**Comment by soans1994** [comment]
Hello, 

I want to create a new animation for the human model, can you give me links for the tutorial. Also i checked the default animation files in the human pose perception package.  The inspector window has model, rig, animation, materials options. Can i acheive different animations by editing these parameters? How can i view the joints responsible for the animation?

Thank You
