### ISSUE TITLE
Enhancement: export COCO format natively or add converter tool

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#152]
It looks like atm we get JSON exports from creating the synthetic datasets but will have to write a converter to push it into coco?
Most obj detection is based around Coco format so adding this would be useful.
I did see something in a thread saying you had opted against including this (not sure if that's still correct), but thought it was worth opening an express issue to track the status, even if it just gets closed as won't do.  If so, are you interested in a PR to add a converter as I'll need to write this regardless at least for 2D obj detection.
I do think it would add a lot of user benefit to be able to export directly to Coco format without running a secondary utility.
Thanks!

**Comment by lessw2020** [comment]
I've written the coco converter for 2D bounding boxes and now training with the generated coco files.  
One note, which I guess I'll open an issue on, is the current perception export files don't actually export the generated image sizes.  For rescaling dataset images, this is vital and hence why it's included in coco format. 
I had to add some code to open the respective files to get the image sizes, which works but seems better to have this info exported.

**Comment by Tylersuard** [comment]
I'm interested in this too.  I mean, the annotations Unity generates are useless unless we can get them into a format that is usable for training a model.

**Comment by lessw2020** [comment]
I can't publish the converter I wrote at work, but I'm making a new one from scratch on my own time and should have it ready to use shortly.
https://github.com/lessw2020/perception_tools

**Comment by lessw2020** [comment]
It's ready for use now - recommend the notebook but there's also a script. 

https://github.com/lessw2020/perception_tools

![begin_processing](https://user-images.githubusercontent.com/46302957/111084384-58551600-84cf-11eb-9e2c-b0b0862d089d.JPG)

![convert_perception](https://user-images.githubusercontent.com/46302957/111084408-7753a800-84cf-11eb-8c4c-29c6d96ca3e6.JPG)

![convert_complete](https://user-images.githubusercontent.com/46302957/111084424-8a667800-84cf-11eb-8f7e-912958bdeada.JPG)

**Comment by adason** [comment]
Related https://github.com/Unity-Technologies/datasetinsights/issues/159

**Comment by JonathanHUnity** [comment]
For better tracking, we'll merge this and related requests into https://github.com/Unity-Technologies/com.unity.perception/issues/251
