### ISSUE TITLE
how to rotate items already rotated to face the camera (ala x=-90) in clock-wise randomization?

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#155]
I must be missing something obvious, but having spent some time on it I can't find the solution and thus posting this here for input.
Much like the prefabs that came with the tutorial, I have my prefabs moved to -90 x rotation so that their front now faces the camera during synthetic generation.
That all works as expected.
However, now I want to to rotate the camera facing objects, so that they are randomized 0-359 degrees in a clock wise type rotation.  
By rights, this should be rotation along the Y axis based on the rotation gymbal that is showing.
However, I find that rotating the Y or Z axis end up moving the object the along the exact same rotation plane...and am unable to accomplish the rotation of the object in a clock-wise fashion.  This seems to repeat with the tutorial objects as well so it's not a prefab issue.
I think some images will help show the problem so let me attach:
Here's my synthetic 3d model as imported. The view is from the camera direction, slightly up and to the right to show it better. 
![prefab_start_camera](https://user-images.githubusercontent.com/46302957/105126822-6caf0080-5a94-11eb-8422-aa062a9d3dce.JPG)
If I run a scenario like this, then all I will see is the very top of the item since it was built flat...you get this:
![prefab_start_view](https://user-images.githubusercontent.com/46302957/105126909-9405cd80-5a94-11eb-8f87-c95d60c9571c.JPG)
So, much like the tutorial prefabs I align the prefab rotation to be set with -90x.  Now you see the face (albeit upside down) but that gets things going:
![prefab_start_90x](https://user-images.githubusercontent.com/46302957/105126959-ada71500-5a94-11eb-97cf-4608a7ceee1e.JPG)
Now what I want to is to randomly rotate them along this (y axis) so that they are randomized as shown by the blue arrow:
![prefab_want_to_rotate](https://user-images.githubusercontent.com/46302957/105127008-c7e0f300-5a94-11eb-92e9-7b300ad4f1c1.JPG)
However, the issue is that regardless of whether I rotate the Y axis or the Z axis...the object moves exactly the same rotation angle. (??)
Here's Y with 45:
![rotate_y_45](https://user-images.githubusercontent.com/46302957/105127253-56557480-5a95-11eb-8349-7d2d77aca3c5.JPG)
and now Z with 45 - identical rotation:
![rotate_z_45](https://user-images.githubusercontent.com/46302957/105127272-61100980-5a95-11eb-99c6-33ef4a819aed.JPG)
and a bit shockingly, if I have both Y and Z with 45...it now makes effectively a 90 degree rotation to show 100% the rotations are now moving on the identical rotation plane.
![yz_45_cumulative](https://user-images.githubusercontent.com/46302957/105127312-7d13ab00-5a95-11eb-8f9b-66732e47a2e2.JPG)

And that's the issue here - how do we have a rotation randomized to rotate it like a clock hand once rotated to face the camera?
Thanks!

**Comment by mkamalza** [comment]
Hi Less,

The issue where rotating around Y and Z has the same results happens when the prefab is rotated. The root cause is [Gimbal Lock](https://en.wikipedia.org/wiki/Gimbal_lock) which we don't need to get into. But to fix the issue, the simplest solution would be to place your object inside another object in the scene, and then rotate the parent object. So the steps are:
- Place prefab in scene
- Create empty GameObject
- Drag the prefab previously placed in the scene into the empty GameObject


![Jan-20-2021 10-22-54](https://user-images.githubusercontent.com/11081204/105218018-7d4d8e00-5b09-11eb-8bdb-f6820cfc5df5.gif)

**Comment by lessw2020** [comment]
Hi @mkamalza  - thanks a bunch for the explanation!  I will read up on gimbal lock but that definitely clarifies.  
Let me try resetting to no pre-rotation (0,0,0) for the prefab, and do that solely in the scenario as that would be easier than pushing each item into a gameobject.

**Comment by lessw2020** [comment]
I tested resetting the prefab to 000 and then using the randomization tag set x to -90 (constant) and then tested modifying both Y and Z to 90 (constant).
It still encounters gimbal lock, as the 90 Z and 90 Y both result in the same side view rather than rotation along a clock hand axis. 
(note I thought I had tried that yesterday as well but did it again now to eliminate any variables).
I'll try pushing it into a game object pre-rotated and see if I can get it to rotate as desired in the scenario.

**Comment by lessw2020** [comment]
I added the prefab to game object and tried to rotate as desired but no luck so far. 
1 - If I run it w rotation randomizer off, then I see it facing front as expected.
2 - If I turn on rotation randomization, and set X to 0 (constant) then it rotates the object to the top view.
3 - If I turn rotation on and set X to -90 (constant), then it rotates it to the side view.
So it's unclear how we can randomize rotation to preserve it front facing, while leaving the X param untouched from the contained prefab?  (custom rotation script that only samples Y and Z?) 
Note that I added the game object with rotation tag to the scenario, and removed the prefab...so the rotations are applied to the game object directly, which I believe is how it's expected but just noting it to be sure.

**Comment by mkamalza** [comment]
In Unity, there is the notion of global rotation and local rotation. In the former, the rotation is relative to the global X,Y,Z axes and in the latter it is relative to the object's parent. If the object has no parent, these two rotations are the same.

If I understand correctly, in your use-case, you would like the object to rotate in two ways:
- Around the world Z axis, similar to a clock hand
- Around its local Y axis (so the clock hand is rotating around its longest side)

Is this correct?
If yes, one solution would be to have separate rotation randomizers and tags for these two rotations. 
Using the parent GameObject method above, in one randomizer you would randomize the Z **world** rotation of the parent object, and in the other you randomize the Y **local** rotation of the inner object.

Global Rotation Randomizer Tag on parent object:
![image](https://user-images.githubusercontent.com/11081204/105230165-d2919b80-5b19-11eb-8bf8-1e53337496d8.png)

Local Rotation Randomizer Tag on inner object:
![image](https://user-images.githubusercontent.com/11081204/105229847-61ea7f00-5b19-11eb-9de9-99d2fe42755c.png)

Randomizer setup in scenario:

<img src="https://user-images.githubusercontent.com/11081204/105230246-eb9a4c80-5b19-11eb-9591-3a24aa3acb5b.png" width="400">

GlobalRotationRandomizer.cs uses the exact same code from the RotationRandomizer provided in the package, but LocalRotationRandomizer has a key difference. The sampled rotation should be applied locally:

```C#
protected override void OnIterationStart()
{
    var taggedObjects = tagManager.Query<LocalRotationRandomizerTag>();
    foreach (var taggedObject in taggedObjects)
        taggedObject.transform.localRotation = Quaternion.Euler(rotation.Sample());
}
```

This setup's results for me:

![Jan-20-2021 12-24-39](https://user-images.githubusercontent.com/11081204/105231285-7c255c80-5b1b-11eb-865d-bacfc0c4b249.gif)

**Comment by lessw2020** [comment]
That did the trick!!  
Thanks a bunch for this help @mkamalza.
![full_rotation](https://user-images.githubusercontent.com/46302957/105257801-6163df80-5b3d-11eb-95bf-035491276e67.JPG)

btw, if I could ask - how did you make this nifty full rotation gif you showed at the end?  I'd like to use it to show the capability to our internal teams.
Thanks again as this solved a major sticking point here for me.

**Comment by mkamalza** [comment]
You're welcome Less. Glad the issue was solved!
For the gif I used an app named GIPHY capture.

**Comment by VirajVaitha123** [comment]
Hi there,

I am also having this same issue.

Thanks for this useful post, but could you include the full c# scripts for the randomizationtag, and rotation randomisation code?

When I try add the script locally I get this error:
![image](https://user-images.githubusercontent.com/44236859/176634540-d1760c31-8102-46f3-94a1-05d3ed45e998.png)

and the package is ofcourse read only so I can't import there.

Thanks,

Viraj
