### ISSUE TITLE
Request - export image sizes with image generation

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#161]
Currently while perception exports a lot of data with the various annotation files, it doesn't export the generated image sizes. 
Coco format requires the image size and the size info is vital for rescaling of the bboxes during training.
Thus, would ask that image sizes be exported somewhere (i.e. captures_000.json) for easy access.

*I wrote a coco converter utility that reads the data from the annotations to generate coco files for training, but to fill in the image size, which is required in coco format, I have to go inspect every img file to pull the sizes.

Thanks!

**Comment by mkamalza** [comment]
To achieve this, you would need to add custom annotations to your output. Please have a look at this page for an explanation, as well as an example for how to do this:
https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation%7E/DatasetCapture.md
