### ISSUE TITLE
Invisible geometry labels being lost if you manually control rotation...any insight/fixes?

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#168]
Thanks to the help on earlier issues, I've been able to label things with invisible geometry (adding transparent quads) such that 'sub-components' on objects are also labelled.
If I only use the generic random rotation, then labelling works as expected in the captures json.
However, in my situation I have to force the prefabs to rotated so that all items are 'facing the camera'.  We can't do our object detection from the backside of the object or side of the object.
Once I force it to rotate to face the front to the camera..all my invisible geometry is lost. 
I then only get labels for the singular object, and not any of the labelled sub-components.
I've spent hours trying to adjust the quads to be higher on the object, to rotate a containing game object, even rotated the quads as a check...and unfortunately nothing permits the sub-labels to show up once the object is forcibly rotated. 
I guess what I'll try is to redo the geometry with the object pre-rotated, but any input or help here would be appreciated.
Summary - invisible geometry works fine if the object is freely randomized in rotation, but forcing a fixed rotation of the X (to make it face front) breaks the labelling for the sub-components.

**Comment by sleal-unity** [comment]
Hi lessw2020,

Would you be wiling to share a few screenshots? It might help clue me into what's causing your issue.

**Comment by lessw2020** [comment]
@sleal-unity  - definitely.  Let me get those together now to walk you through it.
context - these are Covid diagnostic tests...so as noted, we can't 'read' them unless they face to the camera.

**Comment by lessw2020** [comment]
not sure if related, but now I'm seeing this error about an internal leak, and can't shake it even with a reboot.  The background objects are no longer rotating....so let me make a new scene and rebuild in case that is the root issue.
![internal_leak](https://user-images.githubusercontent.com/46302957/106076493-81a71780-60c4-11eb-91e2-3103df316c13.JPG)

**Comment by lessw2020** [comment]
Well to try and simplify, I can show the issue on the whipping cream prefab.
I followed the procedure in this issue (https://github.com/Unity-Technologies/com.unity.perception/issues/151)
and on the whipping cream made a transparent cylinder to cover the cap, and also a transparent quad to cover the label:
However, once I display it in game view, then I only get the label for the cap and object, not the quad.
![base_whipping_cream_geometry](https://user-images.githubusercontent.com/46302957/106079675-84a50680-60ca-11eb-9d2c-af39b6c1041c.JPG)
![whipping_cream_cap_cylinder](https://user-images.githubusercontent.com/46302957/106079677-84a50680-60ca-11eb-908c-8bfc8113e8bd.JPG)
![whipping_cream_quad](https://user-images.githubusercontent.com/46302957/106079678-853d9d00-60ca-11eb-82ce-2de95288a8ba.JPG)

**Comment by lessw2020** [comment]
and then in game view, no label:
![whipping_cream_no_label](https://user-images.githubusercontent.com/46302957/106079726-9c7c8a80-60ca-11eb-918d-627401dbef76.JPG)

**Comment by lessw2020** [comment]
Alright, bit of a breakthrough.  If I use an invisible cube, and not a quad...now it shows with labelling as expected (in game view..haven't generated with it).
![cube_label_working](https://user-images.githubusercontent.com/46302957/106081477-d1d6a780-60cd-11eb-8a6b-524e04644b66.JPG)

**Comment by lessw2020** [comment]
so this seems to be a bug with quads.  Note that I also tested making the material non-transparent, in case that was the root issue and also made it obnoxiously large...that showed the same issue of visible from side angle (where it projects past the carton) but once rotated to face on, it disappears and is not shown nor labelled.

**Comment by lessw2020** [comment]
I'll try tomorrow to rebuild the prefabs with cubes for the invisible geometry and see if that allows a workaround for now.

**Comment by lessw2020** [comment]
Note that I'm using HDR pipeline and 2020 recent.

**Comment by sleal-unity** [comment]
Off the top of my head, one thing that might be causing this issue with the quad specifically is that mesh triangles are uni-directional. They are only drawn when the mesh points are enumerated counter-clockwise with the virtual camera. You wouldn't be able to tell this with the cube you used as a replacement since its quads are configured by default to point outward, but if you moved the scene's camera inside the cube, you may notice uni-directional nature of the mesh triangles. I believe the default plane mesh is also uni-direction in this way.

I am thinking your quad might be reversed since in the second screenshot we can see a small slice of the back side of the quad actually being captured.

Anyways, to check if this is the issue, you can try giving the quad's transform 180 degrees twist on any axis.

**Comment by sleal-unity** [comment]
I noticed your comment that you tried rotating the quad to make sure it wasn't backwards, so I have only one other suggestion. I would check to make sure that the quad is not actually inside the carton and rather placed slightly offset in front of the carton. If you place the quad too close to the carton's outer face you may be run into a Z-fighting issue. [Wikipedia has great article](https://en.wikipedia.org/wiki/Z-fighting) explaining this computer graphics phenomena.

**Comment by lessw2020** [comment]
Hi @sleal-unity  - you nailed it! 
 It was in fact a rotation issue with the quad being uni-directional (something I had no idea about).   I did find I had to rotate on the X-axis, not the Y for my specific quad (possibly due to it already being rotated from creation time).  With a visible material enabled, then it suddenly appeared...both visually and started labelling as expected :)
First, **huge thanks** to your help as this would have been basically impossible to surmise and I already spent hours of frustration/effort on it today. 
I guess that leads to the question of going forward, how would someone know if their quad is facing 'out' to avoid this...esp if it's a transparent quad?  Is there a visual way to check during design (ie. not by adding a texture and running in game mode).
At least now I know the issue and I'll go rotate all my quads tomorrow and hopefully can start training with the full labelling going which will be a big moment.
Thanks again!

**Comment by lessw2020** [comment]
Also, thanks to the tip re: z-fighting- that may have been happening to some degree as I was working to fix the rotation/out face issue, and moving it around. 
Will make sure everything is slightly offset and not planar!

**Comment by JonathanHUnity** [comment]
@lessw2020 a good way to test this is to make the object non-transparent and make sure you can see it from all the angles you are interested in. Definitely a downside of invisible geometry is it's harder to debug. Glad you got it figured out!
