### ISSUE TITLE
question - possible / best way to dynamically randomize masks and/or materials for prefabs during generation?

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#199]
For the objects I am detecting, we frequently have QR codes or id numbers with text on the objects.  In the real life scenario, every object will have it's own unique QR code and random text id written underneath it.

Thus, I'd like to be able to randomly apply varying QR codes and hand written number as masks onto the prefab for each image.  
However, by it's nature, it seems prefabs are effectively 'fixed'...thus right now I am making a broader suite of prefabs, each with it's own QR code, but that feels a bit crude esp as we get into a matrix of prefab type * qr code * id text to try and create dynamic objects to mimic closer to the flow of real incoming data for it to train on.

Thus my question - is there a way to dynamically swap out masks/materials during the image OnIterationStart() or similar so that a single prefab/model could have it's masks/materials dynamically selected and assigned to randomize it on each image? 
(simple example, having 100 QR codes as masks available, and a single base model - and it randomly pulls QR code from that set and puts that one on the prefab, and it's used for that individual image...on the next image, again one of the 100 is randomly selected for the next image, etc).
Related - if it's possible to swap/randomize materials in the same manner, it would reduce the need to premake so many prefabs each one hard coded with a given result material.

Right now I'll continue on the path of 'lots of prefabs' with hard coded QR / result materials, and randomly selecting from those, but if there is a more elegant way to do this in code both for masks and materials, would appreciate any advise on how to do it!

**Comment by sleal-unity** [comment]
Hi Less!

Yep, you can do this by creating a randomizer that swaps out the QR code texture (2D pixel data or images are often called textures in 3D graphics) on the part of your GameObject that displays the QR code. With this randomizer, you can author just one generic prefab with an allocated space for the QR code and it will work for all the QR code images you load into your project.

Our existing [TextureRandomizer](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/TextureRandomizer.cs) is a good example for how to accomplish this. Here are the basic steps:
1. Load your QR code JPG or PNG files into the Assets folder within your project. These images are referred to as textures by the Unity game engine.
2. Create a QrCodeRandomizerTag class. This tag will mark all objects that need to have their QR code texture swapped out for a new one.
3. Create a new QrCodeRandomizer class
4. Add a public Texture2DParameter field to this randomizer
5. Code the randomizer to apply a randomly sampled texture to each GameObject that needs a QR code upon each new iteration
6. Add this new randomizer to your scenario and add your QR code textures to the Texture2DParameter exposed on the QrCodeRandomizer in the inspector window
7. Add a QrCodeRandomizerTag to any GameObjects/Prefabs in your scene that need to have their QR codes swapped randomly

Here's some example code for the QrCodeRandomizerTag  and the QrCodeRandomizer:
```csharp
using UnityEngine;
using UnityEngine.Perception.Randomization.Randomizers;

[AddComponentMenu("RandomizerTags/QR Code Randomizer Tag")]
public class QrCodeRandomizerTag : RandomizerTag { }
```

```csharp
using System;
using UnityEngine;
using UnityEngine.Perception.Randomization.Parameters;
using UnityEngine.Perception.Randomization.Randomizers;

[Serializable]
[AddRandomizerMenu("Example/QR Code Randomizer")]
public class QrCodeRandomizer : Randomizer
{
    /// <summary>
    /// The list of QR Code images to apply to tagged objects
    /// </summary>
    public Texture2DParameter qrCodeTextures;
    
#if HDRP_PRESENT
        static readonly int k_BaseTexture = Shader.PropertyToID("_BaseColorMap");
#else
    static readonly int k_BaseTexture = Shader.PropertyToID("_BaseMap");
#endif
    
    protected override void OnIterationStart()
    {
        var tags = tagManager.Query<QrCodeRandomizerTag>();
        foreach (var tag in tags)
        {
            var renderer = tag.GetComponent<Renderer>();
            renderer.material.SetTexture(k_BaseTexture, qrCodeTextures.Sample());
        }
    }
}
```

Sample images I generated using the above code:
![image](https://user-images.githubusercontent.com/53197518/107305216-2b34c400-6a48-11eb-9466-9decf3d2fdf2.png)
![image](https://user-images.githubusercontent.com/53197518/107305329-659e6100-6a48-11eb-8a81-611a19a814b1.png)
![rgb_2](https://user-images.githubusercontent.com/53197518/107305164-0fc9b900-6a48-11eb-9f1f-1434b60d2553.png)
![rgb_4](https://user-images.githubusercontent.com/53197518/107305168-122c1300-6a48-11eb-88df-8a6854328664.png)

**Comment by lessw2020** [comment]
Wonderful, thanks again @sleal-unity!  This is tremendously helpful both in terms of how to do it, as well as significantly enhancing the 'true to life' randomization I can do now for our data generation. 
Greatly appreciate all of the info above!!
