### ISSUE TITLE
class labels are randomly incorrect in larger datasets

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#208]
I've had poor training results the past two days and after a lot of tracing backwards, have found that while bounding boxes are always the correct fit, the class labels for those boxes are incorrect at maybe ~20% of the time, and randomly incorrect...and hence the poor training results.

I've confirmed the incorrect labels are present in the captures.json and not a translation into coco issue since I wrote my own coco converter, but hoping to get some insight on how to fix as this is a core issue.  
Note this is not a 'every label is consistently off', but rather randomly the labels are swapped or incorrect.  The boxes always fit nicely, it's the class label that is randomly wrong.

Here's a single example:
![incorrect_detail_label_json](https://user-images.githubusercontent.com/46302957/108143941-8173b980-707d-11eb-8e68-8cff5184ecb9.JPG)
![incorrect_detail_labels](https://user-images.githubusercontent.com/46302957/108143942-820c5000-707d-11eb-870d-0709f02d4e99.JPG)

The bottom box should be 'bottom_nhs' and diagnostic should be in the middle, but in this case as you can see it's flipped.  The actual boxes are correct in terms of their fit.
The class label for the diagnostic is also incorrect though less apparent....but here's an image that shows that random mistake better:
![incorrect_labels](https://user-images.githubusercontent.com/46302957/108144065-be3fb080-707d-11eb-8a0c-19cffc25c00d.JPG)
If you look at the two left images you can see the upper left has the correct type B (note the rounded handle cutout) and bottom left is all rectangular but also labelled as type B (it's a type D).  

I didn't hit this issue on smaller (< 2K ) datasets but I'm seeing this in case on a 6K dataset.  Other changes from working sets are 20 total prefabs (vs 4 or 8) and I also changed from auto-labelling via asset class name to using free form labelling.
I have verified multiple times that the prefabs all have correct invisible geometry.

I'm going to reset and rebuild with 4 and then 8 prefabs and see if I can narrow down the issue here but any insight or suggestions to isolate/ fix would be appreciated.

**Comment by JonathanHUnity** [comment]
We have identified an issue that can cause labels to be incorrect and are currently working on a fix. This problem occurs when all of the labeled GameObjects are destroyed and recreated each frame. One workaround for this is to cache your set of objects instead of destroying and recreating them. An example object caching utility can be found here:

https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Utilities/GameObjectOneWayCache.cs

**Comment by lessw2020** [comment]
Thanks for the info @JonathanHUnity.  
That makes sense as I was previously keeping the items instantiated manually in the scene, but that created ghost labels...so moved to not having anything pre-instantiated when this showed up.
I'll try and setup with caching  so I can keep going and good luck with the fix work.

**Comment by lessw2020** [comment]
I'm attempting to workaround this issue with my own cache handling...however, hitting an issue about a renderer not being attached.  I'm know in URP you have to assign the forward renderer, but I'm in HDP and not sure what/how I should assign a renderer in code.
Any insight would be appreciated - I'll start reviewing the codebase to see if I can find a fix, but wanted to post here in case that is faster and/or other people hit the same thing:
![missing_renderer](https://user-images.githubusercontent.com/46302957/108559985-ea8f4300-72b0-11eb-96c3-25fd8519cce9.JPG)

**Comment by JonathanHUnity** [comment]
"Renderer" in this case is referring to the MeshRenderer or
SkinnedMeshRenderer component. Is there any more information in this error
when you click it in the console? If there is a stack trace it would be
easier to narrow down.
Jon Hogins

**Comment by lessw2020** [comment]
Thanks much @JonathanHUnity!
Further inspection - this is an issue with my models/prefabs having lost their default mesh-renderer on import for some reason, as using the sample dairy creamer as the randomized foreground object works as expected. 
Thus, will trace it backwards on my end and fix, and not a generic issue here.

**Comment by lessw2020** [comment]
Possibly related - I now receive this error on the camera:
![deferred_shader_error](https://user-images.githubusercontent.com/46302957/108608446-c8aec280-737b-11eb-88d7-3f591f16b5b7.JPG)

I then attempted to modify the shader mode of the camera to forward, but am unable to do so (I have no ability to access the dropdown):
![camera_no_choice](https://user-images.githubusercontent.com/46302957/108608461-d8c6a200-737b-11eb-9a56-598af8a44894.JPG)

In theory, per the manual, that seems it is the way to change it:
![manual_lit_shader_selection](https://user-images.githubusercontent.com/46302957/108608468-e3813700-737b-11eb-9a9b-4e0352e28728.JPG)

Could I get any advise on how to switch to forward mode?  I am using transparent, invisible geometry for my labelling (with HDR/Lit shader).  
I've been flipping around the menus and interfaces trying to fix this to no avail.
Thanks in advance!

**Comment by JonathanHUnity** [comment]
Sure. Find the HDRenderPipelineAsset in your project - it is probably in
your settings folder. With that selected you should be able to find the
setting in the inspector.

Let us know if you can't find it.

**Comment by lessw2020** [comment]
Thanks a ton @JonathanHUnity!  I found it, as you said, in the settings folder.
That also finally got rid of the error, which I had spent a lot of time on today since I didn't realize there was this settings asset to begin with.  
I realize the tutorial focuses on URP, but it might be worth adding a blurb on this for HDRP?   I didn't even realize there was this concept of a 'settings asset' nor where it lived, so the only asset I thought it meant was the camera settings and hence all the time spent this morning flipping around trying to active the inactive custom frame settings. 
Thanks again, really appreciate your help esp on a Saturday!

**Comment by JonathanHUnity** [comment]
Good feedback! Sorry to hear you spent so much time on this. We'll try to
make this more clear.

**Comment by JonathanHUnity** [comment]
This bug was been resolved in [Release-0.8.0-preview.2 ](https://github.com/Unity-Technologies/com.unity.perception/releases/tag/Release-0.8.0-preview.2 ). Thank you for the report!
