### ISSUE TITLE
How do we add a delay between captures?

### ISSUE THREAD

**Issue by rajshekarreddy97** [Unity-Technologies/com.unity.perception#221]
I would like to add a delay (in real-world time, not simulation time) between each iteration/capture. How do I go about this? It's a bit urgent, so any help would be appreciated. Thank you!

**Comment by mkamalza** [comment]
Hi,

The Perception Camera currently only supports timing based on simulation time. The rationale here is to be able to have deterministic simulations that produce the same output regardless of the capabilities of the underlying hardware.

With the current system, you can introduce delays between captures using the "Frames Between Captures" property of Perception Camera. In the example shown below, the camera starts capturing at frame 10, and then skips 9 frames between consecutive captures.

![image](https://user-images.githubusercontent.com/11081204/109035306-5d1b6c80-767d-11eb-8465-810446e58522.png)

With these values, the captures look like the gif below. Notice how the bounding boxes only update periodically (every 10th frame), and not every frame.

![Feb-24-2021 08-34-41](https://user-images.githubusercontent.com/11081204/109033574-a2d73580-767b-11eb-8785-488d1b347ea6.gif)

Would this work for you? If not, can you please elaborate a bit on your use-case and how real-world time is needed?

**Comment by rajshekarreddy97** [comment]
Hey, yes I think this works for me. My use-case is that I'm generating raytraced synthetic images and I'm using Unity's Path Tracing. Hence, I need to wait for the path tracing to finish tracing between each capture.

**Comment by mkamalza** [comment]
Sounds great. Please let us know if you come across any issues once you have tried it.

**Comment by rajshekarreddy97** [comment]
Do you know any api that lets me know when the Path Tracing is finished? Right now, there's a loading bar that appears at the bottom of the game view and I am using this as reference and doing a trial and error.

**Comment by sleal-unity** [comment]
@rajshekarreddy97 

Although I don't have too much experience with Unity HDRP's latest ray tracing tools, my impression from the [Unity HDRP documentation](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.3/manual/Ray-Tracing-Path-Tracing.html) and from my own experiments has indicated that the number of frames needed for the path tracing loading bar to complete is equivalent to the maximum samples configuration in the path tracing volume settings override.

For example, if you copy the path tracing settings as shown below, I believe you would need 128 frames per iteration configured for your scenario to properly path trace your scene.

![image](https://user-images.githubusercontent.com/53197518/109732452-0ed10680-7b72-11eb-879e-ede6e38b0eda.png)

**Comment by rajshekarreddy97** [comment]
@sleal-unity I recently realized that too. I think this would be sufficient for me. Thanks!
