### ISSUE TITLE
RGB images not being saved

### ISSUE THREAD

**Issue by arjunrao796123** [Unity-Technologies/com.unity.perception#225]
My images, both RGB and semantic images, were being saved in the respective folder.
Now only the sematic segmentation images are being saved. I have checked the 'Save RGB to disk option' but the folder for RGB images is still empty.
Anything else I can change or adjust?
Thanks in advance.

**Comment by mkamalza** [comment]
Hi,

There aren't any other settings besides the one you mentioned. Have there been any changes to your project that could have caused this? Also, does the console show any errors?

**Comment by arjunrao796123** [comment]
> Hi,
> 
> There aren't any other settings besides the one you mentioned. Have there been any changes to your project that could have caused this? Also, does the console show any errors?

It was working up to a point and then it suddenly stopped saving the images. I do not think I made changes to any camera script. I was just working on creating new background and foreground classes. 
For now, I have just started a new project and I am not facing the issue. I am constantly monitoring the image folder now after every change I make.

**Comment by mkamalza** [comment]
There is one potential issue that could be causing this. There is a renderer feature that is added to the Forward Renderer asset during runtime, and sometimes this feature is not properly removed after you stop playback. This can cause rgb images to stop being produced. To check, open the Forward Renderer asset in your project, and make sure the only Renderer Feature that is added is Ground Truth Renderer Feature. If there is another one, remove it.

**Comment by arjunrao796123** [comment]
This fixed the problem. I changed it to only one renderer feature and the RGB images are now being saved.
Thank you.
