### ISSUE TITLE
YOLO darknet labels

### ISSUE THREAD

**Issue by solder-fumes-asthma** [Unity-Technologies/com.unity.perception#226]
Hello, 

I would like to use this tool to generate [YOLO-ready labels](https://github.com/AlexeyAB/Yolo_mark/issues/60#issuecomment-401854885). However, I lack the knoweledge on Unity and C# to make a script myself. Is it possible that you already have any tool available for doing this? 

Thanks in advance.

**Comment by mkamalza** [comment]
Hi, we currently do not offer a tool for this type of conversion. However, you can create your own convertor with python or another language that you know, without needing to use code in C#. 
The output that the Perception package produces is in JSON format and fairly straightforward. There are captures_###.json files that include the outputs of the labelers (e.g. in case of bounding boxes, these outputs contain the x, y, width, and height of the bounding boxes of the tracked objects in the 2D coordinates of the produced images). Each captures_###.json files contains entries for multiple frames, and each frame entry contains the file-name of the corresponding RGB image that was also produced.

**Comment by solder-fumes-asthma** [comment]
Hello, 

Yes, I wrote said translator and it works just fine. Just wanted to know if there was something out there already that could save me that extra step.

Thanks and best : )

**Comment by Tylersuard** [comment]
@solder-fumes-asthma May I please have access to said translator?

**Comment by solder-fumes-asthma** [comment]
Sure! Sorry if I am a bit late. Paste and run this with python. 

```
import json

'''
This script is used to convert JSON labels from the Unity Perception package to
YOLO darknet annotation format.

The only input taken here is the json file. Its path and the picture sizes
MUST BE HARDCODED. If there are various json files just run the program as many
times changing the file name. The output will fall on the directory you are
calling this script from.
'''

pic_height = 680
pic_width = 680

with open('./captures_000.json', 'r') as file:
    big_json_file = json.load(file)

for picture in big_json_file['captures']:
    filename = picture['filename'].split('/')[-1]
    filename = filename[:-4] + '.txt'

    with open(filename, 'w') as annotation_file:
        for bbox in picture['annotations'][0]['values']:
            annotation_file.write(
                '%d %f %f %f %f\n' % (
                    bbox['label_id'],
                    (bbox['x'] + bbox['width'] /2)  / pic_width,
                    (bbox['y'] + bbox['height']/2)  / pic_height,
                    bbox['width']                   / pic_width,
                    bbox['height']                  / pic_height
                    )
                )
```

**Comment by z3lx** [comment]
To anyone stumbling upon this issue and feeling unsatisfied with the proposed solution, I have written a unity editor extension to convert SOLO datasets into YOLO format [here](https://github.com/z3lx/solo2yolo).
