### ISSUE TITLE
upgraded Unity from 2020.2.1 to 2020.2.6 - null reference errors x 18, but all same issue - any fix?

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#228]
I realize I went into unsupported land here, but since it was a minor upgrade (.1 to .6) and I wanted to test out the MasterStack feature, I upgraded.
Anyway, the result is a bevy of null reference errors that block me from seeing the inspector tab completely, but they are all the same error pointing to the same line of code.  
Not sure if there's a quick fix or if I just need to rebuild in the previous version but wanted to post out for any feedback in case this is an easy fix.
![upgrade_unity_nullreference](https://user-images.githubusercontent.com/46302957/109545087-3d20ea00-7a7d-11eb-9a77-1efa11516369.JPG)
and clicking on these goes to the same code:
![upgrade_code_error](https://user-images.githubusercontent.com/46302957/109545123-49a54280-7a7d-11eb-951e-361840134f63.JPG)

**Comment by lessw2020** [comment]
Note - I'm just rebuilding in 2020.2.1 for now as it's < 30 minutes to do that, so I'm not blocked.  
Mostly wanted to post for awareness and in case there is an easy fix since it looks like it's just a space optimization line that's the issue.
If it's not helpful though, go ahead and close as it may be something already addressed internally in the next version, but not released etc. and thus not productive to deal with.

**Comment by sleal-unity** [comment]
Hi Less!

Yep, I ran into this UI error myself just last week. I've got a fix integrated into master for this issue ready for the next release. However, I did run into some issues I haven't seen before when upgrading one of my test HDRP projects to 2020.2.6f1 from 2020.2.4f1. I'll post again if I come across any solutions here.

**Comment by lessw2020** [comment]
Hi @sleal-unity  - great, thanks for the update.
Glad to hear about the fix pending in the next release, that was ultimately the main point of my posting here and glad that it wasn't specific to my project.
I rebuilt in 2020.2.1 and moving along nicely there for now.
Thanks again!
