### ISSUE TITLE
DepthGrab.cs won't work with Perception

### ISSUE THREAD

**Issue by paszti96** [Unity-Technologies/com.unity.perception#229]
If I use the Perception module and the DepthGrab.cs script (Unity.Simulate.Capture), then DepthGrab will generate only black images. 
Do you know the cause of this problem and how could I resolve it?

**Comment by StevenBorkman** [comment]
Hi, thanks for reaching out. My hunch is that you do not have depth enabled in your render pass settings. If you are using URP check your `Universal Render Pipeline Asset` file in Assets/Settings.
![image](https://user-images.githubusercontent.com/66975693/109568251-a40dc580-7ab4-11eb-918f-8b89f0a5ec9c.png)
Verify that 'Depth Texture' is enabled.

**Comment by paszti96** [comment]
I use HDRP, but the script only creates full black images if the Perception module is used. If I try to save the depth images 
without Perception module added to my camera, it works fine. 

My settings are the following:
![image](https://user-images.githubusercontent.com/21191977/109645659-73329c80-7b57-11eb-95bf-7e529ea9872f.png)
![image](https://user-images.githubusercontent.com/21191977/109646559-a9245080-7b58-11eb-834f-37b0ef4b8254.png)
