### ISSUE TITLE
Improving tightness of auto-bounding boxes during rotation - any options?

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#238]
the sim to real gap (based on IOU of holdout sets) on one of my datasets has been much higher than other sets.  
After randomizing a number of items to try and reduce that, I have effectively found that the core issue is that the bounding boxes that are generated during rotations are ballooning more than needed. 
That results in non-rotated examples having a similar excess buffer and accounts for the lower sim to real showing on this dataset.
Thus my question is there any options to reduce or tighten how bounding boxes are resized to account for randomized rotations?

Let me show an example - first one that is basically vertical.  The bounding boxes segment up the diagnostic - the bottom of the 'text' portion runs along the bottom of the IVD box, and above the read window.  
The top of the diagnostic portion goes right against the bottom of the text portion.  
(these junctures will show the issue in the next photo).
![starting_space_mesa](https://user-images.githubusercontent.com/46302957/110217496-1c83d600-7e69-11eb-8b0c-e87ec2fe3533.JPG)

Now when we add rotation, then top of the diagnostic goes way higher than it needs to, and the bottom of the text also extends much further than needed.
I've tried to highlight with the red bubble on the side to show the gap, but basically the top of the diagnostic can still be below the IVD box.  Similarly the bottom of the text box doesn't need to drop all the way down to go below the read window. 

![excess_space_rotation](https://user-images.githubusercontent.com/46302957/110217538-5e148100-7e69-11eb-899c-09902eece9f1.JPG)

Thus, we now 'teaching' the AI it should have these excess buffers and hence the lower performance on the IOU holdout.
![h6_pred_2k_synthetic](https://user-images.githubusercontent.com/46302957/110217665-2528dc00-7e6a-11eb-8fe5-054c4379a7ce.JPG)
vs the result of tuning with hand labelled real images:
![simreal_h6_prediction](https://user-images.githubusercontent.com/46302957/110217678-3a056f80-7e6a-11eb-8d2b-e505d5666aaa.JPG)

Note that I have rotations in my 'real image' training and we don't see this excess buffering...thus is there a way to tune/modify the bounding boxes generated for rotated items to tighten their expansion?

**Comment by lessw2020** [comment]
*related but the outermost box (rdt) adjust quite well during the rotations and as a result we get a nice IOU score on the holdout.  It's these internal boxes that don't seem to adjust well and thus create this excess buffering effect.

**Comment by lessw2020** [comment]
I should also add the internal bounding boxes are from invisible quads floating above the rdt, vs the outer rdt one is the prefab itself.

**Comment by lessw2020** [comment]
this example might be even cleaner to see - basically the text bounding box should not go above the large blue box...yet on rotation it promptly expands into that space when it shouldn't.  This thus creates an excess buffer condition as well. 
Oddly the top box handles the rotation nicely (the top of the text box should be where the bottom of the top box is, not expand like it's doing).
![top_excess_buffer](https://user-images.githubusercontent.com/46302957/110218137-cd3fa480-7e6c-11eb-9949-3ca8c80b82d5.JPG)

**Comment by lessw2020** [comment]
in some cases, there's also the reverse - the bounding box is too small and cuts off where it should not.  In the image below you can see how the read windox box is too small and cuts off about 1/3 of the window it should contain.  (tried to highlight with the red half circle to show the missing delta).
![too_small_box](https://user-images.githubusercontent.com/46302957/110218574-4d670980-7e6f-11eb-97c5-4a50154410dd.JPG)

**Comment by sleal-unity** [comment]
Hi Less!

Could you share a screenshot of your prefab, but with colored materials attached to the invisible quads? I'd like to get a better idea of how the labels on your RDTs are structured with respect to the underlying prefab.

Also, from my current understanding from looking at the images you've shared, it doesn't seem as though these axis aligned bounding boxes (AABB) are misbehaving per say, more that they're not well suited for accurately marking the labeled area when the object is rotated close to a 45 degree angle. This is a common problem with using AABBs when estimating object sizes for game engine tasks like volume estimation or collision detection.

Are you suggesting that something like an oriented bounding box (OBB) would be more useful?

Here's a [Wikipedia article](https://en.wikipedia.org/wiki/Bounding_volume) on the subject of different bounding box types that may help explain my mindset here. Specifically, this paragraph here:

> In many applications the bounding box is aligned with the axes of the co-ordinate system, and it is then known as an axis-aligned bounding box (AABB). To distinguish the general case from an AABB, an arbitrary bounding box is sometimes called an oriented bounding box (OBB), or an OOBB when an existing object's local coordinate system is used. AABBs are much simpler to test for intersection than OBBs, but have the disadvantage that when the model is rotated they cannot be simply rotated with it, but need to be recomputed.

And here's a drawing I used to illustrate these two bounding box strategies when discussing this topic with a colleague of mine recently:

![Bounding Box Types](https://user-images.githubusercontent.com/53197518/110225907-a26e4400-7e9e-11eb-9bb1-ae90ffc8889a.png)

**Comment by lessw2020** [comment]
Hi @sleal-unity!
Thanks a ton for the fast response.
So, in further review, you are correct - algorithmically you are containing all 4 corner points, which is correct for the AABB type boxes (so this is a closable issue and apologies for the false alarm). 

We do our own rotation in our training pipeline for real images, but the difference visually is that all the other rdt's are long and rectangular...this one is much more squarish than any other.  Thus, we more typically see things like this:
![rotated_rdt](https://user-images.githubusercontent.com/46302957/110228936-0eaa7100-7eba-11eb-9dab-549449937999.JPG)

A rectangle rotating within a square still fills it more efficiently in terms of corner points with less excess buffer, vs a square rotating within a square bloats it out and visually it was unexpected to see, such that I thought it was off on the labelling. 

I also tested using minimal-rotation tonight, and ultimately that's not the reason it's being goofy on the sim to real holdout testing for this RDT as I had thought.

To your point re: other options - we have looked at switching to 4 point polygons as a workaround for rotated items, and in fact put in support for it in our codebase.  But ultimately it was painful on the labelling side, so we didn't end up using it.

If you wanted to explore adding OBB or gliding vertex or 4 point polygons, that would be super interesting.  I haven't seen OBB before but here is the paper on gliding vertex and explanation:
![gliding-vertex](https://user-images.githubusercontent.com/46302957/110229491-a611c300-7ebe-11eb-968c-e4e43371debd.jpg)
https://arxiv.org/abs/1911.09358
  
Anyway, pls go ahead and close this one as it is correctly computing based on AABB's.

**Comment by sleal-unity** [comment]
@lessw2020, thanks for the input as always!

Your comments about 4 point polygons reminds me of another similar conversation I had a month ago or so. I might need to investigate this more myself.

Anyways, if your labeling requirements change, just open up a new GitHub issue with the kind of functionality your looking for. It's always good to hear ideas directly from people using our tools!
