### ISSUE TITLE
How to disable/enable labeling on objects?

### ISSUE THREAD

**Issue by RocketFan** [Unity-Technologies/com.unity.perception#243]
I need to controll which objects can be labeled on perception camera.
So I tried to disable Labeling script on every object when his instance was created,
like on the code example down below
```
var instance = gameObjectOneWayCache.GetOrInstantiate(prefabs.Sample());
var labeling = instance.GetComponent<Labeling>();
labeling.enabled = false;
```
But it does not change anything. 

I want to simply disable labeling on every object and then activate it on the specific ones,
which for example are inside some range to camera view. 
I know how to find that specific objects, but problem is I can't disable labeling on them.

Is there any option to do this?

**Comment by mkamalza** [comment]
Hi,

This functionality is unfortunately not supported currently. If a Labeling component is enabled when the player starts, it will remain active in ground truth generation, even if disabled midway through.

Can you please elaborate a bit more on your specific use case and tell us which labeler you are using? This way, we may be able to recommend workarounds or provide you with some custom code to help you overcome this issue.

**Comment by RocketFan** [comment]
Hi, thanks for quick replay.

I want to have only labeled thoes objects that are inside max distance to perception camera and thoes that are not cropped, as in the image below.

![shapes_labeling](https://user-images.githubusercontent.com/42043913/110798042-0bc4cd00-827a-11eb-80d2-62cfbb4ef3b6.png)

**Comment by mkamalza** [comment]
Thank you for the explanation. We are hoping to add this functionality soon, but for the time being, there are a few things you could try that might work:
* For each labeled object you could have two clones. You only assign the Labeling component to one clone. At any given time only one of these objects has an enabled renderers. When you need to disable labeling, you would switch on the renderers of the object that does **not** have a labeling component, and vice versa.
* A simpler workaround would be to just disable rendering on the objects that you do not wish to have labeled. Depending on how much this affects the eventual performance of the model trained on this data, it might be a viable solution.
* The RenderedObjectInfo labeler produces a metric for the number of visible pixels of each labeled object in the output dataset. You could process the output after the fact to filter out objects that have fewer than a certain threshold number of visible pixels. This may be a viable workaround if there is a direct relation between the visible size of the objects and their distance to the camera.

**Comment by JonathanHUnity** [comment]
As of Release-0.8.0-preview.2, you can now control the labeling by enabling or disabling the Lableing component. Thanks for the request!
