### ISSUE TITLE
Create annotations only for objects above size threshold.

### ISSUE THREAD

**Issue by Neurotaur** [Unity-Technologies/com.unity.perception#247]
Hi,
Can Perception create annotations only for objects that are above a minimum size? (see picture with example)

![image](https://user-images.githubusercontent.com/6352684/110850254-2e081c00-8275-11eb-9d97-aa124732ba30.png)

**Comment by mkamalza** [comment]
Hi,

We currently do not have this feature, so the best solution would be to post process the dataset to filter out objects that have fewer than a minimum number of visible pixels. This number can be generated using the RenderedObjectInfo labeler, and is stored in the metrics.json files.
