### ISSUE TITLE
any recommended prebuilt interior setups?  (default setup is outdoors, but also need to mimic indoor lighting scenarios)

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#252]
I have been using the tutorial config which mimics an outdoor scenario (sunlight, open air) but now need to also do obj detection in indoor (home/office) type of lighting, esp to mimic the softer shadows vs the harsher ones from sunlight.
It seems the only way to mimic that type of ambient lighting/softer shadows is to literally have the requisite walls and interior to get the realistic light bouncing and color pickup, so wondering if there are any prebuilt setups that are pending or recommended, or do we just have to build our own?
I'm using HDRP.
Thanks!

**Comment by sleal-unity** [comment]
Hi Less!

Sorry for the later response than usual. I was going back and forth on how to answer your question appropriately. Though I guess I decided an info dump is probably necessary to understand your use case. In short, creating a randomized interior scene is possible, but choosing what scene properties to randomize and configuring interior lighting can be very tricky. And here's why...

#### Interior randomization

Choosing the scope of randomizations you want to simulate here is key. On one hand. you can just randomize the colors of a 4 walled empty room, place your object in the center and take a picture. On another hand, you could go hard and randomize the wall textures, room layout, furniture and clutter objects, and light sources and end up with a pretty hefty project to implement, not to mention the extensive asset acquisition effort needed to source the objects to fill up your rooms. Based on your question, if you're only interested in basic lighting configurations, maybe the 4 walled empty box is the best place to start.

#### Interior lighting

A project's lighting configuration probably has the greatest impact over any simulation property when it comes to visual output. Unity has many lighting options each of which is designed as different trade off between performance and realism. I will list the 3 most pertinent options that you will likely be interested in.

1. URP baked lighting - The universal render pipeline offers the most performant lighting configurations by using an offline baking process to generate realistic bounce lighting within a static scene and then using simple shadow mapped dynamic lights + light probes to make dynamic (or randomized) objects "fit" into the baked scene. This option provides high FPS, but lacks the visual fidelity needed for interior environments and is geared toward more outdoor like settings. Also, depending on scene randomization complexity, light baking might not even be a good option. Randomly generated scenes will often place objects and adjust lighting in ways that make the new scene incompatible (AKA: look bad or unrealistic) with the original baked lighting configuration.

2. HDRP lighting - A default HDRP scene offers a step toward more realistic environments with a much larger array of lighting settings (soft shadows, multiple dynamic lights, etc.), better support for complex lighting configurations with large numbers of lights, and a host of real time effects like camera exposure and screen space ambient occlusion. A warning though: real time screen space effects may make your scene "look better", but the way these effects are calculated is not based on how light works in the real world, so realism may vary. Another huge advantage of HDRP is the potential to have moderately realistic lighting without baking your lighting configuration (thought you can bake if you want to). However, there is no real time global illumination option in default HDRP, meaning that your scene will not simulate complex real world light behavior such as light bouncing, light bleeding, or realistic shadows. This can result in unrealistically dark scenes when only using directional lights and windows (without extra interior lights to brighten things up). HDRP offers a good compromise between performance and realism for some use cases.

3. HDRP DXR (DirectX Raytracing) - Unity offers some preview ray tracing features in its latest editor versions that can be used to drastically improve the realism of your scene... for a cost. Here are the pros and cons of DXR:

Pros:
- Can simulate more realistic light behaviors (light bouncing, light color bleeding, and realistic shadows)
- No light baking required

Cons:
- Requires special hardware to run (Nvidia RTX graphics cards required)
- Very time consuming to render. Some lighting options (Global Illumination) are less expensive then others (Path tracing).
- Much more complicated to configure
- These features are still in preview and subject to change

Heres an interesting image comparison of the different lighting configurations:

1. Default HDRP with two lights (one directional light and one dim ceiling point light)
![DefaultIllumination](https://user-images.githubusercontent.com/53197518/111531052-479bde80-8721-11eb-8a94-563e34ad79ef.PNG)
2. HDRP + Global Illumination (GI)
![GlobalIlluminationColor](https://user-images.githubusercontent.com/53197518/111531178-6ac68e00-8721-11eb-8063-ae2ab0eef647.PNG)
3. HDRP + Path Tracing (128 samples) (notice the red light bleeding)
![PathTracingColor](https://user-images.githubusercontent.com/53197518/111531247-7d40c780-8721-11eb-8afc-e453e78dfa25.PNG)
4. HDRP + Path Tracing (4096 samples) (more samples = less ray tracing noise = longer time to render)
![PathTracingColor_4096](https://user-images.githubusercontent.com/53197518/111531269-87fb5c80-8721-11eb-8a79-753623034fd0.PNG)

Feel free to ping me if you need any additional clarification on the above information. Also, you may want to consider contacting us directly at [computer-vision@unity3d.com](computer-vision@unity3d.com).

**Comment by lessw2020** [comment]
Hi @sleal-unity!
Thanks a bunch for all the info above and for generating the comparison images.  For our use case, we'd definitely like to go with max realism.  The path tracing mimics a lot the effects we see in our real shadowed images, so nice to see the image.  
I am happy to note that the HDRP shadows, have already been very helpful to train the classifiers to ignore real shadow, so synthetic is already helping.  Thus, making it as photorealistic as possible is the ultimate goal.
Also I did the basic put up four walls to make a basic room - longer term the idea is to make a series of 'scenario' rooms to generate robust simulations in various settings and thus produce well rounded training sets. 
I'll ping you via the direct line as looking at purchasing new hardware so what to make sure it can use the path tracing (ie. ampere gpu architecture). 
Thanks again!

**Comment by sleal-unity** [comment]
@lessw2020, one really important thing I need to confirm is whether the perception package's semantic labeling shaders and such are compatible with HDRP's preview features (GI, path tracing, etc.). But regardless, let's chat more through the computer-vision@unity3d.com email list about what would be involved in taking these next steps toward more realistic environments.

**Comment by lessw2020** [comment]
Sounds good, thanks again @sleal-unity
