### ISSUE TITLE
issues with adding keypoint labels to custom files

### ISSUE THREAD

**Issue by tklinterg** [Unity-Technologies/com.unity.perception#263]
Hi, 

Thanks for a splendid package. I've run through the tutorials and I'm now trying to apply the same concept to custom models. However, I run in to issues with the labels being offset from the models and not overlaid as in the tutorial.

**Comment by mkamalza** [comment]
Hi,

Thank you for trying out the package. To address this issue, we need a bit more information. Can you perhaps post some screenshots of where you have positioned the keypoints and what the visualization output looks like?

**Comment by tklinterg** [comment]
Thanks for the replay.


I got it working after posting  about the issue. It was due to an old
version of the package, when updating to 0.8, the issue was resolved.

BR

**Comment by JonathanHUnity** [comment]
Great!
