### ISSUE TITLE
Is it possible to disable any dataset or logs output, only get labels or segmentations in real time?

### ISSUE THREAD

**Issue by BlueFisher** [Unity-Technologies/com.unity.perception#271]
I don't want any output of captures, metrics or logs. What I need is just the labels or segmentations information in real time. 
So is there a way that I can disable the outputs? and is there way that I can receive the results of label positions and segamentation textures?

**Comment by JonathanHUnity** [comment]
This is not supported at the moment. In PerceptionCamera you will find two events - InstanceSegmentationImageReadback and RenderedObjectInfosCalculated. See [the PerceptionCamera API docs for more.](https://docs.unity3d.com/Packages/com.unity.perception@0.6/api/UnityEngine.Perception.GroundTruth.PerceptionCamera.html#events
) If you subscribe to these events, they will send instance segmentation and bounding box once they are computed without writing any information to disk. 

Also, [SemanticSegmentationLabeler](https://docs.unity3d.com/Packages/com.unity.perception@0.6/api/UnityEngine.Perception.GroundTruth.SemanticSegmentationLabeler.html#events) exposes an event producing the raw semantic segmentation image, but there is no way currently to disable writing out images.

**Comment by BlueFisher** [comment]
@JonathanHUnity Thank you. I'm looking forward to the new feature.

**Comment by sleal-unity** [comment]
Update: It is now possible to stop perception from writing the dataset to disk using the [NoOutputEndpoint](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Runtime/GroundTruth/Consumers/NoOutputEndpoint.cs).

This endpoint can be configured for your scene by navigating to ProjectSettings ->Perception and then clicking the "Change Endpoint Type" button and selecting the "NoOutputEndpoint" option from the dropdown.

![image](https://user-images.githubusercontent.com/53197518/166338146-b450f62c-9967-4952-85b6-1f169cfbb4a9.png)

Was there any remaining feature needed to support your use case @BlueFisher, or was Jon's suggestion sufficient?
