### ISSUE TITLE
Is it possible to generate data through the Unity CLI

### ISSUE THREAD

**Issue by lucasvandijck** [Unity-Technologies/com.unity.perception#275]
I am trying to run a perception system on a remote GPU server through the Unity CLI, but the perception module doesn't output any data. I have tried using xvfb, but it still won't generate any json/jpg. Does anybody know if this is possible or am I doing something wrong?

**Comment by mkamalza** [comment]
Hi Lucas,

In order to assist with this issue we need to know a bit more about the steps to reproduce it. Can you please explain your workflow in more detail?

**Comment by lucasvandijck** [comment]
So the situation is that we have a car driving on a procedurally generated track with objects on it. The car has a 2D labeller (and semantic labeller for future use) and the objects all have a label.
On start a script reads a JSON file and configures a camera prefab with the correct settings and the perception component after which the car starts driving and detecting.

This all works perfectly when you run it in the Unity window, but it's very slow. We have a remote GPU server (linux ubuntu lts 18) which we want to use to generate this data. We found that you can't really seem to run a Unity project without building, so we currently first build the project and then run it.

The problem is however that we can see the log of the run, so we know the scene has started, and when we ctrl+C the perception module also tells us where we can find the files. The folder containing this data is always empty however. We would like to be able to clone a repo containing our project and then (build and) run the Unity project, generating RGB images and 2D labels.

**Comment by JonathanHUnity** [comment]
Could you provide us the player.log for your run? If you would prefer, you can send it to computer-vision@unity3d.com

**Comment by lucasvandijck** [comment]
Where can I find this file? I tried `find . player.log` in both the project and Unity directory and no file returned.

**Comment by mkamalza** [comment]
The logs are located in the .config folder. Have a look here for more information:
https://docs.unity3d.com/Manual/LogFiles.html

You can also define where the log is saved when using the CLI using the -logFile argument:
https://docs.unity3d.com/Manual/CommandLineArguments.html

**Comment by lucasvandijck** [comment]
Thank you, here are the logs

`Mono path[0] = '/home/vopvision/Documents/vop_simulation/Builds/paard_run_26_03_Data/Managed'
Mono config path = '/home/vopvision/Documents/vop_simulation/Builds/paard_run_26_03_Data/MonoBleedingEdge/etc'
Preloaded 'lib_burst_generated.so'
Preloaded 'libjpeg.so'
Preloaded 'libturbojpeg.so'
Display 0 'screen': 640x480 (primary device).
Desktop is 640 x 480 @ 0 Hz
[Vulkan init] extensions: count=15
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
Vulkan detection: 0
No supported renderers found, exiting`

I also find it weird there was no Vulkan detected, the server should contain 3 Vulkan-enabled GPU's.

**Comment by PriyeshWani** [comment]
Hey @lucasvandijck,

What rendering pipeline are you using? So from the logs it seems you are using Vulkan Graphics API. That won't work with XVFB as XVFB is only for opengl applications. For vulkan there is no stable CPU based rendering support.
Please reach out to simulation-help@unity3d.com for more information and further support.

**Comment by lucasvandijck** [comment]
We are using the HDRP

**Comment by JonathanHUnity** [comment]
Closing for now as we took this discussion offline. The CLI reference can be found here: https://docs.unity3d.com/Manual/CommandLineArguments.html

**Comment by umairkhawaja** [comment]
Hi.

I created a developer build from unity for my perception project. When I run it in terminal, it just opens a blank screen and the application is stuck. Is there something I'm missing?
