### ISSUE TITLE
semantic segmentation

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [Unity-Technologies/com.unity.perception#278]
Hello, great work Unity Perception Team. I am working on segmentation and I want to generate the data for it as it was written in the readme file that we have to right-click in the asset folder then go in the perception and then choose the label config file. But unfortunately, I can only see one option there which is **Create Prefab from selected models**. Please tell me what could be wrong. I will be thankful to you.

**Comment by mkamalza** [comment]
Hi,

To create a label config you would need to go to the `Assets -> Create -> Perception` menu. Here is a screenshot from Unity Editor on OSX:

![image](https://user-images.githubusercontent.com/11081204/113010366-a011a980-912d-11eb-9a33-f870a6ead580.png)

**Comment by HasnainKhanNiazi** [comment]
Thanks, it was my bad, I was looking at the wrong menu.
