### ISSUE TITLE
New labels at runtime

### ISSUE THREAD

**Issue by markuzo** [Unity-Technologies/com.unity.perception#288]
Hello! 

I am trying to construct `GameObject`s with a `Labeling` component and add those new labels to an `IdLabelConfig` (attached to the main camera's `Perception`), using `com.unity.perception@0.8.0-preview.3`, and doing it all at runtime.

I am looking through the csharp files for `Labeling`/`LabelManager`, `IdLabelConfig`/`LabelEntryMatchingCatchEntry`, but can't get my head around how it's possible to add new labels. Is this functionality supported? Is there documentation for this?

**Comment by sleal-unity** [comment]
Hi @markuzo!

Unfortunately adding new labels to a LabelConfig at runtime is not supported at the moment. However, as long as every label you intend to use is already in your LabelConfig before beginning your simulation, you can change a GameObject's label at runtime to a different existing label. For example, here's a Randomizer that swaps between two labels on a particular GameObject for each iteration:

```csharp
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Perception.GroundTruth;
using UnityEngine.Perception.Randomization.Randomizers;

namespace RandomizerTests
{
    [Serializable]
    [AddRandomizerMenu("TestRandomizers/Switch Labels Randomizer")]
    public class SwitchLabelsRandomizer : Randomizer
    {
        public GameObject testObject;
        public string label1;
        public string label2;
        
        protected override void OnIterationStart()
        {
            var labeling = testObject.GetComponent<Labeling>();
            labeling.labels = scenario.currentIteration % 2 == 0
                ? new List<string> { label1 }
                : new List<string> { label2 };
            labeling.RefreshLabeling();
        }
    }
}
```

**Comment by markuzo** [comment]
Thanks very much for the response! That's a shame - I'll keep a large list of default labels in the LabelConfig and just store a mapping of default labels to desired labels.

Is there a plan to support more LabelConfig editing at runtime-initialization? Beyond ID, I can imagine the same behavior applying to the Semantic Segmentation.

**Comment by sleal-unity** [comment]
Yep, @markuzo, this functionality is part of a feature that I happen to be working on right now.

Our team has a prototype of dynamic label configuration creation we're looking for formalize in a future release. I don't have an ETA to share at the moment, but hopefully you'll see this feature soon.

**Comment by markuzo** [comment]
Looking forward to it @sleal-unity. Closing this issue for now.
