### ISSUE TITLE
Creating images using random background objects vs a static scene?

### ISSUE THREAD

**Issue by WeiKin007** [Unity-Technologies/com.unity.perception#295]
Hello,

I'm looking into training object detection models using synthetic data so I've been trying out Unity Perception, and have a couple questions on scene setup for objects. Lets say I have a very small subset of objects to identify, which will mostly be in a specific scene, e.g. a predefined room. Would it be better to create images like the sample projects where random objects with random textures are placed in the background, or just playing the object in a static scene with no background objects and randomizing its position and rotation?

**Comment by JonathanHUnity** [comment]
I would suggest trying out both for yourself! There is certainly merit in both ideas, and I believe you will see decent performance with the fully random environment, fine tuned on real data. The beauty of synthetic data is that you can try these experiments fairly quickly.

Here are some more resources to give you ideas:
https://blogs.unity3d.com/2021/04/09/boosting-computer-vision-performance-with-synthetic-data/
https://blogs.unity3d.com/2020/09/17/training-a-performant-object-detection-ml-model-on-synthetic-data-using-unity-computer-vision-tools/?_ga=2.25393789.1535664.1619714973-241705585.1608577589 

By the way, this is a great question for our newly-minted [Computer Vision Forum](https://forum.unity.com/forums/computer-vision.626/). Hope to see you there.
