### ISSUE TITLE
'IdLabelConfig' does not contain a definition for 'GetAnnotationSpecification' and no accessible extension method 'GetAnnotationSpecification' 

### ISSUE THREAD

**Issue by saher-hazen** [Unity-Technologies/com.unity.perception#297]
Perception 0.5

I have written a custom annotator / labeler. My labeler tries to access GetAnnotationSpecification from the IDLabel instance, but fails to do so as its access is set to be internal.

I can make changes to the original class, to change the access modifier, but it is reverted every time I restart unity and a fresh version is pulled. I can't place my script in the same folder for the same reason.

Is there a fix for this? Or should I create a custom class for IDLabelConfig and try to use that?

**Comment by JonathanHUnity** [comment]
Hmm, ok I  understand. As you can see, GetAnnotationSpecification is quite straightforward and simply provides a formatting of the label entries for writing out to Json. My suggestion would be to copy this code into your own class in your project.

By the way, I am very curious to see what kind of labeler you are building. If you'd rather, feel free to reach out to us at computer-vision@unity3d.com

**Comment by saher-hazen** [comment]
Thanks for getting back to me. I ended up with a solution similar to your suggestion; made copies of entrylabelcache and IDlabelconfig classes.

I needed to add more detail to the labels exported for each of the objects, so I was extending the boxdata structure followed in boundingbox labeler, in a custom labeler. My labeler annotates multiple landmarks on an object and their occlusion, which has since been implemented in the form of the keypoint annotator, but wasn't available in the 0.5 version.

**Comment by lstemple** [comment]
I just wanted to add that I encountered the same issue when trying to add my own screen space variant of the BoundingBox3DLabeler. Similar to the current 2D labeler, I require the rotated 3D points to be reported with respect to screen space rather than camera or world space.

**Comment by JonathanHUnity** [comment]
Opened a PR to make this API public 👍🏻
