### ISSUE TITLE
Semantic segmentation model performance is bad on real images

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [Unity-Technologies/com.unity.perception#299]
Hello everyone, I am working on semantic segmentation and I generated the dataset using Unity perception package and model is performing well on Perception package generated data but on real images, model performance isn't good. I am using Unet + Efficientnetb3 for model training. Any help will be appreciated. Thanks

**Comment by JonathanHUnity** [comment]
Hi there. It is quite common at first to get great performance on synthetic images but poor performance on real. Improving sim2real performance is a highly iterative process, iterating on both the data generation and model training.

Here are some good resources on how we and our users have approached improving sim2real performance in their projects. 
https://blogs.unity3d.com/2020/09/17/training-a-performant-object-detection-ml-model-on-synthetic-data-using-unity-computer-vision-tools/?_ga=2.25393789.1535664.1619714973-241705585.1608577589
https://blogs.unity3d.com/2021/04/09/boosting-computer-vision-performance-with-synthetic-data/

Hope this helps!

By the way, this is a great topic for our newly-minted [Computer Vision Forum](https://forum.unity.com/forums/computer-vision.626/). It should be a more inviting format for open conversation. Hope to see you there.
