### ISSUE TITLE
about skeleton based action recognition

### ISSUE THREAD

**Issue by litchiar** [Unity-Technologies/com.unity.perception#300]
this project is really awesome
I have used Unity for about four years since my undergraduate degree，now  I am studying skeleton based action recognition at the graduate level，i think i can use this project to build a new dataset for my study

**Comment by JonathanHUnity** [comment]
Great! Let us know if you hit issues with the tools. For more general questions about model performance and building your dataset, check out the [Computer Vision Forum](https://forum.unity.com/forums/computer-vision.626/). Good luck!
