### ISSUE TITLE
Multiple Perception Cameras

### ISSUE THREAD

**Issue by TalalWasim** [Unity-Technologies/com.unity.perception#301]
Hello,

I wanted to ask if the package currently supports multiple cameras simultaneously, or is there a known way to implement that? For my task I need to have multiple cameras capturing the same scene from different perspectives.

Talal

**Comment by JonathanHUnity** [comment]
There is no official support for this yet. Some features like RGB capture and 2d bounding boxes may work when multiple cameras are present, but you will run into issues with other labelers. Support for this is being tracked here, and I'd encourage you to provide some more details there on what you're looking to do: https://github.com/Unity-Technologies/com.unity.perception/issues/54

Thanks!
