### ISSUE TITLE
Change to resolution doesn't update the annotations

### ISSUE THREAD

**Issue by markuzo** [Unity-Technologies/com.unity.perception#302]
Hi!

I'm trying to set the resolution of the output at runtime. To do this, I have a C# script that in the `Awake`/`Start` (same behavior regardless), uses `Screen.SetResolution()` to set the resolution to a custom value. The effect that this has is that only the 2nd image of the captured RGB images is updated.

The problem is in the annotations (`BoundingBox2DLabeler`), as all annotations are with respect to the resolution before you changed it. Example, if you start with 600x600 (the first image and its annotations are at the resolution), then set the resolution to 1280x720, all of the annotations will be with respect to 600x600 (however, the image is correct at 1280x720).

The workaround is to use the first resolution as a reference, but it's a little bit of a pain, as you can imagine. 

In general, all of my `Update()` calls only apply on the 2nd of image of a capture. I am using a `PerceptionCamera` with scheduled capture mode and starting at frame 0. Also, I am using the `FixedLengthScenario`.

**Comment by JonathanHUnity** [comment]
Hi. Do you want to change the resolution from frame to frame during dataset generation or just set it once at the beginning of the simulation? If frame to frame, this is not supported today without destroying and recreating the PerceptionCamera. If at the beginning of the simulation, it is possible so long as your code for updating the resolution runs before the PerceptionCamera's Start() (which occurs in the Update step of the player loop)

**Comment by markuzo** [comment]
Just once, at the beginning. 

In the script (which is attached to a GameObject of the scene, not a GameObject created during runtime), I try setting the resolution of the screen with `Screen.SetResolution` in the `Awake()` call. However, I noticed that the resolution (checked with `Screen.width`) isn't updated until the 2nd `Update()`, which I'm guessing is the reason the PerceptionCamera gets created with the 'wrong' resolution. 

Because it's an issue with `Screen.SetResolution` not affecting the resolution immediately, I can close this issue. But before I do, I am wondering if you have a workaround to set the resolution at the start and have it affect the simulation.

**Comment by abhayraw1** [comment]
Hey, I was wonder about the same thing. I am usning the Unity [SynthDet  ](https://github.com/Unity-Technologies/SynthDet) project. The default resolution of the generated dataset is 1280 x 960. I wanted to change that. Currently I am using a workaround script to manually resize the dataset and the annotations but wanted to know if there exists a cleaner solution.
