### ISSUE TITLE
Object not being labelled by the perception camera (HDRP)

### ISSUE THREAD

**Issue by arjunrao796123** [Unity-Technologies/com.unity.perception#306]
Hi,
I have this script:
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class pick_any_obj : MonoBehaviour
{
    // Start is called before the first frame update
    [SerializeField]
    private GameObject[] prefabs;
    private int randomPrefab;
    GameObject obj = null;
    private int cou = 0;
    // Update is called once per frame


    private void Start()
    {
        randomPrefab = Random.Range(0, prefabs.Length);

        obj = Instantiate(prefabs[randomPrefab], transform.position, transform.rotation);

    }


    public void Update()
    {
        if (obj != null)
        {
            DestroyImmediate(obj);
        }

        randomPrefab = Random.Range(0, prefabs.Length);
        Debug.Log(string.Format("Update {0}",cou));
        cou++;

        obj = Instantiate(prefabs[randomPrefab], transform.position, transform.rotation);

    }



}
```

After setting the prefabs length to 10, every frame instantiates a new object.
In the case of my URP project, with the same script, every object that instantiated each frame was being labelled by the perception camera.

However, in my HDRP project, only objects that are constant are being labelled. 
If I change the update to a fixed update, then the instantiated objects are being labelled every 5 iterations. 
```
public void FixedUpdate()
    {
        if (obj != null)
        {
            DestroyImmediate(obj);
        }

        randomPrefab = Random.Range(0, prefabs.Length);
        Debug.Log(string.Format("Update {0}",cou));
        cou++;

        obj = Instantiate(prefabs[randomPrefab], transform.position, transform.rotation);

    }
```
I want it to be labelled every iteration. Can someone help me out?

**Comment by arjunrao796123** [comment]
I downgraded the perception version from 0.8.0 to 0.7.0 and it worked properly

**Comment by mkamalza** [comment]
We strongly recommend you use the Randomization framework to perform any object instantiation or manipulation. This can be done by creating a custom Randomizer through extending the Randomizer class. This class has lifecycle hooks into the Iteration and the Scenario which make it easy to implement scene modification behaviours in a deterministic manner. These include an OnUpdate() function that you can override to perform tasks that need to happen every frame. 

If you set your Perception Camera to capture every frame, you can be sure that these captures happen at the very end of each frame, after all the  OnUpdate() methods of all Randomizers in your Scenario are performed.

**Comment by arjunrao796123** [comment]
I see. I am relatively new to Unity and while SynthDet was doing everything in a 2Dish manner, I am trying to create a 3D scene and randomize positions according to the 3D boundaries. 
I use randomizations for parameters such as light, color, scale, etc.. but I am using normal scripts for positions in a 3D environment.

**Comment by arjunrao796123** [comment]
I ran the perception in HDRP and everything is black? Any solution for this?

**Comment by mkamalza** [comment]
Could you please elaborate on this issue? Do you mean the RGB images are black? or the semantic segmentation images?

**Comment by arjunrao796123** [comment]
The RGB images are all black. The semantic segmentation is working fine.
This is happening in the HDRP only.

**Comment by sleal-unity** [comment]
Hi @arjunrao796123,

Are you still obtaining black RGB images? Unfortunately there could be a number of scene settings that could be the culprit.

Here are a few steps I would recommend to identify the project change that is causing the issue with your RGB output:
1. Create a new simple perception project to confirm that basic perception functionality similar to that used in the [phase 1 of the perception tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation%7E/Tutorial/Phase1.md) is working without any issues. This is a very important step to ensure that something is not terribly wrong with the freshly installed perception tooling.
2. Add your custom features back to the new simulation 1 by 1 until the RGB images begin to turn black.
3. Ping me on this thread with some screenshots of the last change you made to your project before encountering the black RGB images so we can dive into this issue together and determine why that change is causing your issue. Screenshots are always welcome too!

**Comment by ComeOnAndSam** [comment]
yeah I've encountered the same issue. I remade my project in HDRP and objects weren't being labelled. I created a new scene and copied the scene straight up into a blank one and to my surprise it worked. And then eventually it all stopped being labelled again. Im not sure what HDRP settings I altered, Im not sure I edited anything besides prefabs between it working and it not.

**Comment by arjunrao796123** [comment]
> Hi @arjunrao796123,
> 
> Are you still obtaining black RGB images? Unfortunately there could be a number of scene settings that could be the culprit.
> 
> Here are a few steps I would recommend to identify the project change that is causing the issue with your RGB output:
> 
> 1. Create a new simple perception project to confirm that basic perception functionality similar to that used in the [phase 1 of the perception tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation%7E/Tutorial/Phase1.md) is working without any issues. This is a very important step to ensure that something is not terribly wrong with the freshly installed perception tooling.
> 2. Add your custom features back to the new simulation 1 by 1 until the RGB images begin to turn black.
> 3. Ping me on this thread with some screenshots of the last change you made to your project before encountering the black RGB images so we can dive into this issue together and determine why that change is causing your issue.

I will have to try the method you mentioned. It's possible the scene is the issue. I just used a scene that I got from the unity asset store.

**Comment by arjunrao796123** [comment]
> yeah I've encountered the same issue. I remade my project in HDRP and objects weren't being labelled. I created a new scene and copied the scene straight up into a blank one and to my surprise it worked. And then eventually it all stopped being labelled again. I'm not sure what HDRP settings I altered, I'm not sure I edited anything besides prefabs between it working and it not.
> 
> I didn't commit my project when I hit the point where labeling worked, so then I had to reset it, and I haven't been able to get it working again.

Try downgrading the perception version to 0.7.0.0. That worked for me

**Comment by ComeOnAndSam** [comment]
> 
> 
> > yeah I've encountered the same issue. I remade my project in HDRP and objects weren't being labelled. I created a new scene and copied the scene straight up into a blank one and to my surprise it worked. And then eventually it all stopped being labelled again. I'm not sure what HDRP settings I altered, I'm not sure I edited anything besides prefabs between it working and it not.
> > I didn't commit my project when I hit the point where labeling worked, so then I had to reset it, and I haven't been able to get it working again.
> 
> Try downgrading the perception version to 0.7.0.0. That worked for me

Thanks for the tip, but sadly that breaks a lot of the randomizers I created for my scene.

So stuck at an impasse I guess. I do really want to use HDRP, it seems like the optimal choice for perception, but I guess I have to wait for better compatibility.

**Comment by trustedfive** [comment]
Can any Unity developers help with this?

**Comment by trustedfive** [comment]
@sleal-unity @mkamalza Any ideas for solving this issue?

**Comment by RuiyuZ** [comment]
Hi, we have still been unable to reproduce the issue. If you are willing to share a project with us to diagnose further, send us an email at computer-vision@unity3d.com and we will give you a link to upload your project. Thanks!

**Comment by RomanDmowski** [comment]
@arjunrao796123, @RuiyuZ.  I had similar problems with black RGB images. (The RGB images were all black. The semantic segmentation was working fine. This was happening in the HDRP only). 
To get everything working fine I had to disable one component: Planar Reflection Probe.
After that, I  got proper RGB images.

**Comment by trustedfive** [comment]
Hey guys this is still not working. @sleal-unity @RuiyuZ @mkamalza Seems like a lot of people are having this issue with Perception not working for HDRP.

**Comment by ComeOnAndSam** [comment]
My issue is that RGB images appear but Semantic Segmentations are black, along with nothing being labelled. Hopefully a fix can be found with the project I sent off awhile ago.

**Comment by fYYw** [comment]
+1 on the black RGB images output.
