### ISSUE TITLE
Document perception package that was impacted by the capture issue

### ISSUE THREAD

**Issue by adason** [Unity-Technologies/com.unity.perception#311]
Since the capture package issue was identified and [fixed](https://github.com/Unity-Technologies/com.unity.perception/pull/305), we should add note in README (or some suitable place) that warns users not to use these versions.

**Comment by sleal-unity** [comment]
Made a PR to add this documentation to the changelog:
https://github.com/Unity-Technologies/com.unity.perception/pull/314
