### ISSUE TITLE
How do I create a SynthDet serialized PyTorch model file?

### ISSUE THREAD

**Issue by skynet0807** [Unity-Technologies/com.unity.perception#318]
After completing the Perception Tutorial, in learning Unity SynthDet on TorchServe (https://github.com/Unity-Technologies/perception-synthdet-torchserve/blob/master/docs/getting-started.md) Torch Server configuration and operation It is completed.
But there is no guide on how to create the synthdet_faster_rcnn.pth file.
I would appreciate it if you let me know.

**Comment by Wesley201** [comment]
I think the answer is to take the model generated in the tutorial and rename it to synthdet_faster_rcnn.pth according to this doc.

**Comment by skynet0807** [comment]
@Wesley201 
Thank you for your answer.

Data from the tutorial is available on the next page at https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.Multiple files appear as output in four folders, such as perception/Documentation~/Tutorial/Phase1.md#step-7).
- Logs
- JSON data
- RGB images (raw camera output) (if the Save Camera Output to - Disk check mark is enabled on Perception Camera)
- Semantic segmentation images (if the SemanticSegmentationLabeler is added and active on Perception Camera)

I wonder how to create the synthdet_faster_rcnn.pth file using these files.

**Comment by adason** [comment]
@skynet0807 The model file will be created when you followed the SynthDet [tutorial](https://github.com/Unity-Technologies/SynthDet/tree/master/docs). The serialized pytorch model will be created as part of step 5.

**Comment by skynet0807** [comment]
@adason  Your answer is correct.
Thank you.
