### ISSUE TITLE
Tutorial for Adding a Custom Labeler

### ISSUE THREAD

**Issue by umairkhawaja** [Unity-Technologies/com.unity.perception#320]
Is there any guide on how we can extend the functionality of existing labeler scripts?
For instance, I want to extend the BoundingBox Labeler and add a bounding box within the bounding box based on some GameObjects and also output other information as strings?

**Comment by Wesley201** [comment]
We do have on our roadmap to add documentation for custom labelers or extending labelers, which will be added in future releases of the perception package.

**Comment by umairkhawaja** [comment]
That's great. I already know how to create custom randomizers and have created several by now. Can't find resources to create a custom labeler though. Having trouble navigating the labeler scripts in the perception package as well

**Comment by Wesley201** [comment]
We currently don't have any resources on how to extended the labelers, it can be a difficult process at the moment to accomplish. Feel free to start a thread on the Computer Vision forum on the labelers, at this time I'm not sure what other guidance we can provide.

https://forum.unity.com/forums/computer-vision.626/

**Comment by JonathanHUnity** [comment]
Closing this issue for now. Feel free to open another thread if you have more questions
