### ISSUE TITLE
Tutorial for Custom Scenarios

### ISSUE THREAD

**Issue by anilozfuttu** [Unity-Technologies/com.unity.perception#322]
Is there a documentation about creating custom scenarios other than fixed length scenario?

For example I want to control iterations based on some events in my simulation and need events like OnSimulationStart , OnSimulationEnd.

**Comment by Wesley201** [comment]
Here are the instructions I believe you are looking for, if you need further help please let us know. Also, there is now a computer vision unity forum where you can also post as well.

Forum:
https://forum.unity.com/forums/computer-vision.626/

Instructions:
https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Randomization/Scenarios.md#implementing-custom-scenarios

**Comment by JonathanHUnity** [comment]
Closing for now. Let us know if you need more help!
