### ISSUE TITLE
tagManager.Query is not grabbing tags in their inspector order

### ISSUE THREAD

**Issue by ComeOnAndSam** [Unity-Technologies/com.unity.perception#324]
I have an object in my inspector that holds a bunch of the same kind of randomizer tag component, each component holding different data. When the simulation scenario randomizer grabs them, their execution order is important, so I wanted them to be grabbed from top to bottom. But it's not doing that, it's grabbing the one I want to execute last and executing it first under every circumstance. I can't figure out what's deciding the tagManager.Query order if it's not inspector order.

**Comment by mkamalza** [comment]
Hi,
The RandomizerTag system is mainly intended for finding objects in the Scene and performing logic that is unified between them. The order of tags retrieved matches their order of execution, which is from last to first in the inspector.

As a workaround, perhaps the data part can be abstracted out into separate scriptable objects that are loaded at runtime, or another type of component? This will allow you to have only one tag on the object.

Alternatively, a minimum change workaround would be to retrieve the list of tags from the parent object, using the `GetComponents<MyRandomizerTag>()` method. This should return the tags in the order they are added to the object in the inspector.

**Comment by JonathanHUnity** [comment]
I'll close this issue for now. Feel free to reopen if it continues to be an issue.
