### ISSUE TITLE
Baking Shader not responding

### ISSUE THREAD

**Issue by kaylC4** [Unity-Technologies/com.unity.perception#326]
Importing Perception Package 0.8.0 on unity 2020.2.1f1 on Mac with both linux build support mono and IL2CPP installed, causes the the message 'Baking Shaders not responding' in background task in the editor.As result the material are not properly applied shown.
P.S: I already disabled Asynchronous Shader Compilation

<img width="1440" alt="Schermata 2021-06-01 alle 08 46 17" src="https://user-images.githubusercontent.com/32168144/120279098-56bd1200-c2b6-11eb-92cd-2bfc2923afe6.png">
(url)

**Comment by mkamalza** [comment]
Hi,

I have been trying to replicate this with the Unity version you are using on OSX, in both URP and HDRP, I but have not been able to. 

Is this happening on a new empty project too? Also, could you try a newer Unity version, such as 2020.3.7 and see if it still happens?

It would also help diagnose this issue if you are able to share your Unity project with us.

**Comment by kaylC4** [comment]
Hi,
Thank you for your reply,
I had several issues with unity in general in those days ( I had to
reinstall everything).

I'll try and let you by the end of the day.

Buona giornata
EB

Il giorno mer 9 giu 2021 alle ore 22:34 Mohsen Kamalzadeh <
***@***.***> ha scritto:

**Comment by JonathanHUnity** [comment]
I'm going to close this for now. Feel free to comment again if it continues.
