### ISSUE TITLE
Manager create request called after shutdown

### ISSUE THREAD

**Issue by Ademord** [Unity-Technologies/com.unity.perception#331]
Hello, I keep running into this when I hit play
![image](https://user-images.githubusercontent.com/4501464/121324914-73d68e00-c911-11eb-9f32-fb0a171abe8a.png)

after i open the project the first time, it works fine, but i hit Play (to stop) and Play again and it can never start again

**Comment by Ademord** [comment]
also, i forgot to enable warnings, i get:
![image](https://user-images.githubusercontent.com/4501464/121332197-ea768a00-c917-11eb-8aab-12d6d2bf1efb.png)

**Comment by Ademord** [comment]
when I disable ```Save Camera RGB Output to Disk``` it takes longer to crash, i made a video to show the error behavior.
https://www.dropbox.com/s/q5gt42wldvcgcpf/unity_perception_bug.mp4?dl=0

**Comment by Ademord** [comment]
also for the record, the warnings I see after opening my simple project: 
![image](https://user-images.githubusercontent.com/4501464/121350834-6928f280-c92b-11eb-80e4-557cd7acfb77.png)

**Comment by mkamalza** [comment]
Hi. Thank you for posting. I will look into this and see if I can replicate. Meanwhile, I noticed you are using Unity 2021. Can you please try the same or a similar project on Unity 2020.3 to see if the error persists?

**Comment by Ademord** [comment]
i am sorry if i dont continue this issue, i am reverse engineering other projects (tinyyolov2-barracuda, Detection2AR , etc) and trying to integrate them into my project, so i just discarded the perception module as a possible solution.

when i tried to downgrade to 2020.3 as you suggested i got:
![image](https://user-images.githubusercontent.com/4501464/121544284-e460d600-ca09-11eb-99ff-b1194deeb466.png)
![image](https://user-images.githubusercontent.com/4501464/121545902-348c6800-ca0b-11eb-9f70-a9b135d6eef7.png)

**Comment by JonathanHUnity** [comment]
@Ademord , do you have a version of this project that reproduces the issue that you could send to us? It would be most helpful in tracking down the problem.

If so, you can send the project to computer-vision@unity3d.com or email us there for a secure upload link.

Thank you!

**Comment by korzen** [comment]
I am also running into same problem (2021.1.19f1) HDRP

**Comment by Ademord** [comment]
kind of an unrelated question... I am using yolo and on linux my build is giving me an error I have document on this issue https://forum.unity.com/threads/urgent-shader-loading-problem.1194259/. Anyone has any idea what this could be?

**Comment by JonathanHUnity** [comment]
0.9.0 of the perception package was just released with support for 2021.1. Give it a try and feel free to report back if you hit any issues.

**Comment by JonathanHUnity** [comment]
@Ademord For your compute shader work, I would recommend using the Vulkan graphics API instead of OpenGL, as Vulkan has much better support for compute shaders.

**Comment by j4y33** [comment]
Has anyone solved this issue? Also I think it is related with the fact that even after a labeller has been added to the perception camera, in play mode, it says
![Screenshot 2021-11-28 at 19 24 38](https://user-images.githubusercontent.com/28354613/143780993-435c15cc-3cb3-4ba5-923c-d7878a5034a5.png)
:
