### ISSUE TITLE
Incorrect message for InvalidOperationException when label config not assigned

### ISSUE THREAD

**Issue by lstemple** [Unity-Technologies/com.unity.perception#334]
This one should refer to the 3D bounding box labeler and not the 2D one:  

https://github.com/Unity-Technologies/com.unity.perception/blob/235ce6e2aa89e98bcfda56cc7069f0a82a0dc517/com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs#L122

Thank you for providing a useful package!

**Comment by RuiyuZ** [comment]
Thank you for catching this! We will fix it.
