### ISSUE TITLE
Using Temporal anti-aliasing (TAA) in HDRP Perception

### ISSUE THREAD

**Issue by RomanDmowski** [Unity-Technologies/com.unity.perception#338]
I want to use Temporal Anti-Aliasing in my HDRP Perception project. It seems this algorithm doesn't work well: the images are blurry:
![image](https://user-images.githubusercontent.com/15218457/123601664-3b332180-d7f8-11eb-8af5-d8500d690579.png)

TAA uses frames from a history buffer to smooth edges, so I tried to slow down the frequency of captures, changing the 'Frames Between Captures' parameter. Still, it doesn't work. Is the TAA algorithm in Unity Perception supported? How should I configure the  'Perception Camera' and "Fixed Lenght Scenario' parameters?

**Comment by JonathanHUnity** [comment]
The easiest way to have multiple frames of 'settling' is to set two options:
On the Fixed Length Scenario, set it to 10 frames per iteration
![image](https://user-images.githubusercontent.com/23556416/124152224-32388f00-da48-11eb-8c92-1dfd687cd2c5.png)

On the PerceptionCamera, set it to start capturing at frame 9
![image](https://user-images.githubusercontent.com/23556416/124152246-382e7000-da48-11eb-9385-84959bd33e86.png)
This way you will get one frame per iteration (scene randomization).

This appears to be enough time to let FXAA 'settle', but you may need to tune these numbers for your app..

**Comment by RomanDmowski** [comment]
Hi Jon,
Thanks a lot for your hints - now TAA works fine, the quality of images is much better. Now I can start testing the ray tracing in Unity Perception.
To get TAA working I had to increase the values of parameters: Frames Per Iteration = 60, Start at Frame = 59
