### ISSUE TITLE
Calculating percentage of object that is visible

### ISSUE THREAD

**Issue by NoahMattV** [Unity-Technologies/com.unity.perception#341]
I'm trying to figure out a method to calculate how much of any labeled object is occluded so I can ignore it if it's too hidden. Does anyone have some ideas for this? I know part of the rendered object info is the number of visible pixels, but I need it as a percentage of the object if it weren't occluded at all in a given perspective.

**Comment by mkamalza** [comment]
Hi Noah,

Unfortunately, we currently do not support this task. We do hope to support occlusion labeling in the near future though, so please stay tuned to the repo for updates.

**Comment by frederikvaneecke1997** [comment]
Any progress on this request ? Any ideas on how to do this ?

**Comment by mkamalza** [comment]
Hi, we're actively working on this feature. Please reach out to [shounak.mitra@unity3d.com](mailto:shounak.mitra@unity3d.com) for more information on accessing the functionality.

**Comment by StevenBorkman** [comment]
Hey all! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! With this release we have introduced a new occlusion labeler which will provide the occluded amount (as a percentage) to all labeled objects.

There are a bunch of cool features to check out such as ray tracing, depth, a new output format SOLO, normals, and more! Here is the full list of changes: [Perception 1.0 Changelog](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/CHANGELOG.md)
