### ISSUE TITLE
Bounding Box 2D not appearing on Prefab

### ISSUE THREAD

**Issue by vaibhavbagri** [Unity-Technologies/com.unity.perception#348]
Hi, I am trying to use tha [UMA](https://github.com/umasteeringgroup/UMA) character to create a labelled dataset alongside the Unity Perception package. I added the labelling script to the prefab and added it a label config file as well.
Now, if I place the prefab on the scene, the labelling works and a bounding box appears correctly.

![image](https://user-images.githubusercontent.com/32847060/126378390-62469058-e90d-4417-b7c7-ec0a11c07629.png)

But now, if I add the same prefab to a foreground object placement randomizer, and run it, the object appears but there is no bounding box around it, nor is it added to the captures_000.json. If I add a different prefab to the randomizer, the bounding box works. Sample image as reference:

![Screen Shot 2021-07-20 at 2 46 34 PM](https://user-images.githubusercontent.com/32847060/126378767-3f5d1b91-e366-4eb8-a83b-c579ef6e54e4.png)

I am trying to create a labelled dataset with randomized humanoid characters, and this asset for humanoid characters seems pretty useful if I can get the bounding box to work. Any help or tips would be greatly appreciated.

**Comment by StevenBorkman** [comment]
The good news is that since it works in the non-prefab version of the asset then there is no reason that it should not work for the prefab version. First thing is to verify that the labeling component is set properly on the prefab, and on the object when it is instantiated in the scene. Hopefully it is just something as simple as the label is not on the prefab properly.

**Comment by vaibhavbagri** [comment]
The labelling component seems to be properly set on the prefab 
![image](https://user-images.githubusercontent.com/32847060/126382477-cc8c3040-173f-4f95-b613-bb4004979d20.png)

How would I check the same for the object that is instantiated on the scene when I am using the Foreground object randomizer in a Fixed Length Scenario?

**Comment by StevenBorkman** [comment]
When you are running you can pause the execution and step through the scene using the controls on the top center of the screen.
![image](https://user-images.githubusercontent.com/66975693/126383002-e0ee3502-98d7-4cd9-a6f4-f1e98d495b16.png)

I recommend hitting pause before you hit play for the first time, this will start you in pause mode, You can then step through each frame with the 'forward' button on the far right. Wait until your prefabs have been instantiated. You should be able to then click on any instantiated prefab in the 'Hierarchy' and look at its contents in the 'Inspector'

**Comment by StevenBorkman** [comment]
I am assuming that the label 'person' is in the label config that is attached to the bounding box labeler

**Comment by vaibhavbagri** [comment]
Yes it is.
![image](https://user-images.githubusercontent.com/32847060/126388040-78ce99f2-a663-481b-b9dc-c9f55a3f6a00.png)
![image](https://user-images.githubusercontent.com/32847060/126388085-6cf8c01e-5d9d-4fa5-843f-901841c8c4dd.png)

**Comment by StevenBorkman** [comment]
Does the model have LODs? Just asking because I see it in the labeling config file.

**Comment by vaibhavbagri** [comment]
There are two character models. One has LOD, one doesn't. I tried both, but the bounding box didn't work for either.

**Comment by StevenBorkman** [comment]
Ok. well I am running out of ideas this way. Do you mind if I can have access to your project and see if I can debug on my machine?

**Comment by vaibhavbagri** [comment]
Yeah sure. How do I send the project to you?

**Comment by StevenBorkman** [comment]
Probably the easiest way is to add it to a google drive and send me a link. Or if your code is on github, I could clone your repo and checkout a branch.

**Comment by vaibhavbagri** [comment]
The repo isn't on github, I'll share a link to you via Google Drive

**Comment by vaibhavbagri** [comment]
Here's the link to the project : https://drive.google.com/file/d/12kCgkE7ybV1SIlYqnmTroOVS96P07U2g/view?usp=sharing

Let me know if you need any clarification from my side.

**Comment by vaibhavbagri** [comment]
Hey @StevenBorkman , were you able to replicate/find the issue?

**Comment by StevenBorkman** [comment]
I'm looking into it right now. I am able to replicate the issue, but I'm still looking into why it is happening. Fingers crossed...

**Comment by StevenBorkman** [comment]
I'm looking into it right now. I am able to replicate the issue, but I'm still looking into why it is happening. Fingers crossed...

**Comment by StevenBorkman** [comment]
So that was a little wild. I'm not entirely sure what is going on in the UMA system, but the way that it dynamically generates skinned meshes in Update makes it so that the 'Labeling' component does not get picked up for it (at least when the game object is instantiated from a randomizer).

But the good news is that I think I have a fix for you. I removed the 'Labeling' component from your prefab and injected it procedurally from the UMA slot. I edited the 'CapsuleColliderSlotScript' that injects the capsule collider and the rigid body for the human model to also inject the labeling component, like this:
![image](https://user-images.githubusercontent.com/66975693/126540410-20cadfc7-81d1-45af-971d-0679694944db.png)
			
you will also have to update the 'UMA_Content.asmdef' file with a reference to perception:
![image](https://user-images.githubusercontent.com/66975693/126540323-04d4f5ad-4554-4193-9629-72b9820bffb0.png)

**Comment by StevenBorkman** [comment]
This gets it to work on my machine, so hopefully you will have similar success

**Comment by vaibhavbagri** [comment]
Wow that worked for me as well, thank you so much for all the help, there was no way I could've figured this out on my own!

Just a followup, in this case, since I'm adding the labelling component programmatically, I have no way to assign a different label to a particular UMA right? So say I want to give one character a label 'male', and another 'female', it wouldn't be possible with this approach unless I make a separate capsule collider slot script for each?

**Comment by StevenBorkman** [comment]
No problem. I'm glad to help.

As for your question... I think there is probably a way to pass data through to the script from the editor but you will have to be a lot more familiar with the way that the UMA code works than I am. It looks like the CapsuleCollider script is contained in a CapsuleColliderSlot which is contained in the CapsuleColliderRecipe. I would look into those classes to see if there is a way to pass in different values to different prefabs. That's if you want to do it elegantly.

But, I think copying the script several times with different labels in each one will get the job done for you, and it may not be pretty, but it will probably get you the results that you are looking for. Good luck.
