### ISSUE TITLE
Black segmentation masks

### ISSUE THREAD

**Issue by umairkhawaja** [Unity-Technologies/com.unity.perception#350]
Hi, I have created a label config for segmentation and added the appropriate labels in the labelling components of the objects. I have also added the Segmentation labeler in the main camera, however when I generate data and visualize it using dataset insights I don't see any masks, and the segmentation masks are black images. Any ideas what I'm missing?

**Comment by StevenBorkman** [comment]
Hi, so it sounds like you are doing everything correctly, so it should work. Just to verify:
1) You have a SemanticSegmentationLabelConfig with a label value, like this:
![image](https://user-images.githubusercontent.com/66975693/127509333-6928d84e-bbc5-4d00-ab88-4c6ebfe385d2.png)

2) You have a game object with a 'Labeling' component on it, with the proper label, like this:
![image](https://user-images.githubusercontent.com/66975693/127509569-dd61403a-8d72-463c-a284-bcd78f09a912.png)

3) That you have a 'Perception Camera' component added to your 'MainCamera' with a 'SemanticSegmentationLabeler' added to it, like this:
![image](https://user-images.githubusercontent.com/66975693/127509870-eed9de48-fb43-451c-9960-78781327ea64.png)

4) With my setup like that, I'm getting these results from the internal visualizer:
![image](https://user-images.githubusercontent.com/66975693/127509999-e56c3ea9-7d2e-4924-8b19-79951ea49b15.png)

My scene is in URP with the latest release of perception. Hopefully this helps, but if it doesn't please respond and we can start to look deeper into what might be happening in your scene.

- Steve

**Comment by umairkhawaja** [comment]
Hi, thank you for your response. I have double-checked these steps and I seem to be doing all of them correctly. I still don't see the masks either during the simulation in the game tab or in dataset insights

**Comment by umairkhawaja** [comment]
Okay, I created a new scene, and tried segmentation on some objects and it works. So potentially, some script or my scene setting is causing this?

**Comment by umairkhawaja** [comment]
@StevenBorkman  I think I have figured out the issue. Apparently, the labeler is not working on nested objects. For instance, there's a segmentation label assigned to Object B which is a child of Object A. The mask for Object B is not saved, but if a label is assigned to Object A then its mask is available.

Can this be handled with some changes in settings, or do I need to dive into labeling scripts?

**Comment by StevenBorkman** [comment]
@umairkhawaja I'm trying to setup a simple scene to see if I can re-create your issue. I have 2 cubes, cube A on top with no labeling script, and cube b on bottom, nested under cube A with a labeling script attached to it, and it works. I certainly appreciate that my scene is probably far more simple than yours, so is there anyway that you can give me a little more detail about your setup?
![image](https://user-images.githubusercontent.com/66975693/127712227-345fb993-9322-4458-a183-724639e2d611.png)
![image](https://user-images.githubusercontent.com/66975693/127712254-a6e703cf-561d-40a8-a13c-773c02a1a87a.png)
![image](https://user-images.githubusercontent.com/66975693/127712279-cd609825-0b40-45ca-ac06-a1d74ce6e9fd.png)
![image](https://user-images.githubusercontent.com/66975693/127712309-d91b34f8-5df1-4420-980f-d2fd07490762.png)

**Comment by umairkhawaja** [comment]
Thanks for your detailed response!
I missed out one key constraint though which is probably the cause. So the child resides completely inside the parent. But it's visible in the scene since the material of the parent is transparent. I verified this by moving the child outside the parent and then running the script which shows the segmentation mask. Now, is there any way to dump segmentation masks for such objects?

**Comment by StevenBorkman** [comment]
Transparency in segmentation is something that we don't currently support but are planning on implementing in the near future.

We do have a branch where we did some experimenting with this feature available at https://github.com/Unity-Technologies/com.unity.perception/tree/seg_opacity if you would like to look at it and try it out. On that branch, the object will be transparent in segmentation if the main texture (albedo) alpha channel is 0.

**Comment by umairkhawaja** [comment]
Great, thank you so much for your help!
