### ISSUE TITLE
Question: Initialize new random objects every iteration

### ISSUE THREAD

**Issue by vaibhavbagri** [Unity-Technologies/com.unity.perception#353]
Hi, I am using the foreground object placement randomizer to place a list of prefabs in my scene. I notice that all the objects are initialized at the start of the iteration, and then their position is changed in a random manner.

![image](https://user-images.githubusercontent.com/32847060/127915034-c874e6f0-8690-402a-9712-b15900018746.png)

![image](https://user-images.githubusercontent.com/32847060/127915187-5cfb2e5f-11ad-4e4b-bfa7-bb21f4877bfe.png)

For example, person_2 and person_3 are the same in both frames.

In the test scene, it shows that all the objects have been created
![image](https://user-images.githubusercontent.com/32847060/127915484-6dd05822-eba8-4fe8-8089-b58e13c68b06.png)

I want to re initialize the objects at each iteration, since the objects themselves have some randomized parameters to them. Was wondering if there was any way I could do that?

**Comment by aryan-mann** [comment]
Hey @vaibhavbagri! As you pointed out, the `ForegroundObjectPlacementRandomizer` caches objects so they don't have to be re-instantiated each iteration. We can find a work-around for that! Could you elaborate on how the objects (persons) are randomized when they are initialized/instantiated; is there a separate script attached to the objects (persons)?

**Comment by vaibhavbagri** [comment]
Hi, yes the objects are randomized through a separate script attached to them. I tried writing in the same script as the randomizers, but it wouldn't let me.

What would be the workaround to not re instantiate the object at each iteration?

**Comment by aryan-mann** [comment]
One workaround would be to create a custom copy of the `ForegroundObjectPlacementRandomizer` script (make sure to change both the name of the class and the path in the `AddRandomizerMenu` tooltip attribute above) Inside the new copy, if you look within the `OnIterationStart` method, you can see code for when the object is spawned.
```cs
var instance = m_GameObjectOneWayCache.GetOrInstantiate(prefabs.Sample());
``` 
You can add code just below it to randomize the objects. You had mentioned that you had a separate script attached to each object. In that case, you could call a public method inside that script like this.
```cs 
instance.GetComponent<SomeCustomScript>().SomeCustomMethod();
```

Hope this helps!

**Comment by vaibhavbagri** [comment]
Thank you for the reply.  I also had a couple more questions - in case I do not want the objects to be cached and simply instantiated again every iteration, is there a way to manage that?

Also, I noticed that sometimes, there are a couple of objects which are always spawned in the exact same location even though I use the ForegroundObjectPlacementRandomizer. Is there some way around this bug? I can attach some screenshots or send files if you need some more context on the problem.

**Comment by aryan-mann** [comment]
To instantiate a new GameObject each time, you could replace the line
```cs
var instance = m_GameObjectOneWayCache.GetOrInstantiate(prefabs.Sample());
```
with the following
```cs
var instance = GameObject.Instantiate(prefabs.Sample());
```
However, that would require you to destroy the newly created GameObjects manually before the next iteration. Let me know if that helps.

As for the bug, would appreciate more context and screenshots so we can reproduce it on our end. Which exact location are they objects spawned in?

**Comment by vaibhavbagri** [comment]
Thanks for the help with the script, it was really helpful.

For the bug, I have uploaded a video of a sample iteration run on drive and have also added the prefabs that are doing this to the same folder (Although I don't know if the prefab would be useful to you without the library itself). The objects are always spawing in the exact center of the frame, as seen in the video. Here is the drive [link](https://drive.google.com/drive/folders/1llvP2aciVGoOZH3LvSCFO4WdQ2iubPcE?usp=sharing)

**Comment by vaibhavbagri** [comment]
Hey, I was trying to do what you suggested, I added this line in onIterationStart :
var instance = GameObject.Instantiate(prefabs.Sample());

So this was able to create new objects in each iteration. Now, to delete it, in onIterationEnd, I wrote:
while(m_Container.transform.childCount != 0){
                Destroy(m_Container.transform.GetChild(0).gameObject);
}

This throws an error saying Destroy does not exist in current context (Since the class does not inherit from Mono Behaviour). How am I supposed to destroy the objects that are created in that case?

Apologies if the questions are quite basic, I am fairly new to Unity. Thanks in advance for all your help!

**Comment by aryan-mann** [comment]
Hey @vaibhavbagri, apologies for the delayed response. You can use `GameObject.Destroy` instead. 

Two other things to note that might be helpful. When instantiating, make sure to set `m_Container` as the parent of the transform of the instantiated object. Example: 

```cs
// Inside OnIterationStart
var instance = GameObject.Instantiate(prefabs.Sample(), m_Container.transform, true);
```

Secondly, before destroying, make sure to de-parent the object from `m_Container`. Example:

```cs
// Inside OnIterationEnd
while (m_Container.transform.childCount != 0)
{
    var obj = m_Container.transform.GetChild(0);
    obj.parent = null;
    GameObject.Destroy(obj.gameObject);
}
```

**Comment by aryan-mann** [comment]
Marking this as resolved for now. Feel free to re-open it if you have additional questions!
