### ISSUE TITLE
Step and TimeStamp does not update

### ISSUE THREAD

**Issue by ryrichard** [Unity-Technologies/com.unity.perception#354]
As the title suggest, I followed your tutorial and created my own scenario, but in both cases, neither Step nor TimeStamp ever change. If I am understanding their functions correctly, step is just an id that increases with every capture, and timestamp is just time in miliseconds, so if the simulation deltatime is 0.0166, then in 2 frames it should be about 0.0332 seconds or 33.2 miliseconds. In any case, I don't see any changes and I am wondering if I am missing something in my scene.

**Comment by mkamalza** [comment]
Hi, 
The camera's timing sequences are fully encapsulated within each Iteration of the Scenario. So, the step and timestamp values reset on each Iteration. If you set the Frames per Iteration value of the Scenario to something larger, you will see those values increase.

**Comment by ryrichard** [comment]
I see the changes now. Thank you.

**Comment by ryrichard** [comment]
Sorry to reopen this but I am a bit confused on the way Frames Per Iteration works because increasing it only takes pictures of the same frame. Also, is there a way to make the timestamp and step increase with iteration or some other method of indexing?

**Comment by mkamalza** [comment]
In the provided samples used in the tutorial, the environment is only randomized at the start of each Iteration of the Scenario. If you look at the source code for any of the Randomizers, you'll see things happening in the function `OnIterationStart`. This is why within the duration of one iteration, no matter how many frames you render, there is no change in the state of the environment.

Each of the captures in the captures_xxxx.json files have a sequence ID attached to them. Each sequence maps to one Iteration of the Scenario. You can find additional information about each sequence ID in the metrics_xxxx.json files. This includes the Iteration number of each sequence.
