### ISSUE TITLE
Running in Server mode

### ISSUE THREAD

**Issue by saher-hazen** [Unity-Technologies/com.unity.perception#356]
Hi, I am trying to build the project to run it on a local server. I can get the build to execute if it is not in server mode. But server mode builds produce no images. 

I have referred to [this issue]( https://github.com/Unity-Technologies/com.unity.perception/issues/275 ): but have remained unsuccessful. A typical log file is attached. The generated dataset only has the Dataset and Logs directories, and no RGB folder. There are no captures files in the dataset folder either.

I am not sure if I am messing something else up completely, because I haven't run projects in headless mode before. Any guidance is appreciated.

[log3.txt](https://github.com/Unity-Technologies/com.unity.perception/files/6930671/log3.txt)

Ubuntu 20.04 (mono/ standard .net 2.0 / set labeler visualizations to disabled / )
Unity 2021.1.15f1
Perception 0.8.0.preview 3

**Comment by aryan-mann** [comment]
Hey @saher-hazen 👋 , thanks for using the Perception package. Rendering is currently not supported while running in server/batch mode and thus no images will be generated from a run using batch mode.

We do have an offering to build a custom dataset for you by Unity experts. If you would be interested in this, please reach out to our projects team directly with this [form](https://create.unity.com/cv-contact?_gl=1*mkp630*_gcl_aw*R0NMLjE2MjgwOTUyMzkuQ2p3S0NBanc5YWlJQmhBMUVpd0FKX0dUU3FpbE5jWUpFYXg1LUcwMHpKT2hDSGNFZ2lPQkRXVUtwbG9aUjQ3dEpqcjNkanJoYkpaV05ob0NtX29RQXZEX0J3RQ..*_ga*NDc0NDI3MjcwLjE2MjM2ODYwNTA.*_ga_1S78EFL1W5*MTYyODE4ODgxNC41MC4wLjE2MjgxODg4MTQuNjA.&_ga=2.249587072.722099627.1628188815-474427270.1623686050&_gac=1.93539951.1628095454.CjwKCAjw9aiIBhA1EiwAJ_GTSqilNcYJEax5-G00zJOhCHcEgiOBDWUKploZR47tJjr3djrhbJZWNhoCm_oQAvD_BwE).

**Comment by saher-hazen** [comment]
Thank you for your prompt reply, @aryan-mann ! Can you also please confirm if it is possible to do it with a virtual display? So that my OS is still headless but I run my build using a virtual display, as suggested [here](https://towardsdatascience.com/how-to-run-unity-on-amazon-cloud-or-without-monitor-3c10ce022639) ?

**Comment by JonathanHUnity** [comment]
This may work but is not officially supported. I'll close this issue for now. Let us know if you have any other questions.

**Comment by Rawdreen** [comment]
Hi @JonathanHUnity! 
Are any updates coming on rendering in server mode (-batchmode)?

If not, is it any walkaround solution for it, maybe script alteration?
