### ISSUE TITLE
Metal OSX builds with HDRP output pink image

### ISSUE THREAD

**Issue by demirhere** [Unity-Technologies/com.unity.perception#362]
The same application that produces correct output in Unity Editor outputs pink images when built for Metal/OSX. There are some issues with HDRP CopyTexture (not sure if that is the method of capturing the screen), but currently HDRP is only supported on Metal and not OpenGL Core, making the built applications unusable.

**Comment by mkamalza** [comment]
Thank you for bringing this to our attention. I am not sure exactly why this happens but I am indeed able to reproduce this under OSX with a built player. As this is an issue with the capture package, I have forwarded this to our capture team to track and hopefully fix soon. I will update this thread once a fix is available.

**Comment by JonathanHUnity** [comment]
A new version of the Perception package has been released which should address this issue. Let us know if you hit any more issues.

**Comment by calingc** [comment]
Hi, I have the same issue as @demirhere, rendering on Metal/OSX produces pink images. the version I'm using is `Version 0.9.0-preview.2 - November 02, 2021`. Is there a newer version that solves the issue?

**Comment by calingc** [comment]
I'm terribly sorry, I just realized that for `Version 0.9.0-preview.2 - November 02, 2021` I had to upgrade my unity version. I did that and now I can render just fine through a build. Thanks!
