### ISSUE TITLE
Prefab sub object randomization

### ISSUE THREAD

**Issue by tylercollins590** [Unity-Technologies/com.unity.perception#367]
Is it possible to randomize sub objects within a prefab to account for variations in those objects? An example of this would be having a car mesh in a prefab, and swapping the wheels to different wheels randomly to increase the sample size of the dataset.

**Comment by ChumbaWambalala** [comment]
Yes, you can create your own custom randomizer. Check it out here https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Randomization/Randomizers.md

**Comment by StevenBorkman** [comment]
Hey Tyler, thanks for reaching out. @ChumbaWambalala is correct (and by the way, thanks @ChumbaWambalala for jumping in and helping the community) that you can create custom randomizers to alter the scene. If you haven't yet, I would recommend reading through our [tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Tutorial/TUTORIAL.md) in walks you through creating a custom randomizer and adding it to a scenario.

I'm going to close this issue now, but if this hasn't answered your question, please feel free to re-open it.
