### ISSUE TITLE
Multiple labels per object

### ISSUE THREAD

**Issue by demirhere** [Unity-Technologies/com.unity.perception#372]
We are randomly generating people in a scene with different outfits. Our models use the entire bounding box of the person for training, but need labels of what that person is wearing (e.g. white coat, blue pants). Since we are able to have only one label per object, we could create every possible combination of labels, add it to config, but that is not maintainable or scalable.

I saw the guide for labeling parts of the objects (as in the milk box example), but even all belong to same object, the resulting labels are not connected to one another. 

My question is, how can we have multiple labels per object and know they belong to the same one?

**Comment by aryan-mann** [comment]
Hello @dogan-demir, thanks for using Unity and the Perception package! As the BoundingBox2DLabeler uses one label for `label_name` when generating the data, the optimal route would be to report addition data using a custom annotation. A general example of how custom annotations are registered and used can be found at the following link for future reference: [CustomAnnotationAndMetricReporter.cs](https://github.com/Unity-Technologies/com.unity.perception/blob/master/TestProjects/PerceptionURP/Assets/ExampleScripts/CustomAnnotationAndMetricReporter.cs). 

As a helpful starter, I've prepared the following script that adds an annotation which contains information on the labels found within the children (in the scene hierarchy) of a list of GameObjects. Each annotation value is mapped to the original GameObject through its instance id in the Labeling component.

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Perception.GroundTruth;

namespace DefaultNamespace
{
    struct ChildLabelAnnotationValue
    {
        public uint parent_instance_id;
        public string[] child_labels;
    }

    [RequireComponent(typeof(PerceptionCamera))]
    public class ChildLabelAnnotation : MonoBehaviour
    {
        public GameObject[] targetGameObjects;
        AnnotationDefinition m_BoundingBoxAnnotationDefinition;
        SensorHandle m_CameraSensorHandle;

        void Start()
        {
            m_BoundingBoxAnnotationDefinition = DatasetCapture.RegisterAnnotationDefinition(
                "Child Labels",
                "Labels in a GameObjects children. Each child's labels are appended into one label.",
                id: Guid.Parse("C0B4A22C-0420-4D9F-BAFC-954B8F7B35A7"));

            m_CameraSensorHandle = GetComponent<PerceptionCamera>().SensorHandle;
        }

        void Update()
        {
            var annotationValues = new List<ChildLabelAnnotationValue>();
            foreach (var targetGameObject in targetGameObjects)
            {
                var parentLabel = targetGameObject.GetComponent<Labeling>();
                var labelComponentInChildren = targetGameObject.GetComponentsInChildren<Labeling>();
                var concatenatedLabelsOfChildren = labelComponentInChildren
                    .Select(label => label.labels.Aggregate("",
                        (label1, label2) => $"{label1}{(label1 == "" ? "" : " ")}{label2}"
                    ))
                    .ToArray();

                annotationValues.Add(new ChildLabelAnnotationValue()
                {
                    parent_instance_id = parentLabel.instanceId,
                    child_labels = concatenatedLabelsOfChildren
                });
            }

            if (m_CameraSensorHandle.ShouldCaptureThisFrame)
            {
                m_CameraSensorHandle.ReportAnnotationValues(
                    m_BoundingBoxAnnotationDefinition, annotationValues.ToArray()
                );
            }
        }
    }
}
 ```
To use the script, attach it to the `Main Camera` which contains the `PerceptionCamera` component and add the parent GameObjects to the `targetGameObjects` field. In your scene, you might have the following hierarchy:
```
Person 1 (with one label: Person) [Add this to `targetGameObjects` in the inspector]
  - Shirt 1 (with two labels: [Green, Shirt])
  - Pants 1 (with two labels: [Blue, Pants])
```
which would result in the following data being added to `captures_<x>.json`: 

```json
"annotations": [
   ...
   {
      "id": "a69b9de7-dc69-4063-94ab-82cb477554e3",
      "annotation_definition": "c0b4a22c-0420-4d9f-bafc-954b8f7b35a7",
      "values": [
         {
           "parent_instance_id": 6,
           "child_labels": [
             "Person",
             "Green Shirt",
             "Red Pants"
           ]
         },
   }
   ...
]
```

Let us know if this works for you or if there's anything else we could assist you with!

**Comment by kaylC4** [comment]
Hi aryan-mann,
First of all thank you for your work. Following the example in CustomAnnotationAndMetricReporter.cs, I'm triyng to figure out how put in the bounding box annotation the name of the instance of the prefab identified.

Let me explain.

I allocate the same prefab (person_prefab) randomly using a script. Each instance has a different scale factor and is doing a different action. Both these information are encoded in the instance name.

For example if I allocate 3 persons with scale factor 1, 0.9 and 1.2, I'll have:
- person1_s1_walking
- person2_s0.9_sleeping
- person3_s1.2_running

How can I put the instance name in the bounding box annotation, since the labeller identifies them as person_prefab

        {
          "id": "53eeb745-7cc0-4ebf-92ed-abc7a1f60e1f",
          "annotation_definition": "f9f22e05-443f-4602-a422-ebe4ea9b55cb",
          "values": [
            {
  "label_id": 0,
  "label_name": "person_prefab",
  "instance_id": 5,
  "x": 971.0,
  "y": 232.0,
  "width": 15.0,
  "height": 17.0
},
            {
  "label_id": 0,
  "label_name": "person_prefab",
  "instance_id": 4,
  "x": 1033.0,
  "y": 351.0,
  "width": 24.0,
  "height": 20.0
}


thank you very much

EB

**Comment by demirhere** [comment]
@aryan-mann First of all, thank you for the script. I have two questions.
1. I'm testing this together with a BoundingBox2DLabeler since I need the bbox of the parent object. I created single iteration FixedLengthScenario. However, this results in 2 captures, instead of 1 when I don't use it. 1st capture has the right labels but all parent_instance_ids are the same, and it is not tied to an image filename. 2nd capture is correct. [captures_000.json.zip](https://github.com/Unity-Technologies/com.unity.perception/files/7314725/captures_000.json.zip)
2. How can I make sure the labels (components) that are not visible are not included? The goal with this is to clean up the dataset so that, for example if someone is wearing green tshirt but only the head is visible, then we wouldn't want the model to learn a green tshirt label on that image, because that causes issues.

**Comment by ChumbaWambalala** [comment]
> @aryan-mann First of all, thank you for the script. I have a few questions.
> 
> 1. I'm testing this together with a BoundingBox2DLabeler since I need the bbox of the parent object. I created single iteration FixedLengthScenario. However, this always adds an extra first capture that has no filename and no labels. Subsequent captures are correct. [captures_000.json.zip](https://github.com/Unity-Technologies/com.unity.perception/files/7314725/captures_000.json.zip)
> 2. If my objects are randomly spawned by a randomizer, does this still apply? i.e. Does your Update method always come after objects are spawned and organized?
> 3. How can I make sure only visible sub-object labels are included? MeshRenderer's isVisible doesn't work if shadows are rendered.

I've tried this method, and It doesn't work on spawned objects. Somehow the timing on calculating the annotations and rendering the image doesn't sync. 

Still trying to figure out how

**Comment by JonathanHUnity** [comment]
Randomization happens during Update, so the order of Update of other MonoBehaviours is determined by the Script Execution Order. One good way of resolving this is to convert Aryan's MonoBehaviour into a CameraLabeler (see [this documentation](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/GroundTruthLabeling.md#camera-labeler)) and put your logic in OnBeginRendering.

To filter to only visible objects, you will need to use the [RenderedObjectInfosCalculated](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Runtime/GroundTruth/PerceptionCamera_InstanceSegmentation.cs#L27) event in the PerceptionCamera. Note that this event will get called multiple frames after the frame in which the objects were rendered, so you will need to use AsyncAnnotations to manage the pending results. The [BoundingBox3DLabeler](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs) is a good example of how to do this.

This is a fairly complex task at the moment, and we are always interested in your feedback

**Comment by aryan-mann** [comment]
Closing this for now, let me know if you all have any lingering questions and we can open this one back up!

-- Aryan

**Comment by moonsh** [comment]
@aryan-mann 

https://github.com/Unity-Technologies/com.unity.perception/issues/372#issuecomment-923116731

This code is still available? It seems it's outdated now. Can you provide a new sample again?

**Comment by moonsh** [comment]
@kaylC4  Did you find a way to do that?
