### ISSUE TITLE
ShouldCaptureThisFrame behavior when capturing manually

### ISSUE THREAD

**Issue by kalkun** [Unity-Technologies/com.unity.perception#379]
Hi. It is not clear to me when `ShouldCaptureThisFrame` is true when trigger mode is not scheduled. It seems to me that it depends on the simulation delta times, which are not used when the mode is _manual_, can you help me understand this? 

The context is that i want to adjust the camera on each frame and trigger a capture. I'd also like to add annotations (using `ReportAnnotationValues`) however, the latter is guarded by the `ShouldCaptureThisFrame` is `true` otherwise raising an error.

**Comment by JonathanHUnity** [comment]
In manual mode, ShouldCaptureThisFrame will return true once `PerceptionCamera.RequestCapture()` is called for that frame. Let us know if that helps!

**Comment by JonathanHUnity** [comment]
Great!
