### ISSUE TITLE
Cameras with different output resolution

### ISSUE THREAD

**Issue by robin-moss** [Unity-Technologies/com.unity.perception#382]
Currently, the resolution is set by the game view but when we have multiple different cameras we'd like to support each camera having its own resolution control.

I doesn't look like it's possible based on the current documentation: https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/PerceptionCamera.md#output-resolution

**Comment by robin-moss** [comment]
Thanks, so the way to do this is to modify the resolution of the different displays and use them on the camera.

Probably not an issue (in the short term) but is it possible to have more than 8 displays?

**Comment by JonathanHUnity** [comment]
@robin-moss , the new version has been released with multi-camera support. Feel free to try it out and let us know if you run into any problems.

**Comment by robin-moss** [comment]
Are there any docs on this new feature? The output-resolution docs haven't been updated

**Comment by yumianhuli2** [comment]
> Are there any docs on this new feature? The output-resolution docs haven't been updated

been updated？

**Comment by RuiyuZ** [comment]
@robin-moss @yumianhuli2 The docs have not been updated yet, but to use multiple cameras you can add multiple perception cameras to your scene as you will do for one perception camera and that will work.
