### ISSUE TITLE
Output folder option

### ISSUE THREAD

**Issue by robin-moss** [Unity-Technologies/com.unity.perception#383]
Currently, the output folder for the perception camera is set by a global setting that affects other parts of how Unity stores files.

It would be ideal if we could set a specific folder for the cameras to write to

**Comment by JonathanHUnity** [comment]
@robin-moss , the output folder option can be found on the PerceptionCamera in the newly released 0.9.0 version. Enjoy!

**Comment by lchunleo** [comment]
> PerceptionCamera

Hi can i have updated my perception, but can advise where i can configure the output folder for customizing the output to save the data? thank you
