### ISSUE TITLE
Import LabelConfig at runtime

### ISSUE THREAD

**Issue by bkleck** [Unity-Technologies/com.unity.perception#385]
Hi, I saw that there was an option to add in Labels to the Label Config through importing from a JSON file.

Currently, this is only able to be done in the Unity Editor. May I check if there is any way for me to do this in runtime instead, or could you point me to a specific function that I could over-write?

Thank you in advance!

**Comment by JonathanHUnity** [comment]
I'll close this for now. let us know if you still have issues @bkleck
