### ISSUE TITLE
invisible labels after converting to HDRP

### ISSUE THREAD

**Issue by mshooter** [Unity-Technologies/com.unity.perception#389]
Hi, 

I converted my project to HDRP. 
However now when I run my project, the bounding box labels and etc are not visible shown in the game view. 
And not outputted in the annotation files. 

Could you advise me what to do? 
OS: Windows10 
Unity version: 2020.27f1

**Comment by JonathanHUnity** [comment]
@mshooter thanks for reporting. Did you find a solution to your issue? Let us know if you did not.

**Comment by mshooter** [comment]
Hi @JonathanHUnity, 
It started working when I set up the lights properly (e.g. adding a sky and fog volume). 
However, I don't know if that is a solution.
Thank you!
