### ISSUE TITLE
FPS drop when saving RGB output to disk

### ISSUE THREAD

**Issue by FedericoVasile1** [Unity-Technologies/com.unity.perception#390]
Hi,

I'm facing a problem when using the Perception camera component: when enabling the "Save Camera RGB Output to Disk" there is a drop in performance of about 50 fps.
Moreover, the drop seems to do not come from the [actual saving of the frame to disk](https://github.com/Unity-Technologies/com.unity.perception/blob/ee2addba98eec0938f848916890e834a5eb078b7/com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs#L461), but from the [call itself to the asynchronous function](https://github.com/Unity-Technologies/com.unity.perception/blob/ee2addba98eec0938f848916890e834a5eb078b7/com.unity.perception/Runtime/GroundTruth/PerceptionCamera.cs#L468) 

Is there a way to overcome or alleviate it?

Thank you 😄 .

**Comment by Rawdreen** [comment]
@FedericoVasile1 
I also observed such fps drops, does it affect your output results? (ex: when you replay your seed, does output come with slight visual variation?)

**Comment by JonathanHUnity** [comment]
When RGB capture or other labelers are enabled, two expensive things occur. First, if "Show Labeler Visualizations" is enabled, images are read back from the GPU synchronously each frame, causing a large FPS drop. If you disable visualizations, your FPS will probably double.

Second, images are encoded into PNG format. This is spread across many threads but still causes FPS to drop in simple applications.
![image](https://user-images.githubusercontent.com/23556416/140782177-cd4a6b86-8b82-4686-ab0f-38158257dc8e.png)

**Comment by FedericoVasile1** [comment]
> @FedericoVasile1 I also observed such fps drops, does it affect your output results? (ex: when you replay your seed, does output come with slight visual variation?)

Hi @Rawdreen, sorry for the late reply, I have not encountered this problem.
