### ISSUE TITLE
Data Output Occurence

### ISSUE THREAD

**Issue by bkleck** [Unity-Technologies/com.unity.perception#391]
Hey Unity, thanks so much for the Perception package, managed to successfully use it for my personal synthetic data application.

However, one problem that I faced was that the dataset output only occurs after I stop the editor (I assume it will be similar to closing the app). Is there any way to output the dataset to my persistent path straight after the scene ends, instead of after closing the application?

Thank you!

**Comment by bkleck** [comment]
For more context, i made use of the following code to disable my Scenario after it ends to prevent auto-shutdown of the app.
        public void ScenarioEnd()
        {
            // disable the Scenario once it ends, to prevent auto shutdown of application
            GetComponent<CustomScenario>().enabled = false;

            // go back to main menu
            SceneManager.LoadScene(2);
        }

However, the output files only appear after i press the Play/Stop button in Unity editor.

**Comment by bkleck** [comment]
For more context, i made use of the following code to disable my Scenario after it ends to prevent auto-shutdown of the app.

public void ScenarioEnd()
{
// disable the Scenario once it ends, to prevent auto shutdown of application
GetComponent().enabled = false;

        // go back to main menu
        SceneManager.LoadScene(2);
    }
However, the output files only appear after i press the Play/Stop button in Unity editor.

**Comment by bkleck** [comment]
For more context, i made use of the following code to disable my Scenario after it ends to prevent auto-shutdown of the app.
`
public void ScenarioEnd()
{
// disable the Scenario once it ends, to prevent auto shutdown of application
GetComponent().enabled = false;

    // go back to main menu
    SceneManager.LoadScene(2);
}
`
However, the output images only appear when i press the Play/Stop button in Unity editor.

**Comment by bkleck** [comment]
For more context, i made use of the following code to disable my Scenario after it ends to prevent auto-shutdown of the app.
```
public void ScenarioEnd()
{
// disable the Scenario once it ends, to prevent auto shutdown of application
GetComponent().enabled = false;

// go back to main menu
SceneManager.LoadScene(2);
}
```
However, the output images only appear when i press the Play/Stop button in Unity editor.

**Comment by sleal-unity** [comment]
Hi @bkleck!

You can prevent the scenario from shutting down by deriving a custom scenario your current scenario class (FixedLengthScenario in this example) and overriding the on complete method.

I'd give the code below a whirl. Feel free to ping this issue thread again if you run into any trouble!

```csharp
using System;
using Unity.Simulation;
using UnityEngine;
using UnityEngine.Perception.GroundTruth;
using UnityEngine.Perception.Randomization.Scenarios;

[AddComponentMenu("Test/No Shutdown Scenario")]
public class NoShutdownScenario : FixedLengthScenario
{
    protected override void OnComplete()
    {
        DatasetCapture.ResetSimulation();
        Manager.Instance.Shutdown();
    }
}
```

**Comment by bkleck** [comment]
@sleal-unity 

Hey Steven, thanks alot! The ResetSimulation was exactly what I was looking for.
