### ISSUE TITLE
KeypointDepthCheck.shader - Parse error: syntax error, unexpected TVAL_ID, expecting TOK_SETTEXTURE or '}'

### ISSUE THREAD

**Issue by Rawdreen** [Unity-Technologies/com.unity.perception#392]
After updating `Unity Perception` to a `Version 0.9.0-preview.2`, I started receiving this `Parse error message` in `KeypointDepthCeck.shader` while trying to display `Keypoints` in Runtime (using `KeypointLabeler` in `Camera Labelers`). 

>![image](https://user-images.githubusercontent.com/23343509/141620667-0f913be1-3b4c-47c0-b7af-6d1c79c86bab.png)
> error points to line 30

Unity Perception Version: 0.9.0-preview.2
OS Version: Windows 11 
Unity version: 2020.3.15f2.723.3
HDRP version: 10.5.1

**Comment by Rawdreen** [comment]
**After removing the following block, shader is compiled and works fine:**
```
 PackageRequirements
            {
                "com.unity.render-pipelines.high-definition"
            }
```


It would be great to have some feedback on why this error might happen and how to fix it in the proper way.

_P.S.: I've used to fix it using [Unity Docs on ShaderLab](https://docs.unity.cn/2021.2/Documentation/Manual/SL-PackageRequirements.html)_

**Comment by aryan-mann** [comment]
Hey @Rawdreen,
The PackageRequirements block above is supported in Unity versions 2020.3.16f1 and above. Upgrading the Editor version to 2020.3.16f1 (or later) should fix this issue!

Best,
Aryan

**Comment by Rawdreen** [comment]
Oh, yeah I see it now. Thanx 👍!
