### ISSUE TITLE
Trying to capture identical data without using Update()

### ISSUE THREAD

**Issue by ryrichard** [Unity-Technologies/com.unity.perception#393]
Basically, I have a scene where an object gets launched into the air without the use of Update() or its like. I was wondering if it is possible to run the scenario twice and capture the same exact dataset.

**Comment by Rawdreen** [comment]
Hi @ryrichard!

Have you read the [documentation](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/Randomization/Index.md) about randomization?

If it is not clear how to use it, you can check out tutorials [here](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/Tutorial/TUTORIAL.md).


_P.S.: Basically, the **unity perception package has a scenarios script** that has seed randomization for foreground object position, rotation, textures, etc., THAT ALLOWS YOU TO CAPTURE THE EXACT SCENARIO TWICE OR MORE._

**Comment by ryrichard** [comment]
Thank you for the reply @Rawdreen 

I am not entirely sure how the randomizers would help here. In the scene I only set the objects initial velocity and let Unity physic handle the trajectory of the object. I could try and create a custom randomizer that sets an initial velocity and see what happens.

**Comment by Rawdreen** [comment]
@ryrichard oh, got you!

Unity itself is [non-deterministic](https://www.raywenderlich.com/7728186-creating-a-replay-system-in-unity) like most game engines (meaning that physics simulations are most likely to be different at each rerun of your simulation)

Maybe this [doc](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/DatasetCapture.md#custom-sensors) might help you with your question, and try to test your simulations out by yourself!

**Comment by JonathanHUnity** [comment]
Hi @ryrichard , unfortunately physics in Unity is indeed non-deterministic. If you are highly motivated, you could attempt to get a solution working in the DOTS-based [Unity Physics package](https://docs.unity3d.com/Packages/com.unity.physics@0.0/manual/design.html), which is deterministic, but I would warn you that it may be a lot of work.

**Comment by ryrichard** [comment]
I meant to close this, but was preoccupied. Thank you everyone for your help.
