### ISSUE TITLE
3D keypoint annotation

### ISSUE THREAD

**Issue by mshooter** [Unity-Technologies/com.unity.perception#394]
Hi, 

I was wondering if it was possible to output 3D keypoints annotations? 

Thank you!

**Comment by RuiyuZ** [comment]
Hi @mshooter, the perception package does not support outputting keypoint annotations in 3D axis out of box, but you can custom the output dataset follow this guide: [Custom Annotations and Metrics](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/DatasetCapture.md#custom-annotations-and-metrics)
