### ISSUE TITLE
Joint label UI invisible 

### ISSUE THREAD

**Issue by mshooter** [Unity-Technologies/com.unity.perception#395]
Hi, 

when I want to label the keypoints, the field to fill in doesn't appear. 
This is very annoying as I have to click on the "+" multiple times until I can fill in one of the many fields. 
This happens only if the joint is not a parent. 

Unity version: 2021.2.0f1 
OS: Windows 10 
![Joint label error](https://user-images.githubusercontent.com/23126918/141976912-e291270e-b476-4ee9-b403-909862974914.PNG)

**Comment by RuiyuZ** [comment]
Hi @mshooter, I have not been able to reproduce this issue on my machine. 

One thing I noticed is that you are on Unity version 2021.2.0f1. The perception package officially supports unity version 2020.2.19. Can you try to downgrade the unity version to see if that helps fix the issue? 

If it does not fix it, is it possible for you to send us your project or a slimmed-down repro?  If you'd like, please send us an email at computer-vision@unity3d.com and we will send you a link where you can upload a project. Thanks!

**Comment by mshooter** [comment]
Hi @RuiyuZ, 

thank you for letting me know, however I am using this tool that requires Unity 2021 so unfortunately I can't downgrade Unity. 
The program is quite big, however I could try to replicate a slimmed version of it at some point in 2022. 
The issue is not that urgent at the moment for me. 

Thanks again!

**Comment by JonathanHUnity** [comment]
I have not been able to reproduce this issue on 2021.1.28f1. @mshooter Could you give a detailed set of repro steps starting from a blank scene?

**Comment by JonathanHUnity** [comment]
I'll close this for now, but feel free to re-open if you are still hitting this and can provide more info.
