### ISSUE TITLE
Programmatic interface for camera output configuration

### ISSUE THREAD

**Issue by mandlamoyo-ocado** [Unity-Technologies/com.unity.perception#398]
Hey Unity team, thanks for including an option to set the camera output directory in release 0.9.0.

Currently, it only seems possible to do so using the GUI interface, as shown below:

![Screenshot from 2021-11-16 15-20-14](https://user-images.githubusercontent.com/82148497/143464885-f5b29aec-2fe5-4e82-8d09-f7d450ce65a6.png)

Please could you provide a programmatic interface to update the camera output directory as well?

**Comment by robin-moss** [comment]
Additionally to that it would be great now we have multi-camera support if each camera could have it's own output directory
