### ISSUE TITLE
Error when clicking on Run in Unity Simulation

### ISSUE THREAD

**Issue by XarisGeorgiadis** [Unity-Technologies/com.unity.perception#399]
Hello I started doing the perception package tutorials today and I have run into an error I cannot solve in Phase 3:Cloud. When I click on "Run in Unity Simulation" I get the following error: Exception: GetSysParams failed Forbidden (I will paste the whole error at the end of the message). As a result the "Sys-Param" field is empty and I cannot build and run the project. Can anyone help me with this? I am a total Unity beginner so I apologize if the solution is very simple.

Whole error:
Exception: GetSysParams failed Forbidden
Unity.Simulation.Client.API.GetSysParams (System.String accessToken) (at Library/PackageCache/com.unity.simulation.client@0.0.10-preview.10/Editor/API.cs:113)
UnityEditor.Perception.Randomization.RunInUnitySimulationWindow.CreateRunInUnitySimulationUI () (at Library/PackageCache/com.unity.perception@0.8.0-preview.4/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs:109)
UnityEditor.Perception.Randomization.RunInUnitySimulationWindow.CreateEstablishingConnectionUI (Unity.Simulation.Client.Project+State state) (at Library/PackageCache/com.unity.perception@0.8.0-preview.4/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs:86)
UnityEditor.Perception.Randomization.RunInUnitySimulationWindow.OnEnable () (at Library/PackageCache/com.unity.perception@0.8.0-preview.4/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs:55)
UnityEditor.Perception.Randomization.RunInUnitySimulationWindow:ShowWindow() (at Library/PackageCache/com.unity.perception@0.8.0-preview.4/Editor/Randomization/Editors/RunInUnitySimulationWindow.cs:44)

**Comment by JonathanHUnity** [comment]
Hi Xaris. Unfortunately, we are no longer supporting this feature in the Perception package, and we plan to remove it in the next release. Feel free to skip this part of the tutorial for now.
