### ISSUE TITLE
How to store RotationRandomizer to metrics/annotations?

### ISSUE THREAD

**Issue by matteot11** [Unity-Technologies/com.unity.perception#400]
Hi, thanks for your great work.

I was wandering how to store iteration-specific metrics in the output metric file. Specifically, I am interested in saving the x,y,z rotations from the RotationRandomizer generated at each iterations.
I read instructions for storing custom annotations/metrics [here](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/DatasetCapture.md), however in my case objects are not already in the scene (like light in the example), they are prefabs. 
Is there any simple way to store rotation information at every iteration? 
Thank you very much.

**Comment by aryan-mann** [comment]
Hi @matteot11!
If I understand correctly, the setup you are using is to generate objects from a set of prefabs at each iteration and have the Rotation Randomizer rotate them each iteration too. 

In that case, I would suggest creating a copy of the `RotationRandomizer` (for example `MyCustomRotationRandomizer`) and adding the metrics code within the `OnIterationStart` method.

```cs
protected override void OnIterationStart()
{
	var tags = tagManager.Query<RotationRandomizerTag>();
	foreach (var tag in tags)
    {
    	var sampledRotation = rotation.Sample();
        tag.transform.rotation = Quaternion.Euler(sampledRotation);
        
		// Metrics code that reports the values of "sampledRotation"
	}
}
```

**Comment by matteot11** [comment]
Thanks for the suggestion. But in this case, where should I define the `DatasetCapture.RegisterMetricDefinition()`?

**Comment by aryan-mann** [comment]
The `OnAwake` function should be a good place to register it. You could use that function to also get a reference to the sensor handle of the Perception Camera that will be used to report the metrics. Here is an example: 

```cs
    protected override void OnAwake()
    {
        rotationMetricDefinition = DatasetCapture.RegisterMetricDefinition(
            "Object Rotation",
            "Captures metrics on the rotation of objects.",
            Guid.Parse("c469b30c-83c7-4577-b81d-e7e028edb756")
        );
        m_SensorHandle = Object.FindObjectOfType<PerceptionCamera>().SensorHandle;
    }
```

In the `OnIterationStart` method, you could then report the values as such:

```cs
....
        if (m_SensorHandle.ShouldCaptureThisFrame)
        {
            m_SensorHandle.ReportMetric(
                rotationMetricDefinition,
                rotationMetricData.ToArray()
            );
        }
```

**Comment by matteot11** [comment]
It perfectly worked, thank you very much!
