### ISSUE TITLE
Unable to use KeyPoint Labeler 

### ISSUE THREAD

**Issue by aryansaurav** [Unity-Technologies/com.unity.perception#402]
I followed the tutorial on Human Pose Estimation. Everything done as instructed but then on playing the scene, the animation of human avatar works but without any bone lines (keypoint labels). Further, there is an error in the runtime:

ArgumentNullException: Value cannot be Null
Parameter name: shader
UnityEngine.Material..ctor (UnityEngine.Shader shader) (at <cfc1ad890650411e946cff2e6f276711>:0)
UnityEngine.Perception.GroundTruth.KeypointLabeler.Setup () (at Library/PackageCache/com.unity.perception@0.9.0-preview.2/Runtime/GroundTruth/Labelers/KeypointLabeler.cs:150)
UnityEngine.Perception.GroundTruth.CameraLabeler.Init (UnityEngine.Perception.GroundTruth.PerceptionCamera camera) (at Library/PackageCache/com.unity.perception@0.9.0-preview.2/Runtime/GroundTruth/Labelers/CameraLabeler.cs:122)
UnityEngine.Perception.GroundTruth.PerceptionCamera.LateUpdate () (at Library/PackageCache/com.unity.perception@0.9.0-preview.2/Runtime/GroundTruth/PerceptionCamera.cs:239)

**Unity Version:  2020.3.14f1**

**Comment by aryan-mann** [comment]
Hey @aryansaurav 👋 !
The minimum supported Unity editor version for Perception 0.9.0.preview-2 is Unity 2020.3.19f1.
Upgrading your project to 2020.3.19f1 (or greater) should resolve this issue.

Let me know if this issue still persists after upgrading!

Best,
Aryan

**Comment by aryansaurav** [comment]
Thanks. I was considering downgrading to the version written in the manual. Could you please recommend me the latest version supported, possibly an LTS one?

**Comment by aryan-mann** [comment]
Any LTS release equal or greater than 2020.3.16f1 should work. You could upgrade to the latest LTS release for version 2020.3 which would be `2020.3.24f1`.
