### ISSUE TITLE
Keypoints not showing in generated Dataset

### ISSUE THREAD

**Issue by K3NYCZ** [Unity-Technologies/com.unity.perception#405]
I created simple scene with human body and shoes. I'd like to annotate the position of specific points on the foot while wearing shoes but they doesn't show up in generated dataset. I have created Keypoint Template for points I want to annotate, gave them Joint labels and assigned them in perception camera where they should be. There's propably something I did wrong but I can't figure it out :confused:. Should I use CocoKeypointTemplate for this? In annotation_definitions.json file are all keypoints but in captures_00x.json not, so they propably just not getting captured.

Note: Whole Project is done in HDRP but I did same thing in URP and there was same issue.

![info2](https://user-images.githubusercontent.com/94965597/145584825-b54dfea5-0ebe-498b-966d-8a51f9b805a6.png)
![info6](https://user-images.githubusercontent.com/94965597/145584829-f5629181-d77b-4040-bff6-3056ba1b26e3.png)
![info5](https://user-images.githubusercontent.com/94965597/145584831-88c8e197-db36-4a90-a0fb-c8c9ff708b9e.png)
![info4](https://user-images.githubusercontent.com/94965597/145584833-81de8878-096f-4c3d-9b2c-89f72836e555.png)
![info3](https://user-images.githubusercontent.com/94965597/145584835-0b1cc65b-3061-4375-ab8d-53bca7e57677.png)
![info1](https://user-images.githubusercontent.com/94965597/145584840-f114ecfa-f825-4093-837f-c43207737fa4.png)

**Comment by JonathanHUnity** [comment]
The object's Labeling component needs to include a label which is present in the IdLabelConfig on the KeypointLabeler. Try changing the label on the shoe and in the IdLabelConfig to "shoe" and see if that fixes it.

**Comment by K3NYCZ** [comment]
Shoe_L have Labeling set to "Use asset name" and 2 Empty objects (Keypoints I want to track) under shoe have joint label. In the IdLabelConfig for KeypointLabeler are Labels of Shoe_L and it's child Empty objects. Keypoint Template also have all Labels.
Captures.json doesn't show any keypoint annotations at all.

**Comment by K3NYCZ** [comment]
Solved: There was mistake in Joint Labeling
