### ISSUE TITLE
How to get output folder names?

### ISSUE THREAD

**Issue by esgnn** [Unity-Technologies/com.unity.perception#406]
Is there a way to access Guids that are assigned as output folder names for RGB, Segmentation etc.?

**Comment by JonathanHUnity** [comment]
Hi @esgnn , the only way to get links to these folders directly is to inspect the annotations in the captures_XXX.json files once the dataset is fully generated. Do you need these directories at runtime?

**Comment by esgnn** [comment]
Hi @JonathanHUnity,

Yes. Basically, I need to write folder paths to a log file. Scene has multiple cameras and i need to know which subfolders they output images. 
Thank you.

**Comment by JonathanHUnity** [comment]
The captures_XXX.json files do contain this information. Sadly there is no way to get at these at runtime right now. There is an internal field on PerceptioniCamera called `rgbDirectory` that can help you, and similar fields on the SemanticSegmentationLabeler and other labelers. We are working on a new dataset format that will make these directories deterministic. In the meantime, you are free to use the GitHub repo to make changes to the perception package to make these fields public or use reflection to access the data.

**Comment by esgnn** [comment]
Ahh, thank you. 
When will the new package be available? And are you going to make hierarchy or output content changes in jsons? (If you prefer, I can ask in a new issue)

**Comment by JonathanHUnity** [comment]
Yes, it will be substantially different in structure and form. Look forward to more on it in the coming weeks!

**Comment by esgnn** [comment]
Thank you. Have a great year!
