### ISSUE TITLE
About json generation

### ISSUE THREAD

**Issue by yumianhuli2** [Unity-Technologies/com.unity.perception#409]
Hello，Perception Team！
I saw that the JSON was generated below : 
    
foreach (var pendingCapture in pendingCaptures)
                    capturesJArray.Add(JObjectFromPendingCapture(pendingCapture));

                var capturesJObject = new JObject();
                capturesJObject.Add("version", DatasetCapture.SchemaVersion);
                capturesJObject.Add("captures", capturesJArray);

                simulationState.WriteJObjectToFile(capturesJObject,
                    $"captures_{captureFileIndex:000}.json");

but I looked at the structure of PendingCapture class , and there was a mismatch between the json fields. Could you please tell me how to match them?

class PendingCapture
        {
            public Guid Id;
            public SensorHandle SensorHandle;
            public SensorData SensorData;
            public string Path;
            public SensorSpatialData SensorSpatialData;
            public int FrameCount;
            public int Step;
            public float Timestamp;
            public Guid SequenceId;
            public (string, object)[] AdditionalSensorValues;
            public List<(Annotation, AnnotationData)> Annotations = new List<(Annotation, AnnotationData)>();
            public bool CaptureReported;

            public PendingCapture(Guid id, SensorHandle sensorHandle, SensorData sensorData, Guid sequenceId, int frameCount, int step, float timestamp)
            {
                SensorHandle = sensorHandle;
                FrameCount = frameCount;
                Step = step;
                SequenceId = sequenceId;
                Timestamp = timestamp;
                Id = id;
                SensorData = sensorData;
            }
        }
### 
**_mismath???_**

      "format": "PNG",
      "annotations": [
        {
          "id": "0303199f-e658-418f-9fc6-39916ef35664",
          "annotation_definition": "f9f22e05-443f-4602-a422-ebe4ea9b55cb",
          "values": [
            {
  "label_id": 4,
  "label_name": "woman",
  "instance_id": 1,
  "x": 1159.0,
  "y": 52.0,
  "width": 59.0,
  "height": 153.0

**Comment by JonathanHUnity** [comment]
It looks like you are asking about the internal behavior of the perception package - is that right?

I believe you will find the answer in the method JObjectFromPendingCapture, which defines how a PendingCapture is translated to JSON.

**Comment by yumianhuli2** [comment]
> It looks like you are asking about the internal behavior of the perception package - is that right?
> 
> I believe you will find the answer in the method JObjectFromPendingCapture, which defines how a PendingCapture is translated to JSON.

OK,Thank U! I will try.
