### ISSUE TITLE
Random Background Image

### ISSUE THREAD

**Issue by andrearosasco** [Unity-Technologies/com.unity.perception#410]
Hello, 
I have a bunch of jpg images and I'd need to randomly load them as the background of the generated scene. How can I do that?

**Comment by esgnn** [comment]
Hi,
I am not sure whether Perception package has any function to do that, haven't checked. 
Another way is,
You can create a path array of textures and, in whichever random way, sample a texture and load it [1]. Also, create a simple plane (I have better results with Unlit shader on the plane) in the scene and orient it facing camera behind object spawn zone.  Access its material [2], and set its texture to the texture you loaded [3,4].

1. https://docs.unity3d.com/ScriptReference/Resources.LoadAll.html
2. https://docs.unity3d.com/ScriptReference/Material.SetTexture.html
3. https://imgur.com/a/UqOgBmu
4. https://imgur.com/a/bSHA1ds

**Comment by andrearosasco** [comment]
Sorry, I see your reply just now. In the end, I ended up using a properly shaped cube as a "screen" randomizing its texture with the provided texture randomizer.

Thank you for your help.
