### ISSUE TITLE
How to make a Scale Randomizer

### ISSUE THREAD

**Issue by andrearosasco** [Unity-Technologies/com.unity.perception#411]
Hello again,
I'm trying to randomize the size of a game object using the following script

```
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Perception.Randomization.Parameters;
using UnityEngine.Perception.Randomization.Randomizers;
using UnityEngine.Perception.Randomization.Randomizers.SampleRandomizers.Tags;

[Serializable]
[AddRandomizerMenu("Perception/Scale Randomizer")]
public class ScaleRandomizer : Randomizer
{
    public FloatParameter scaleVariationParameter;

    protected override void OnIterationStart()
    {
        var tags = tagManager.Query<ScaleRandomizerTag>();

        foreach (var tag in tags)
        {
            var addScale = tag.transform.localScale * scaleVariationParameter.Sample();
            tag.transform.localScale += addScale;
        }
    }
}
```
but if I run it on an object in the scene, its size keeps increasing on and on until it fills the whole scene.

I tried applying this randomizer to an object loaded by `ForegroundObjectPlacementRandomizer` hoping that at each new iteration, reloading the object would have reset it to its original size. It didn't work.

The last thing I tried was to do it manually via the following code
```
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Perception.Randomization.Parameters;
using UnityEngine.Perception.Randomization.Randomizers;
using UnityEngine.Perception.Randomization.Randomizers.SampleRandomizers.Tags;

[Serializable]
[AddRandomizerMenu("Perception/Scale Randomizer")]
public class ScaleRandomizer : Randomizer
{
    public FloatParameter scaleVariationParameter;
    Dictionary<object, Vector3> originalSize = new Dictionary<object, Vector3>();

    public ScaleRandomizer()
    {
        var tags = tagManager.Query<ScaleRandomizerTag>();
        foreach (var tag in tags)
        {
            originalSize.Add(tag, tag.transform.localScale);
        }
    }

    protected override void OnIterationStart()
    {
        var tags = tagManager.Query<ScaleRandomizerTag>();

        foreach (var tag in tags)
        {
            var addScale = tag.transform.localScale * scaleVariationParameter.Sample();
            tag.transform.localScale += addScale;
        }
    }

    protected override void OnIterationEnd()
    {
        var tags = tagManager.Query<ScaleRandomizerTag>();
        foreach (var tag in tags)
        {
            tag.transform.localScale = originalSize[tag];
        }
    }
}
```
but even this attempt fell flat.

How can I make it work?

**Comment by esgnn** [comment]
I think you are adding reference of localscale to the dict and as you increase it at OnIterationStart you are increasing both originalSize dict and runtime size.
To test it could you please replace ScaleRandomizer with, 
````
public ScaleRandomizer()
{
	var tags = tagManager.Query<ScaleRandomizerTag>();
	Vector3 temp;
	foreach (var tag in tags)
	{
		temp = new Vector3(tag.transform.localScale.x,tag.transform.localScale.y,tag.transform.localScale.z);
		originalSize.Add(tag, temp);
	}
}
````

**Comment by andrearosasco** [comment]
I've tried that but the problem persists 😢

**Comment by esgnn** [comment]
Hmm, have you tried assigning fixed numbers?
`originalSize.Add(tag,new Vector3(1f,1f,1f);`

**Comment by andrearosasco** [comment]
Nope, it didn't work like that either but I found two errors. I had to add the keys to the dictionary inside of `iterationStart` since the constructor is just called once before the objects are loaded and I had to remove them from the dictionary inside of `iterationEnd` otherwise it throws a `key already in the dictionary` exception that messes up everything.

So the code now looks like this:
```
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Perception.Randomization.Parameters;
using UnityEngine.Perception.Randomization.Randomizers;
using UnityEngine.Perception.Randomization.Randomizers.SampleRandomizers.Tags;

[Serializable]
[AddRandomizerMenu("Perception/Scale Randomizer")]
public class ScaleRandomizer : Randomizer
{
    public FloatParameter scaleVariationParameter;
    Dictionary<object, Vector3> originalSize = new Dictionary<object, Vector3>();

    protected override void OnIterationStart()
    {
        var tags = tagManager.Query<ScaleRandomizerTag>();

        foreach (var tag in tags)
        {
            originalSize.Add(tag, tag.transform.localScale);
            var addScale = tag.transform.localScale * scaleVariationParameter.Sample();
            tag.transform.localScale += addScale;
        }
    }

    protected override void OnIterationEnd()
    {
        var tags = tagManager.Query<ScaleRandomizerTag>();
        foreach (var tag in tags)
        {
            tag.transform.localScale = originalSize[tag];
            originalSize.Remove(tag);
        }
    }
}
```
This works on objects that are manually added to the scene but not with objects loaded by `ForegroundObjectPlacementRandomizer`.
The reason seems to be that `ForegroundObjectPlacementRandomizer.OnIterationEnd() ` is called before `ScaleRandomizer.OnIterationEnd()` so there are no tags to iterate at that point.

The only idea I have is to create my version of `ForegroundObjectPlacementRandomizer` and scale back the objects from there.

**Comment by esgnn** [comment]
Why not just use `originalSize[tag] = tag.transform.localScale`?
I may have missed something but I didn't see anything related to scale in [ForegroundObjectPlacementRandomizer](https://github.com/Unity-Technologies/com.unity.perception/blob/ee2addba98eec0938f848916890e834a5eb078b7/com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ForegroundObjectPlacementRandomizer.cs)?

**Comment by andrearosasco** [comment]
Yeah, that's true, it simplifies the code. But I still have to call `tag.transform.localScale = originalSize[tag];` to restore the original size. What I was trying to say is that by itself it works fine but when paired with `ForegroundObjectPlacementRandomizer` (so that the scale of the spawned object is randomized) it doesn't.

> The reason seems to be that `ForegroundObjectPlacementRandomizer.OnIterationEnd()` is called before `ScaleRandomizer.OnIterationEnd()` so there are no tags to iterate at that point.

But I solved it by reimplementing `ForegroundObjectPlacementRandomizer`

**Comment by esgnn** [comment]
Glad you solved it!
If you don't mind, what kind of data are you generating?

**Comment by andrearosasco** [comment]
Thanks!

I'm placing photorealistic scans of boxes in front of a random background (images from Flickr 8k) to train a segmentation model. Right now I'm randomizing light rotation/colour, objects position, rotation, scale and shape, and I'm placing some random shapes in front of them to generate obstruction. I just need to do Hue randomization and I'm done.

I don't expect it to be extremely accurate on real examples but when the class you want to segment is not in any big dataset, I guess you either start manually labelling examples or you use synthetic data.

**Comment by esgnn** [comment]
I hope it turns out well. 
One cheap randomization I see is to randomize object texture to encourage the model to learn object's shape. I haven't benchmarked it myself but based on other papers* that report models are focusing on texture, it seems logical to make texture randomization. Let me know if you do an ablation study based on it. 
If you intend to publish I'd also like to read your paper as well., share here the link 
Good luck!
*: [one example paper](https://openreview.net/pdf?id=Bygh9j09KX)

**Comment by andrearosasco** [comment]
Thanks for the suggestion, I'll try! This is just a step in a robotic grasping pipeline so I don't think I'm gonna publish the segmentation part by itself unless I have some really good idea. I might publish the second step of the pipeline, that is point cloud reconstruction if the results are good enough tho.

Thanks again for your help and good luck with your projects.

**Comment by JonathanHUnity** [comment]
Thanks for reaching out. I'll close this thread for now, but feel free to re-open or open a new issue if you run into more problems.
