### ISSUE TITLE
BBOX with Rotation angle

### ISSUE THREAD

**Issue by ChumbaWambalala** [Unity-Technologies/com.unity.perception#412]
I'm trying to figure out how to do bounding boxes that follows the rotation of an object. The default bounding box one only resizes to fit the object and doesn't follow the orientation.

**Comment by StevenBorkman** [comment]
Hey @ChumbaWambalala, try using the BoundingBox3DLabeler, it will provide the values of all 8 corners of the bounding box in 3D space relative to the camera. If you need to have those coordinates in pixel space, take a look at how we visualize the 3DBoundingBox here: https://github.com/Unity-Technologies/com.unity.perception/blob/4d04ae110501b6bfdf88fa5cde2087ae5248bdde/com.unity.perception/Runtime/GroundTruth/Labelers/BoundingBox3DLabeler.cs#L318

This code demonstrates on how to project 3D camera points into screen coordinates.

Hope this helps.

**Comment by ChumbaWambalala** [comment]
Hi @StevenBorkman, this looks great! I've tried it on my simulation environment and this is exactly what I was looking for. But the problem right now is how do I configure it in such a way that the annotation data will be similar to the visualizers output?

**Comment by JonathanHUnity** [comment]
Glad this is working for you. Feel free to re-open if you have more questions!
