### ISSUE TITLE
About Simulaiton Deltatime

### ISSUE THREAD

**Issue by yumianhuli2** [Unity-Technologies/com.unity.perception#413]
Hello！Dear Unity PerceptionTeam！
1. When I change the SimulaitonDeltatime, the movement rate of objects in the scene is changed. What Settings are changed to achieve this?

2. If the simulation time is customized, why is the timestamp interval of each captured image slightly different?
For example：timestamp(interval 0.1s)：0.1s 0.2s 0.3001s 0.40017s 0.50022s
But I want to stick to control the timestamp(interval 0.1s)：0.1s 0.2s 0.3s 0.4s 0.5s
Then Integrating custom object movements with this precise interval ensures that the output is the same for each simulation time.

Thank you so much！

**Comment by RuiyuZ** [comment]
Hi @yumianhuli2 
1. For the first question, SimulaitonDeltatime is the simulation frame time (seconds) for this camera. E.g. 0.0166 translates to 60 frames per second. This will be used as Unity's [Time.captureDeltaTime](https://docs.unity3d.com/ScriptReference/Time-captureDeltaTime.html), causing a fixed number of frames to be generated for each second of elapsed simulation time. I think the changing movement rate of the object you saw was because the number of frames rendered for each second is changed, so it looks like the movement rate is changed by the eyes

**Comment by RuiyuZ** [comment]
And @yumianhuli2,
2. about the simulation time stamp variation, thanks for pointing it out, we will mark this as a Bug Report. May I ask to what extent would this affect what you are trying to do with your project, so we have a better context here?

**Comment by yumianhuli2** [comment]
> And @yumianhuli2, 2. about the simulation time stamp variation, thanks for pointing it out, we will mark this as a Bug Report. May I ask to what extent would this affect what you are trying to do with your project, so we have a better context here?

Hello! Simulation is concerned with the consistency of the results. If the simulation time is involved in the integration of object motion, the smile change or difference of each time will bring different results of the integration of motion, which may affect the conclusion of each simulation

**Comment by yumianhuli2** [comment]
> Hi @yumianhuli2
> 
> 1. For the first question, SimulaitonDeltatime is the simulation frame time (seconds) for this camera. E.g. 0.0166 translates to 60 frames per second. This will be used as Unity's [Time.captureDeltaTime](https://docs.unity3d.com/ScriptReference/Time-captureDeltaTime.html), causing a fixed number of frames to be generated for each second of elapsed simulation time. I think the changing movement rate of the object you saw was because the number of frames rendered for each second is changed, so it looks like the movement rate is changed by the eyes

Hello！

When simulation Delta time is 0.0166 (default) 60 frames per second,Yes！

When I set the Simulation delta time to 0.1, it should be 10 frames per second. Shouldn't it look like the object is moving more slowly?But, as a result, the object appears to be moving faster by the eyes.

**Comment by JonathanHUnity** [comment]
It's a bit unintuitive, but actually it's opposite @yumianhuli2 . Apps running on Perception do not run in real-time - they generate frames as fast as your machine can run. Therefore, when you increase the delta time, more in-simulation time will elapse each frame, causing the simulation to appear to go faster.

**Comment by ChristianWiele** [comment]
Is there a conceptual difference between the standard Unity fixed delta time, and the capture delta time?

**Comment by JonathanHUnity** [comment]
The "fixed" timestep in Unity is a special concept used for triggering physics and the MonoBahviour's FixedUpdate methods. It is intended to allow physics to be skipped in some frames when the simulation is running at very high framerates. Capture deltatime is used to force the engine to always increment a certain amount of simulation time each frame, effectively disassociating it with the wall clock.

For more on these, see https://docs.unity3d.com/Manual/TimeFrameManagement.html
