### ISSUE TITLE
About 3Dlabeling

### ISSUE THREAD

**Issue by yumianhuli2** [Unity-Technologies/com.unity.perception#414]
Hello！Dear TEAM！
I am using com.unity.perception-0.8.

I found that 3Dlabeling is normal on cars with meshrender, but not working on human bodies with skinnedmeshrenderer.

PS: 2Dlabeling and segmentation ...are normal！

**Comment by JonathanHUnity** [comment]
Thanks yumian. 3d bounding boxes are not currently supported on skinnedmeshrenderers. We will mark this as a feature request and update when it is supported.

**Comment by yumianhuli2** [comment]
OK, I'm looking forward to the latest release！

**Comment by yumianhuli2** [comment]
> Thanks yumian. 3d bounding boxes are not currently supported on skinnedmeshrenderers. We will mark this as a feature request and update when it is supported.

OK, I'm looking forward to the latest release！Thank U!

**Comment by XarisGeorgiadis** [comment]
Hello and sorry me for the intrusion,

I am doing a project where I have to add a BoundingBox3DLabeler for the Player prefab from the "Human Pose Labeling and Randomization" tutorial, but as you mentioned this labeler is not supported on skinnedmeshrenderers. I am fairly new to the perception package so please forgive me if I have not understood something properly.

Is there a way to change the mesh of the Player object in order to have working 3D Bounding Boxes?

**Comment by yumianhuli2** [comment]
> Hello and sorry for the intrusion,
> 
> I am doing a project where I have to add a BoundingBox3DLabeler for the Player prefab from the "Human Pose Labeling and Randomization" tutorial, but as you mentioned this labeler is not supported on skinnedmeshrenderers. I am fairly new to the perception package so please forgive me if I have not understood something properly.
> 
> Is there a way to change the mesh of the Player object in order to have working 3D Bounding Boxes?

3dBBox MeshRender with transparent shader？

**Comment by moonsh** [comment]
@JonathanHUnity  3dBBox is not working for human models?

**Comment by JonathanHUnity** [comment]
@moonsh and @XarisGeorgiadis, thanks for reaching out! Please drop an email to @shounakmitra at [shounak.mitra@unity3d.com](mailto:shounak.mitra@unity3d.com) to chat more about this. He is gathering feature requests and can share more about our roadmap.

**Comment by StevenBorkman** [comment]
Hey all! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! With this release we have added support for 3D bounding boxes for human bodies (skinned mesh renderer) assets.

There are a bunch of cool features to check out such as ray tracing, depth, a new output format SOLO, normals, and more! Here is the full list of changes: [Perception 1.0 Changelog](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/CHANGELOG.md)
