### ISSUE TITLE
I need to start one Randomizer before another but both need to be OnIterationStart

### ISSUE THREAD

**Issue by agru97** [Unity-Technologies/com.unity.perception#415]
I need to start one Randomizer before another but both need to be OnIterationStart. Is there a possibility to do this?

**Comment by aryan-mann** [comment]
Hey @agru97,
The randomizers run in order from the top to bottom as they are shown on the UI of the scenario.
If you need one to run before the other, you can put it higher on the UI!

Best,
Aryan

**Comment by agru97** [comment]
Thanks @aryan-mann
