### ISSUE TITLE
Range controls in Randomizer UI don't render correctly

### ISSUE THREAD

**Issue by ab3nd** [Unity-Technologies/com.unity.perception#416]
The tutorial page at https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation%7E/Tutorial/Phase1.md#step-5 has an image of the HueOffsetRandomizer. I have a project in Unity 2020.3.f1 on Linux (Ubnut 20.04) that is based on the tutorial, but the range controls on randomizers in my project render as two small white lines, rather than a text box. 

![bad_ranges](https://user-images.githubusercontent.com/378014/150592425-e978c9d6-3372-41fe-af52-0df3ac8ea1a3.png)

The problem persists if I remove and re-add the randomizer. I haven't tried deleting and reinstalling com.unity.perception yet.

**Comment by ab3nd** [comment]
Deleting and reinstalling Perception turned them into "M" characters
![still_bad](https://user-images.githubusercontent.com/378014/150595933-7313001e-9814-4a47-a149-dbda54d38888.png)

**Comment by RuiyuZ** [comment]
Hi @ab3nd , I think it was because your unity editor window was too small, so it can't fully display the UI, if you make the inspector window larger it will show up

**Comment by vvernygora-unity3d** [comment]
Hi @ab3nd. please check this video. most likely it will help you. Just adjust U

https://user-images.githubusercontent.com/97534919/150599821-885fc487-f4ef-4623-aa17-3c313704cf59.mp4

**Comment by ab3nd** [comment]
D'oh! Thank you!
