### ISSUE TITLE
About physical camera and camera matrices

### ISSUE THREAD

**Issue by yumianhuli2** [Unity-Technologies/com.unity.perception#419]
Hello!

1. I want to calculate the camera matrix through unity's physical camera.
![image](https://user-images.githubusercontent.com/39210837/151641520-b9272cf7-c303-401b-9c02-520125a280fc.png)（xo,yo is px,py below）
I need to get four parameters: fx, fy, px and py.However, unity physical camera only has focal length param. What I want to confirm is whether the unity physical camera defaults to focal length = fx = fy, px = py = 0?

2. If I need to change fy or px, py, what should I do?

Thanks for unity perception team！

**Comment by mkamalza** [comment]
Hi, 

A code solution for this is provided in this [thread](https://github.com/Unity-Technologies/com.unity.perception/issues/388), which is based on the information [here ](https://ksimek.github.io/2013/08/13/intrinsic/).

To answer your question, the relation between fx and fy will depend on the resolution of the produced image and the sensor size (which the physical camera provides). If the width/height ratio of your camera's output is the same as sensor_width/sensor_height, then fx and fy will be the same.

**Comment by yumianhuli2** [comment]
> Hi,
> 
> A code solution for this is provided in this [thread](https://github.com/Unity-Technologies/com.unity.perception/issues/388), which is based on the information [here ](https://ksimek.github.io/2013/08/13/intrinsic/).
> 
> To answer your question, the relation between fx and fy will depend on the resolution of the produced image and the sensor size (which the physical camera provides). If the width/height ratio of your camera's output resolution is the same as sensor_width/sensor_height, then fx and fy will be the same.

Hello! on the post you mentioned @Rawdreen answered
about Fy
float alpha_v = cam.focalLength * pixel_aspect_ratio * ((float)cam.pixelHeight / cam.sensorSize.y); Is pixel_aspect_ratio in necessary?

**Comment by mkamalza** [comment]
I should preface this by saying I'm not an expert in the area. But the way I understand it is that the single focal length (F) number that we have for the camera needs to be adjusted to give us X a Y focal lengths (Fx and Fy). With a square image, Fx and Fy are the same. For a rectangular image we need to consider the ratio between the two, so we can take Fx = F and Fy = F * (w/h). Alternatively, I think you can do Fy = F and Fx = F * (h/w).

**Comment by yumianhuli2** [comment]
> I should preface this by saying I'm not an expert in the area.
> 
> The way I understand the provided code is that it's trying to convert the single focal length (F) number that we have for the camera to get X and Y focal lengths (Fx and Fy). With a square image, Fx = Fy = F. For a rectangular image, it uses F as Fx and calculates Fy = F * (w/h).
> 
> Notice that this code essentially removes pixel_height from the calculation of Fy and this may have something to do with the Gate Fit property of the camera. Gate Fit is by default set to Horizontal, which means if the image is not square, the horizontal field of view stays the same no matter what aspect ratio is used. The vertical field of view on the other hand changes when pixel_width is changed but not when pixel_height is changed. I suggest playing around with these parameters using the Game view's Free Aspect option.
> 
> Given the uncertainty here, I suggest experimenting with the code and different camera properties and trying to verify the output.

Hello！ I tested for it ,pixel_aspect_ratio is not necessary. Thank you!

**Comment by RuiyuZ** [comment]
Hi @yumianhuli2 Does that answer your questions or do you need further help? If that resolves your questions I will close this issue 😃
