### ISSUE TITLE
Attempting to add folder to Texture Randomizer crashes Unity editor

### ISSUE THREAD

**Issue by ab3nd** [Unity-Technologies/com.unity.perception#420]
I have four folders of background images downloaded via a script from pexels.com. The folders are called sky, city, trees, and desert. Each one has around a thousand 2048x2048 images in it. 

I can add city, trees, and desert to the TextureRandomizer by using the "Add Folder", but attempting to add sky crashes the editor. 

The last line of Editor.log (and Editor-prev.log) is 
(Unity:1362475): Gtk-CRITICAL **: 09:20:00.701: gtk_file_chooser_widget_set_current_name: assertion 'priv->action == GTK_FILE_CHOOSER_ACTION_SAVE || priv->action == GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER' failed

Editor version is 2020.3.22f1

**Comment by mkamalza** [comment]
Hi,

It is difficult for us to tell what may be going wrong without the ability to test on your image files. I recommend trying to feed the images to the Randomizer in batches (e.g. putting them in 5 separate folders) and checking if this method fails on a particular batch. That may help narrow down which image is causing the issue.

**Comment by aryan-mann** [comment]
Hey @ab3nd, closing this issue for now! If you are still experiencing issues, it would be helpful for us if you could provide the following:

- Unity Version (Is it still 2020.3.22f1 as you mentioned?)
- Operating System
- Perception Package Version
