### ISSUE TITLE
Single/Multi-camera runtime semantic segmentation support

### ISSUE THREAD

**Issue by yumianhuli2** [Unity-Technologies/com.unity.perception#422]
Hello unity perception package team！
-- com.unity.perception 0.8 version URP Render
I added the Perception camera component on single/multiple cameras and checked the showLabelerVis option, and I rendered the image to the camera's Output Texture. Using Image transfer to the Python side and opencv imshow images from single/multiple cameras, but only RGB raw images in runtime, which was not the semantic segmentation format I wanted for the python side.So How do I use the unity Perception package to support recorder/presentation of single/multi-camera semantic segmentation in runtime?
![image](https://user-images.githubusercontent.com/39210837/151685949-6c3f5066-a09e-4969-a34a-ca822b15273a.png)

![image](https://user-images.githubusercontent.com/39210837/151655557-3309c14e-4f52-4479-bdae-a1359d6183cd.png)

looks like lots of little Windows
![image](https://user-images.githubusercontent.com/39210837/151686738-0b81c7b6-9569-4ab9-a851-271b79060538.png) in runtime

Thank you！

**Comment by mkamalza** [comment]
Hi,

Apologies but I'm not sure I understand what your final goal is here. Would you kindly clarify? In the meantime, here are some general notes:
- The version of the Perception package you are using does not technically support multiple cameras, try updating to 0.9.0
- The in-editor realtime visualizer does not support multiple cameras

**Comment by yumianhuli2** [comment]
> Hi,
> 
> Apologies but I'm not sure I understand what your final goal is here. Would you kindly clarify? In the meantime, here are some general notes:
> 
> * The version of the Perception package you are using does not technically support multiple cameras, try updating to 0.9.0
> * The in-editor realtime visualizer does not support multiple cameras

Hello！
![image](https://user-images.githubusercontent.com/39210837/152636755-46aa138b-d38d-4cd5-bf74-823e2a2777b6.png)
I didn't see any branch for version 0.9 .

**Comment by yumianhuli2** [comment]
> Hi,
> 
> Apologies but I'm not sure I understand what your final goal is here. Would you kindly clarify? In the meantime, here are some general notes:
> 
> * The version of the Perception package you are using does not technically support multiple cameras, try updating to 0.9.0
> * The in-editor realtime visualizer does not support multiple cameras

Yes,0.9.0 version works!But how could you support multiple camera different resolutions at the same time？Thank you!

**Comment by mkamalza** [comment]
Try rendering both cameras to textures and use textures with different resolutions.

**Comment by yumianhuli2** [comment]
> Try rendering both cameras to textures and use textures with different resolutions.

ok,thank you!

**Comment by yumianhuli2** [comment]
> Hi,
> 
> Apologies but I'm not sure I understand what your final goal is here. Would you kindly clarify? In the meantime, here are some general notes:
> 
> * The version of the Perception package you are using does not technically support multiple cameras, try updating to 0.9.0
> * The in-editor realtime visualizer does not support multiple cameras

Hi!
Using this package for multi-camera semantic segmentation texture output can support exe executable program in runtime?
