### ISSUE TITLE
Adding camera effects to the perception camera

### ISSUE THREAD

**Issue by lchunleo** [Unity-Technologies/com.unity.perception#423]
I wish to check how can i add camera effect to the perception camera? thanks

**Comment by mkamalza** [comment]
Hi, 
Camera effects such as blur, color correction, noise, etc. can be added using a Volume object. You can check out this [page ](https://docs.unity.cn/Packages/com.unity.render-pipelines.universal@11.0/manual/integration-with-post-processing.html) to learn about this feature.
