### ISSUE TITLE
Changing Output Folder's directory and sub-folder/image names

### ISSUE THREAD

**Issue by XarisGeorgiadis** [Unity-Technologies/com.unity.perception#425]
Hello,

Is there a way to specify where my project will save the Perception Camera outputs? The default location is on my SSD but my project may end up being a few TBs so I need to save the output data to my hard drive instead. Moreover, is there a way to specify how each image will be named based on my randomizer parameters instead of them being named "rgb_x"?

As far as I can tell I can change all this by modifying the Perception Camera script, but Unity does not let me make any modifications to that file.

**Comment by yumianhuli2** [comment]
> Hello,
> 
> Is there a way to specify where my project will save the Perception Camera outputs? 
 Support is available in version 0.9
 
> As far as I can tell I can change all this by modifying the Perception Camera script, but Unity does not let me make any modifications to that file.
You could place perception package under the ProjectName/Packages folder

**Comment by XarisGeorgiadis** [comment]
@yumianhuli2 Done. Thank you!
