### ISSUE TITLE
Unity freezes when generating datasets with segmentation enabled and large number of objects/image

### ISSUE THREAD

**Issue by calingc** [Unity-Technologies/com.unity.perception#426]
Hi all, hope you're doing well. We're using unity perception to generate synthetic datasets for retail use cases and we encountered the following issue:

An average image we render has about 1500-2000 objects/image (I'll attach a sample render). Problem is that when we enable segmentations, Unity goes to about 100-150 images after which it freezes. We tested on multiple platforms (osx, linux, windows) and the issue is present on all of them: it renders without any problem, but after 100 or so iterations it completely freezes, and it doesn't even free up the RAM (goes about ~10gb of RAM used)

Not sure which technical details you would need from my side, happy to share as much as I can - The code is closed source though, I'm afraid. We would really like to have segmentations as it has been explicitly requested by our clients.

We're using Unity 2020.3.23f1 with HDRP 10.7.0 and Unity Perception 0.9.0-preview.2.

Cheers!

![12_YoVSpsNm](https://user-images.githubusercontent.com/56309133/153200373-7f6c6663-a719-4f2f-8782-29ca21689e21.jpg)

**Comment by shounakgithub** [comment]
Hi, 

Seems like you're facing some issues wrt scaling your datagen step.
We'll need a little more info from you to be able to suggest steps. Please feel free to connect with me at shounak.mitra@unity3d.com and we'll take it from there.

--
Shounak
