### ISSUE TITLE
Background randomisations not showing 

### ISSUE THREAD

**Issue by VirajVaitha123** [Unity-Technologies/com.unity.perception#427]
Hi there,

First thank you for a great resource to speed up training for computer vision!

I've been following the tutorial, and hit a road block when adding the simulation scenario to randomize the background.

I created an empty gameobject (named simulation scenario). I attached the fixed length scenario, background object placement randomizer.

This has:
depth = 2,
layer count = 2
seperation distance = 0.5
placement area 6, 6

Added folder of prefabs (background objects)

Finally, my game has a FOV of 4:3 aspect and main camera has the following settings:
![image](https://user-images.githubusercontent.com/44236859/153659776-1e241285-f3fb-4e60-9dd6-9887d939c7a7.png)

![image](https://user-images.githubusercontent.com/44236859/153659820-82f534d1-f7f6-4d9e-9d02-1516c46df31d.png)

Please let me know if you spot anything wrong.

Thanks,

Viraj

**Comment by StevenBorkman** [comment]
Hey Viraj,

Thanks for using perception and for reaching out. We just became aware of this issue and are working on a solution for it, and hopefully will have a patch release for it soon. This problem only occurs in the latest versions of Unity Editor (verified this issue in both 2020.3.27.f1 & 2020.3.26.f1).

This error does not exist in 2020.3.20f1, so at this point I would recommend downgrading to that version of the editor.

I hope this helps, and if possible, can you tell us which version of the Unity Editor that you are using, to help us identify when this issue started.

Steve

**Comment by VirajVaitha123** [comment]
Hey Steve,

Thanks for the quick response!

No worries appreciate the update. The documentation for this package in particular is really well written. I am hoping to use this on a project at work around species recognition for salmon, puffins and other animals. Is this something that looks realistic with this package (assuming I would need to create the assets for the animals in blender or something?)

Thanks,

Viraj

**Comment by StevenBorkman** [comment]
Hey Viraj,

Yeah, I think building off something similar to the tutorial with your own custom assets will probably work out really well for you.

**Comment by ChristianWiele** [comment]
Can you tell me, when this is gonna be fixed? I would like to update my tutorial videos on Perception as I see an increasing interest. But it would be unfortunate if I recommend to install 2020.3.20 although 2020.3.29 is already out. It would look like there is no active development going on for Perception.

**Comment by JonathanHUnity** [comment]
@ChristianWiele We intend to put out a release early next week that will address this issue.

**Comment by ChristianWiele** [comment]
Thanks for the heads up. This will be very helpful if I can do the tutorial on the current version.

**Comment by aryan-mann** [comment]
Hey all! This issue should be fixed in the latest release 🎉 
Let us know if you have additional questions but closing this for now!
