### ISSUE TITLE
Test run without any output to disk

### ISSUE THREAD

**Issue by ChristianWiele** [Unity-Technologies/com.unity.perception#428]
Hi,

if I disable "Save Camera RGB Output to Disk" the image segmentation files and the meta data are still written. It would be good to have an option to disable any output for test purposes.

Thanks, Christian

**Comment by aryan-mann** [comment]
Hi @ChristianWiele, noting it down as a feature request! 
Could you elaborate on your use-case for when you would not want any output?

**Comment by ChristianWiele** [comment]
Basically all the time during developing and testing of a scenario. I can see everything on screen, so I don't need the output until the final stage.

**Comment by aryan-mann** [comment]
Hey @ChristianWiele, the latest release has a new "No Output Endpoint" which might be help with this issue 🎉 
You can select it from the Endpoint settings in `Project Settings > Perception`.

Closing this for now but let us know if you have additional questions or feature requests!
