### ISSUE TITLE
Only objects present in scene at load time are used for labeling

### ISSUE THREAD

**Issue by martinlyons** [Unity-Technologies/com.unity.perception#43]
Hi,

This project has a lot of potential but at the moment it doesn't seem to allow scripted instantiation of objects with labeling components to be included in the dataset for segmentation/bounding box calculation. If this is a limitation, it's not documented.

Example - I want to generate up to 3000 instances of an object with a dynamically chosen texture on the fly, label these as such (by modifying the labeling component to reflect the texture name) and then move them around to generate training samples. With the Perception package as-is, none of these objects appear in the segmented pngs, though they are obviously present in the rgb images.

I've tried doing my instantiation and labeling in the Awake function and moving my script to the highest priority in the script execution order. It doesn't make any difference.

I'm at a loss for a workaround here, short of manually instantiating 3000 objects in the editor!

**Comment by JonathanHUnity** [comment]
Hi there. So long as the Labeling component is updated in the same frame it was instantiated, the new labels should be picked up in the semantic segmentation images.

One thing to check is the SemanticSegmentationLabelConfig attached to your SemanticSegmentationLabeler. Does it contain entries for all of the labels you are applying to the objects at runtime? Are there any typos? Mismatches between the Label Config and the Labeling on the objects will result in the objects not being colored in the image.

Here is an example of a quick and dirty object generator with dynamic labels:

```
public class ObjectGenerator : MonoBehaviour
{
    GameObject lastGenerated;
    public GameObject prefab;

    // Update is called once per frame
    void Update()
    {
        var instantiated = Object.Instantiate(prefab);
        var labeling = instantiated.GetComponent<Labeling>();
        labeling.labels.Add("Crate");

        if (lastGenerated != null)
            Destroy(lastGenerated);

        lastGenerated = instantiated;
    }
}
```

**Comment by martinlyons** [comment]
Hi Jonathan

Yes that's exactly what my code looks like (apart from I create a new list in the label component before I add to it - but commenting out that line makes no difference). 

Important to note that as a test I've also put an instance of the prefab in the scene from the editor and that gets segmented sometimes OK, but sometimes partially occluded by the instantiated objects (which are segmented as black). 

I've triple checked that the labels are matching, but even so this wouldn't explain why the dynamically instantiated prefabs, when I remove the adding of the label and let them default to the existing label, do not segment while the statically instantiated prefab does.

I can happily privately share the project with you. It's a simple scene with only one script so it should not be hard for you to test against.

**Comment by JonathanHUnity** [comment]
A repro project would be fasntastic. Could you email it to jonathanh at Unity3d.com?

**Comment by JonathanHUnity** [comment]
We resolved offline. By the way, in the 0.4.0-preview.1 release we added `Labeling.RefreshLabeling()` which can be used to refresh the ground truth generators after changing the labels or renderers on an object.
