### ISSUE TITLE
Question: HDPR/High resolution synthetic data

### ISSUE THREAD

**Issue by VirajVaitha123** [Unity-Technologies/com.unity.perception#433]
Hi,

I was wondering what's the highest quality 3D models you can use for synthetic data generation. I couldn't see a discussions section so I just posted here hope that's okay.

I love the concept of this tool and it can really drive data centric model development. The only concern I have is the gap between real and synthetic data (which I assume will improve in the future).

The grocery store dataset didn't look to realistic in my opinion, and really want to test the models ability to generalise to real data when using synethic data. If you wanted to have more realistic 3D models what would you suggest?

- Any 3D scanners apps you recommend to create 3D models?
- Settings I need to change in Unity?
- Am I already able to use HDRP in Unity, if so what do I need to change?

Many Thanks,
Viraj

**Comment by RuiyuZ** [comment]
Hi @VirajVaitha123,

Thank you for your interest in our package!
Perception and unity do support very high-quality models, and I understand your concern on the gap between real and synthetic data; we have many projects that have testified the improvement on ML model with the assistance of synthetic data. Here are some blog posts and research papers on perception package that provides more information:
[Unity Perception: Generate Synthetic Data for Computer Vision](https://arxiv.org/abs/2107.04259)
[Boosting computer vision performance with synthetic data](https://blog.unity.com/technology/boosting-computer-vision-performance-with-synthetic-data)
[Training a performant object detection ML model on synthetic data using Unity computer vision tools](https://blog.unity.com/technology/training-a-performant-object-detection-ml-model-on-synthetic-data-using-unity-perception)

As for your questions:
1. Yes, please check out the "Scanning" part in this article [Getting started with 3D content for synthetic data](https://blog.unity.com/technology/getting-started-with-3d-content-for-synthetic-data)

> There are a range of technologies for 3D scanning, each suited to different types of objects, quality levels, and budgets. Some notable examples are:
> 
> Photogrammetry: Photogrammetry tools such as [Agisoft Metashape](https://www.agisoft.com/) and Unity’s [AR Companion app](https://blog.unity.com/technology/unity-reveals-latest-ar-companion-app-feature-at-apple-wwdc-21) synthesize a 3D object from a set of photographs taken from different angles. Visit Unity’s [photogrammetry page](https://unity.com/solutions/photogrammetry) for more on this technique.
> Pros: Suitable for objects of any size or shape; captures texture and fine detail
> Cons: Sensitive to lighting conditions and object color; somewhat tedious
> 
> Flatbed scanner and 3D modeling: A flatbed scanner can be used to scan different sides of a box-like object and then combined into textures and mapped onto a hand-authored 3D mesh using standard 3D authoring tools. For more, see a [video tutorial](https://github.com/Unity-Technologies/SynthDet/blob/master/docs/CreatingAssets.md) on this method from our recent [grocery object detection project](https://blog.unity.com/technology/training-a-performant-object-detection-ml-model-on-synthetic-data-using-unity-perception).
> Pros: Inexpensive, highly accurate textures
> Cons: Only suitable for flattenable objects; some hand-authoring required
> 
> Industrial 3D scanner: Specialized devices for 3D scanning using laser or structured light produce high geometric accuracy. This approach is ideal for detecting mechanical parts and complex electronic equipment.
> Pros: Highly accurate geometry on most objects; fast
> Cons: Expensive; object sizes are limited

2. For info about high-quality visualization on unity hdrp, I think this page would be helpful: [How to set up Unity's High Definition Render Pipeline for high-end visualizations](https://blog.unity.com/aec/how-to-set-up-unitys-unitys-high-definition-render-pipeline-for-high-end-visualizations)

3. Perception package does support HDRP out of the box, there is a "PerceptionHDRP" project under _TestProjects/_ that you can open in unity editor directly after you clone the [perception repo](https://github.com/Unity-Technologies/com.unity.perception).
PerceptionHDRP project location: https://github.com/Unity-Technologies/com.unity.perception/tree/main/TestProjects/PerceptionHDRP

**Comment by VirajVaitha123** [comment]
Thank you so much this was very useful! 💯
