### ISSUE TITLE
Question: How to randomize a background image

### ISSUE THREAD

**Issue by cd25643** [Unity-Technologies/com.unity.perception#435]
Very new to both Unity, and the perception package. I followed the entire tutorial, and am now building my own scene with custom randomizers/objects/etc. I was wondering how I would go about randomizing a background image for a scene? What I have in mind, is having a folder of multiple HDRIs and each frame it randomly picks one of those. How would I go about doing something like this?

**Comment by esgnn** [comment]
One approach could be (I'm not sure if it is a performant one)

1. [Read](https://docs.unity3d.com/ScriptReference/Resources.LoadAll.html) HDRI's at the start of the simulation - 
2. Pick one at the start of each frame
3. Assign it to [VolumeProfile](https://docs.unity3d.com/Packages/com.unity.render-pipelines.core@5.1/api/UnityEngine.Rendering.VolumeProfile.html). It is a little bit trickier. An example code is below

```
void ChangeSky(VolumeProfile vp, Cubemap hdri)
{
	HDRISky hs;
	vp.TryGet<HDRISky>(out hs);
	hs.hdriSky.value = hdri;
}
```

**Comment by RuiyuZ** [comment]
@esgnn thank you so much for helping out!
@cd25643 I think you are on the right track, and I will just add a little bit on @esgnn's answer
The steps would be:
1. add a "Volume" component to your sky object
2. on the "Profile" box, create a new Volume profile
3. click into that Volume profile and "add override" -> sky -> HDRI sky
4. check the checkbox "Hdri Sky"
5. on the same sky object, create a SkyRandomizerTag class that reads in the HDRISky that can be getting from the Volume we just created on the same object,
```    
public class SkyboxRandomizerTag: RandomizerTag
{
    HDRISky m_Sky;
    public HDRISky sky
    {
        get
            {
                if (m_Sky == null) 
                    GetComponent<Volume>().profile.TryGet(out m_Sky);
                return m_Sky;
            }
    }
}
```
6. create a randomizer script
```
[Serializable]
[AddRandomizerMenu("Perception/My sky Randomizer")]
public class MySkyRandomizer : Randomizer
{
    public CubemapCategoricalParameter skyboxes = new CubemapCategoricalParameter();
    protected override void OnIterationStart()
    {
        var tags = tagManager.Query<SkyboxRandomizerTag>();
        foreach (var tag in tags)
             tag.sky.hdriSky.Override(skyboxes.Sample());
    }
}
```
7. Add MySkyRandomizer to the list of Randomizers in SimulationScenario.
8. click "add folder" to add the folder of HDRIS

**Comment by cd25643** [comment]
@RuiyuZ Thanks a lot for your detailed response. That is very helpful! However, I can't seem to find the "sky" or "HDRI sky" option in the Volume Profile override box? (see pic below) What am I missing here? I only see "post-processing" and in that sub-menu, there is no sky or HDRI sky option...

![1](https://user-images.githubusercontent.com/100865605/158394465-f7392c91-dbdc-4778-8f29-0119c8ef9c4a.jpg)

**Comment by cd25643** [comment]
@RuiyuZ When I go to create a new gameobject, I do not see the "Sky and Fog Volume" option within the Volume category. I instead tried to create a Global Volume, when adding a component I also don't see the option to add a "Visual Environment" or "HDRI Sky"...

![1](https://user-images.githubusercontent.com/100865605/158617212-0b7930c6-a0e9-4317-982a-ef651e60daba.jpg)
![2](https://user-images.githubusercontent.com/100865605/158617237-2bbc0fe1-74cf-4191-90e1-f95f610054aa.jpg)

**Comment by RuiyuZ** [comment]
Hi @cd25643, you can find it here
![image](https://user-images.githubusercontent.com/37159720/158641909-4edc3210-0c9b-43ce-9c1e-e063ccf7b4a6.png)

**Comment by esgnn** [comment]
I might be wrong, @cd25643 are you using Universal Render Pipeline? If so, I am not experienced in URP, but couldn’t find any reference to HDRI at volume documentation. If so, there seems to be a skybox [shader](https://docs.unity3d.com/Manual/skyboxes-using.html)

**Comment by cd25643** [comment]
@esgnn I am using a URP, thanks for the link...

@RuiyuZ I am looking in the exact same spot, but don't see the same menu options. Are you running the 0.9.0-preview.2 release? Perhaps you are not using a URP in your example?

![3](https://user-images.githubusercontent.com/100865605/158665311-437ae19a-3076-4212-8958-b770c0d34d5a.jpg)

**Comment by RuiyuZ** [comment]
@cd25643 Oh.. that's right, this option is not available in URP, only in HDRP, do you think you can switch to HDRP?

**Comment by cd25643** [comment]
@RuiyuZ Switched over to HDRP... Got everything set up again. I created the Sky Randomizer Tag and the Sky Randomizer. I keep running into this error...

![image](https://user-images.githubusercontent.com/100865605/158697769-70134765-5c02-4c4f-b4cc-e2cd596dcfba.png)

Looks like "HDRISky" is not a "type" that can be used in the script. This feels like I'm missing a directive/assembly reference?

**Comment by RuiyuZ** [comment]
@cd25643 yes, I think 
`using UnityEngine.Rendering.HighDefinition;`
is missing

**Comment by cd25643** [comment]
@RuiyuZ That fixed the HDRISky and Sky issues... but it looks like I'm still missing referneces for "CubemapCategoricalParamter" and "Volume". 
![11](https://user-images.githubusercontent.com/100865605/158833559-caea8f33-b255-4f17-88fc-5bf758a53d59.jpg)
![12](https://user-images.githubusercontent.com/100865605/158833592-e2aa3ddd-038e-48c5-a0c4-afa765dfd32b.jpg)

I haven't worked with a HDRP before, so I am likely just missing common references. Here are all my current references:
![13](https://user-images.githubusercontent.com/100865605/158833636-d17a865f-45d9-4a68-8bcb-3efbf7e087da.jpg)

**Comment by mkamalza** [comment]
Hi @cd25643 , apologies for the missing piece. This is actually a class that you need to add to your project. Just create a new C# class file and name it `CubemapCategoricalParameter.cs` parameter and paste the following into it:

```C#
using System;
using UnityEngine;
using UnityEngine.Perception.Randomization.Parameters;

/// <summary>
/// A categorical parameter for generating cubemap samples
/// </summary>
[Serializable]
public class CubemapCategoricalParameter : CategoricalParameter<Cubemap>
{
}

```

**Comment by cd25643** [comment]
That was the missing piece! Thanks for the assistance on this @mkamalza and @RuiyuZ !
