### ISSUE TITLE
Question: Is it possible to manipulate a "flexible" object for each frame of capture?

### ISSUE THREAD

**Issue by cd25643** [Unity-Technologies/com.unity.perception#438]
I am looking to capture 100 frames of a flexible object "drooping" over multiple stationary objects. For example, say I have a desk that has 5 items that are randomly placed on the desk, but then I want to also randomly place a phone charger that "droops" over whatever objects its placed on top of. Is something like this even possible with the perception package? From what I've seen, Ive only seen rigid/stationary objects be randomized...

**Comment by mkamalza** [comment]
Yes, accumulative effects are possible through rendering more than one frame per each Iteration of the Scenario. This is useful for things such as physics, temporal anti aliasing, auto exposure, and more. Have a look at the answer provided for this question in the [Perception FAQ](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/FAQ/FAQ.md) to get an idea of how to achieve this.

" I want to simulate physics (or other accumulative behaviors such as auto-exposure) for a number of frames and let things settle before capturing the Scene. Is this possible with the Perception package?"

**Comment by cd25643** [comment]
Fantastic, thanks for the link!
