### ISSUE TITLE
Color mismatch semantic segmentation

### ISSUE THREAD

**Issue by HenrikWerner** [Unity-Technologies/com.unity.perception#44]
Images generated with the SemanticSegmentationLabeler have slightly other colors than the colors which have been defined in the SemanticSegmentationLabelConfig (e.g. rgb 100,100,100 results in 32,32,32). If I explicitly create a new render texture in SemanticSegmentationLabeler.cs with RenderTextureReadWrite.sRGB given in the constructor than the generated images have the correct color as defined in the config. So Linear <-> sRGB conversions are missing.

**Comment by JonathanHUnity** [comment]
Thanks for the detailed report. I was able to reproduce this locally, and yes, looks like an easy fix. Will update this thread when we've published a new version. Thanks again!

**Comment by JonathanHUnity** [comment]
This will be released in the next version early next week. In the meantime you can try it out from master if you'd like.
