### ISSUE TITLE
generated dataset ?

### ISSUE THREAD

**Issue by an99990** [Unity-Technologies/com.unity.perception#448]
Hi,
So following the tutorial, it is said that we can modify the path where the generated dataset will be. 
![image](https://user-images.githubusercontent.com/87030365/160426839-29280700-3386-4983-b799-ffd01a826111.png)

However, I cant seem to fin Perception in the Project settings as mentionned. Also, the images are broken/missing from the README ?

![image](https://user-images.githubusercontent.com/87030365/160426437-f8e2bcc2-d90a-4663-a990-53bd2e30647a.png)

Unity version : 2020.2.7f1
Version 0.8.0-preview.4 - July 06, 2021

**Comment by an99990** [comment]
solution : in console it displays you the output of the generated dataset ..

**Comment by csun** [comment]
Hey there, thanks for finding this! The tutorial is out of date here and will be fixed.

The settings for modifying the dataset output path (as well as seeing the path to the latest dataset) can be found on your `Perception Camera` component. You can see this by selecting your camera in the scene and scrolling down in the inspector until you see the `Perception Camera` component and the `Output Base Folder` setting.

Hope that helps!

**Comment by an99990** [comment]
Yes thank you , 
for some reason that field isnt editable for me. 
Using unity 2020.3.20f1

**Comment by csun** [comment]
![Capture](https://user-images.githubusercontent.com/74614/160460654-659679a0-97fa-4dfc-9916-6b83798d1683.PNG)

Does this `Change Folder` button show up for you? If so, you should be able to click that and it'll let you select your output folder. You can't edit the text of the field directly, though.

**Comment by an99990** [comment]
no i dont have that button
![image](https://user-images.githubusercontent.com/87030365/160462999-8edac8a4-fa73-45f0-b842-5702dc72b5fa.png)

**Comment by csun** [comment]
Ah, I see that you're using version 0.8.0. I believe this feature for changing the folder was added in 0.9

**Comment by an99990** [comment]
alright thank you !
the only option is to upgrade to 0.10, but from other issues https://github.com/Unity-Technologies/com.unity.perception/issues/444 that broke other stuff so not taking a chance.

thank you for your time !

**Comment by csun** [comment]
For the record, I don't think that 0.10 broke configuring the output folder - it looks like one of the APIs just changed. As long as you're not setting the output folder from code you should be fine, but staying on 0.8 works too!

**Comment by moonsh** [comment]
@csun  I am using perception version 0.10 but I can't find the change folder button. Should I reimport the perception package?

![image](https://user-images.githubusercontent.com/13994270/162827144-86a604f3-f45b-4017-a426-3209bede1a94.png)

**Comment by moonsh** [comment]
@csun  Ah yes. I found it. Thank you! By the way, is there a way to change the path of the output using a script?

**Comment by csun** [comment]
It unfortunately looks like that functionality is not available in 0.10.0, but is being tracked in issue #444
