### ISSUE TITLE
how to set camera intrinsics 

### ISSUE THREAD

**Issue by an99990** [Unity-Technologies/com.unity.perception#449]
How would i set the camera intrinsic info for the perception camera ?

**Comment by csun** [comment]
Hey there - camera intrinsics are set on the `Camera` component of your camera. Select the camera in your scene, go into the inspector tab, and click on the `Physical` dropdown in its settings. You should see something like this:

![image](https://user-images.githubusercontent.com/74614/160460280-b5801190-6f95-4d21-9575-6f68143e6786.png)

**Comment by csun** [comment]
This is based on your Unity version, not the Perception package version, so it might be that 2020.2 is slightly different than 2020.3 (which is what I took a picture of). Sorry, I should've thought of that!

Regardless, you should be able to find similar settings somewhere in there if you dig around enough. Maybe in the "Projection" dropdown? [Here are some docs](https://docs.unity3d.com/2020.2/Documentation/Manual/PhysicalCameras.html) on this, though it looks like their screenshot is out of date as well.
