### ISSUE TITLE
OOB Annotations

### ISSUE THREAD

**Issue by ThreeDmund** [Unity-Technologies/com.unity.perception#453]
Hi is there anyway we can extract OOB annotations ?

**Comment by csun** [comment]
Hey there - could you please clarify what you mean by "OOB"? I'm not familiar with the acronym.

**Comment by ChumbaWambalala** [comment]
Hi sorry, it's OBB not OOB, my bad.
Oriented Bounding Box is what I'm trying to get.

**Comment by csun** [comment]
For Oriented Bounding Boxes, you can add a BoundingBox3D labeler. This will output annotations that include the size, position, and rotation of the bounding boxes.

[This tutorial](https://github.com/Unity-Technologies/Robotics-Object-Pose-Estimation/blob/main/Documentation/2_set_up_the_data_collection_scene.md) includes some instructions on how to set up a BoundingBox3D labeler in your project. Hope that helps!

**Comment by aryan-mann** [comment]
Closing for now, let us know if you have additional questions! 😃
