### ISSUE TITLE
RotationRandomizer not working in 0.10 

### ISSUE THREAD

**Issue by ChristianWiele** [Unity-Technologies/com.unity.perception#459]
Hi,

I created a simple scenario with just the foreground placer, and the rotation randomizer. While the foreground objects are placed correctly, the rotation is not changed.

Christian

Unity 2020.3.31
Perception 0.10.0-preview.
<img width="570" alt="Bildschirmfoto 2022-03-30 um 15 06 41" src="https://user-images.githubusercontent.com/6951534/160841559-e04be5f0-8f63-4817-b964-3acd2df7d4df.png">

**Comment by csun** [comment]
Hey there, Christian. Just to check - are there RotationRandomizerTag components on the prefabs that you're placing? The RotationRandomizer (and most other randomizers) works by querying objects in the scene that have the associated "Tag" component on them. If the prefabs you're spawning do not include that tag, they won't be processed by the RotationRandomizer.

**Comment by ChristianWiele** [comment]
Oh sorry, my bad. Working fine now.
