### ISSUE TITLE
3d bounding box doesnt work for human model.

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/com.unity.perception#463]
Someone already mentioned about 3d bounding box problem 3 months ago but I open a new issue again.

https://github.com/Unity-Technologies/com.unity.perception/issues/414
I found this issue but seems like it's very old so I wonder still it's not available to use the 3d bounding box.

I tested with the tutorial humanoid model in the perception tutorial and I added 3d bounding box labeler but.. it's not working.

**Comment by yumianhuli2** [comment]
> 

Skinnedmesh is probably not currently supported

**Comment by JonathanHUnity** [comment]
Yes @moonsh, this is still not yet supported. Feel free to keep following https://github.com/Unity-Technologies/com.unity.perception/issues/414 for this. 

We are curious about your use case for 3d bounding boxes on humans. Please drop an email to @shounakmitra at [shounak.mitra@unity3d.com](mailto:shounak.mitra@unity3d.com) to chat more about this. He is gathering feature requests and can share more about our roadmap.
