### ISSUE TITLE
Disabling labeler visualizations messes up semantic segmentation image name updates

### ISSUE THREAD

**Issue by XarisGeorgiadis** [Unity-Technologies/com.unity.perception#466]
Hello,

I am currently working on a project on version 0.9.0-preview.2.

I have modified the Semantic Segmentation Labeler script so that the semantic image names reflect the parameters (which are slightly modified on every iteration of the Fixed Length Scenario) of the current simulation. So, instead of using `{frameCount}`, I use another string which the script gets from another script, that I have attached to the main camera, which contains the new image name. I have a randomizer that changes that image name on every iteration of the Fixed Length Scenario, the `Frames Per Iteration` of which are set to 1.

What I discovered today was that disabling the "Show Labeler Visualizations" option of the Perception Camera in the Editor, increased the performance of my simulation improves by 20-30 FPS, which is obviously very desirable. However, I found out that the semantic segmentation image names are not properly updated, if that option is disabled. 

For example:
If I had 3 RGB images named `1_1_1_1.0_10.png`, `1_1_1_1.0_20.png`, `1_1_1_1.0_30.png` I would only have 2 semantic segmentation images named `1_1_1_1.0_10.png`, `1_1_1_1.0_30.png`, meaning that one image was not captured or had been overwritten.

I added the `{frameCount}` in front of the semantic image names in order to test whether the image names are not updated on every frame. After that, the image names would be (for example): `1_1_1_1_1.0_10.png`, `2_1_1_1_1.0_10.png`, `3_1_1_1_1.0_30.png` , where the first integer is the `{frameCount}`.

As you can see, while the `{frameCount}` was properly updated, the image names are sometimes not updated on each frame, only for the Semantic Segmentation Labeler.

As far as I understand, and I may be completely wrong, `OnSemanticSegmentationImageRead` is called from the `OnEndFrameRendering` function in the Perception Camera script, which I would imagine is called on every frame, after all the randomizers have run. I printed the changed image names in the `OnEndFrameRendering` function and they were all correct.

Since my randomizer that changes the image names does so on every frame, and since the RGB images are renamed properly and the image names were printed correctly as mentioned above, I do not understand how or why the semantic segmentation images are not.

Is this a bug or an issue I might have caused, or have I misunderstood how and when the semantic segmentation images are captured? 

Hopefully I have provided enough helpful information concerning my issue.

**Comment by vvernygora-unity3d** [comment]
Hello @XarisGeorgiadis,

Your assumption that **OnSemanticSegmentationImageRead** is called from the **OnEndFrameRendering** is not quite right. When visualizers are disabled, the images are read back from the GPU asynchronously, so **OnSemanticSegmentationImageRead** is called possibly a number of frames after the frame in which the scene was rendered. You have to be careful not to call methods in [Time](https://docs.unity3d.com/ScriptReference/Time.html) in this callback since there is no guarantee of what frame it is called in.

--
Vova

**Comment by XarisGeorgiadis** [comment]
Hello @vvernygora-unity3d and thank you for your reply.

Ah ok, I misunderstood how that all worked. So if I disable visualizations my only option is to rename the semantic segmentation images externally after the simulation has ended?

**Comment by JonathanHUnity** [comment]
If you are using the Time APIs to get frame IDs and such, you need to call those methods in OnEndRendering and pass them in to the call to OnSemanticSegmentationImageRead.

**Comment by XarisGeorgiadis** [comment]
Ok, I will try that out. Thank you!
