### ISSUE TITLE
Explanation of heartbeat.txt

### ISSUE THREAD

**Issue by XarisGeorgiadis** [Unity-Technologies/com.unity.perception#469]
Hello,

Could someone elaborate on what the values logged into the `heartbeat.txt` file represent? I apologize if this a dumb question but I am confused on what their purpose is and what the numbers mean.

**Comment by JonathanHUnity** [comment]
Hi @XarisGeorgiadis , this file is not necessary for normal running and is no longer produced in the latest version.
