### ISSUE TITLE
Failed to get visualizer process ID after launch (Windows 10)

### ISSUE THREAD

**Issue by Robotatron** [Unity-Technologies/com.unity.perception#472]
Clicking on "open visualizer" in the camera perception component does not open the app, only a warning below. Manually going to "http://localhost:8501/" does not work either. 
Any advice is appreciated! 

`Failed to get visualizer process ID after launch. Note that this does not necessarily mean the tool did not launch successfully. However, running the visualizer again will now create a new instance of the process. UnityEngine.UnitySynchronizationContext:ExecuteTasks ()`
![image](https://user-images.githubusercontent.com/95919873/164342596-7d98a429-0d48-4fb5-9fe7-1d65eea93907.png)

Unity 2020.3.33f1 and Unity 2021.3.0f1
Windows 10, 64bit, Version 21H2, OS build 19044.1645

Perception version 0.11.1-preview.1

![image](https://user-images.githubusercontent.com/95919873/164350698-d9c885b8-d63d-4774-9ba6-5a164ba27fc0.png)

**Comment by RuiyuZ** [comment]
Hi @Robotatron, sorry about the trouble you have been through. We have just fixed this visualizer installation issue on Windows, and it will be included in the next release of the perception package.

For now, if you don't mind, you can install and execute the visualizer via the command line, following the instruction here: https://github.com/Unity-Technologies/com.unity.cv.datasetvisualizer, this will open a web browser and you can select the dataset you want to visualize there.

Please let me know if this helps, thanks!

-Ruiyu

**Comment by RuiyuZ** [comment]
@Robotatron, do you mind taking a look at this directory on your computer? 

> C:\GitHub\public_com.unity.perception\TestProjects\PerceptionHDRP\Library\PythonInstall\Lib\site-packages\

Do the **unity_cv_datasetvisualizer-0.1.2.dist-info/** folder and **datasetvisualizer/** folder exists? I just tested visualizer on my windows laptop and it works fine.

**Comment by RuiyuZ** [comment]
Hi @Robotatron, we just published **Perception 0.11.2-preview.2**, and the visualizer is fixed here. You should be able to use the visualizer from unity editor as normal if you install this updated perception package.

**Comment by RuiyuZ** [comment]
Closing this issue as it was fixed in the new release, please feel free to reopen it if the error persists

**Comment by Robotatron** [comment]
Thanks @RuiyuZ, the new release did in fact fix the problem! Thank you.
