### ISSUE TITLE
3D Bounding Box visualization

### ISSUE THREAD

**Issue by umairkhawaja** [Unity-Technologies/com.unity.perception#474]
Can anyone help with understanding how to use these values of BoundingBox3d Labeler to visualize a 3D box?

`"translation": {
                "x": 36.20206,
                "y": -2.58197212,
                "z": 39.8012123
              },
              "size": {
                "x": 2.27042556,
                "y": 1.74524713,
                "z": 4.77659559
              },
              "rotation": {
                "x": 0.110200636,
                "y": 0.959971,
                "z": -0.257339865,
                "w": 0.009357027
              },`
              
 What is `w` in rotation? 
 
 @JonathanHUnity

**Comment by csun** [comment]
Rotation here is represented as a [quaternion](https://en.wikipedia.org/wiki/Quaternion#:~:text=Quaternions%20were%20first%20described%20by,the%20quotient%20of%20two%20vectors.). There are many other [ways of representing rotations](https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions) - do you know what format you are looking for? There are conversion functions between any of these formats, and most languages with have readily available implementations of these in third-party libraries.

**Comment by umairkhawaja** [comment]
Oh, thanks for clarifying that. I mainly wanted to plot this 3D box and was trying to understand how to go about that using this information

**Comment by csun** [comment]
Gotcha - what type of plot exactly? Could you describe what your desired output looks like and what language / libraries you're using? I might be able to help, but would need to know a bit more about your specific situation.

**Comment by umairkhawaja** [comment]
Just the visualization of the 3D box of each vehicle on the images. Nothing too specific, and using the standard python libraries. 

Thanks a lot!

**Comment by Robotatron** [comment]
You can use data insights package from Unity, they have a notebook for 3D box visualization - https://github.com/Unity-Technologies/datasetinsights/blob/master/notebooks/Perception_Statistics.ipynb

**Comment by umairkhawaja** [comment]
@Robotatron Thanks! This is exactly what I was looking for
