### ISSUE TITLE
Incorrect occlusion state using Keypoint Labeler

### ISSUE THREAD

**Issue by umairkhawaja** [Unity-Technologies/com.unity.perception#476]
I've been using the keypoint labeler to output some keypoints. However, it seems like there are cases where the state is incorrectly set to 1. In this sample, the center of the tyres are marked and should have been visible. I tried tweaking the self-occlusion distance, but that didn't change the results. Any idea what I'm missing?

EDIT: It's always the wheel points, and it seems like it occurs the most at this orientation as well (Side poses)

@StevenBorkman @JonathanHUnity 
![KeypointOcclusion](https://user-images.githubusercontent.com/13720047/164708932-846be892-ec39-4caa-a224-d81ed6eab86b.png)

**Comment by JonathanHUnity** [comment]
Do the wheels have a Labeling component on them? If the wheels are labeled separately from the car, the wheels will act as occluders for the car. In this case the self-occlusion distance will have no effect.

**Comment by umairkhawaja** [comment]
OH that makes sense. They do have a separate labeling component for segmentation. I did manage to fix the issue externally using segmentation masks. 

Do I need to remove the component, or disabling them would do the job?

Thanks a lot

**Comment by JonathanHUnity** [comment]
Try disabling them :)

**Comment by umairkhawaja** [comment]
It does work, although it still shows it as occluded in some cases but I guess that's how it just works? The point has to be directly visible by the camera, right? I replicated the KeypointLabeler's segmentation logic outside Unity and that seems to cover these cases though.

**Comment by JonathanHUnity** [comment]
In this case, try increasing the self-occlusion distance. Also, note that the point will not be marked visible if it is 'off' the object, so if there is a hole in the wheel and the point falls on top of the hole, it may not be marked visible.

**Comment by umairkhawaja** [comment]
Also, just a couple of side questions while I have you here:

1) I'm noticing that some points are being marked as visible if they go through a glass, any way to disable this behavior?
2) The FAQs mention that multiple cameras are not supported, however I'm using 5 cameras in the same scene and all of them work correctly. Does the FAQ means 1 perception camera component per camera game object?

**Comment by umairkhawaja** [comment]
Oh right, that does make sense now. This is really helpful, thank you!

**Comment by JonathanHUnity** [comment]
1. The package does not currently have special treatment for transparent objects. If you label the glass separately, it will act as an occluder, but that is the only solution I have for you at the moment.
2. Good to hear. Actually multiple separate cameras should be supported now, but we may need to update our documentation.

**Comment by umairkhawaja** [comment]
Thank you for your responses, closing this issue now
