### ISSUE TITLE
Visualizer not working on Mac

### ISSUE THREAD

**Issue by ChristianWiele** [Unity-Technologies/com.unity.perception#478]
Hi,

as my former issue was closed, and I can't reopen it, I create a new one. Still, in 0.11 the visualizer does not work on Mac. I get a message that the tool was installed successfully, and then an error, that the process was not found.

Christian

**Comment by RuiyuZ** [comment]
Hi @ChristianWiele, sorry about the trouble you have been through. We have just fixed this visualizer installation issue on Mac, and it will be included in the next release of the perception package. 

For now, if you don't mind, you can install and execute the visualizer via the command line, following the instruction here: https://github.com/Unity-Technologies/com.unity.cv.datasetvisualizer, this will open a web browser and you can select the dataset you want to visualize there.

Please let me know if this helps, thanks!

-Ruiyu

**Comment by ChristianWiele** [comment]
Just tried the new version 0.11.2, and now works fine.

Thanks a lot.
