### ISSUE TITLE
ReportAnnotation with custom label does not work

### ISSUE THREAD

**Issue by r-dh** [Unity-Technologies/com.unity.perception#485]
The example from the [documentation](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation%7E/DatasetCapture.md) to capture data with custom annotations does not work. More specifically, metrics are working fine, it is the ReportAnnotation() method that doesn't seem to have any effect on the final dataset.

This can be reproduced with the [example](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation%7E/DatasetCapture.md#example) on Unity 2020.3.33f1 with perception 0.10.0-preview.1.

**Comment by sleal-unity** [comment]
Hello @r-dh!

I've reproduced this issue for perception 0.10.0-preview.1 and confirmed that it is fixed in our most recent 0.11.2-preview.2 release. I would recommend upgrading to 0.11.2-preview.2 if possible.

Thanks for the head up!
