### ISSUE TITLE
Determine "Pose" of a vehicle in a custom labeler

### ISSUE THREAD

**Issue by umairkhawaja** [Unity-Technologies/com.unity.perception#486]
Hi, I wanted to somehow output some metric that measures the "pose" of a vehicle with respect to the camera sensor recording that frame. Does anyone have any ideas how this would be possible? For instance I have the rotation in world-coordinate-system of the vehicle but it would be different when viewing from the camera's field of view. So how can I get this metric?

**Comment by StevenBorkman** [comment]
Have you taken a look at the bounding box 3D labeler. It captures an object's bounding volume in 3D space with the coordinates relative the the camera's location. By your question I'm assuming that you are looking for the coordinates in a cartesian space relative to the camera, and not pixel space.

**Comment by umairkhawaja** [comment]
Oh, I assumed that it was capturing the world coordinates of the object. So the bounding box 3D Labeler outputs the rotation as a Quaternion, and if I were to convert that to some scalar theta, that defines its relative pose with respect to the camera, then do I take the angle between the camera's rotation and the rotation of the 3D box?

**Comment by StevenBorkman** [comment]
Yes, the 3D bounding box labeler includes a position (which is relative to the camera/sensor position), extents (axis aligned to the camera's coordinate system) and a quaternion which defines its orientation/rotation with respect to the camera.

**Comment by umairkhawaja** [comment]
Perfect, thanks!
