### ISSUE TITLE
Add multiple copies of same randomizer to scenario

### ISSUE THREAD

**Issue by methier-CPR** [Unity-Technologies/com.unity.perception#488]
I have a custom randomizer that takes in a parameter and would like to be able to add it multiple times to my scenario, each time with a different parameter. As far as I can see (on version 0.11.2-preview.2), once a randomizer is added to a scenario, it disappears from the "Add Randomizer" menu and cannot be added again.

**Comment by umairkhawaja** [comment]
I don't think a randomizer can be added multiple times, maybe try wrapping the randomizer in a for loop that runs N times with different seeds? You will need to handle saving those N frames and their corresponding labels. I think you'll need to set frames per iteration to N but I'm not entirely sure

**Comment by StevenBorkman** [comment]
Thanks for the question @methier-CPR. My colleague gave a very detailed answer to a similar question previously (https://github.com/Unity-Technologies/com.unity.perception/issues/313), and I hope it will help you out.

**Comment by methier-CPR** [comment]
Hi @StevenBorkman, I was able to figure out a solution based on the answer in #313. Thanks for the help!
