### ISSUE TITLE
Save Scenario Configuration File automatically for each run

### ISSUE THREAD

**Issue by umairkhawaja** [Unity-Technologies/com.unity.perception#489]
Is there any option to enable this? Or any code snippet that will output this JSON?

**Comment by StevenBorkman** [comment]
We do not have a way to do this automatically, generally the scenario configs stay pretty static between executions.

The main way we have to accomplish this is via the Editor with the following UI:
![image](https://user-images.githubusercontent.com/66975693/169618430-8695ecbd-114b-47ed-9ea8-db5a4db70d61.png)

But we do have public method in ScenarioBase class:
```c#
        /// <summary>
        /// Serializes the scenario's constants and randomizer settings to a JSON string
        /// </summary>
        /// <returns>The scenario configuration as a JSON string</returns>
        public virtual string SerializeToJson()
        {
            return ScenarioSerializer.SerializeToJsonString(this);
        }
```

You could write some code to call this method every time when a simulation runs automatically. I hope this helps.

**Comment by umairkhawaja** [comment]
Oh. Yes, I was doing this previously, but wanted to remove the manual effort to save this on each run
