### ISSUE TITLE
Layer mask for ground truth 

### ISSUE THREAD

**Issue by ChristianWiele** [Unity-Technologies/com.unity.perception#495]
Hi,

is there any option to ignore certain layers when generating the ground truth? I have a mesh in my scene that needs to be ignored.

Thanks, Christian

**Comment by aryan-mann** [comment]
Hey @ChristianWiele, for clarification, would you want a GameObject to only be ignored in a particular labeler (for example, having its bounding box show up but hide it in say instance segmentation) or ignored by all labelers?

**Comment by ChristianWiele** [comment]
I want some meshes not to be rendered for the ground truth, but for the image itself. The issue is the following:
I use an ocean shader that uses vertex shaders for displacing the vertices, but this is not supported by the Perception package. So I want to create a second mesh that is deformed by a compute shader, and mimics the ocean surface. For the image itself I use the ocean shader to get the visual side correct. For the ground truth I want the ocean mesh to be ignored (as it is just a flat mesh). Instead, the generated mesh (with a transparent material) should be taken into account.

**Comment by aryan-mann** [comment]
Hey @ChristianWiele, I checked with the team and it seems like we have this feature implemented already 🎉  (not yet available in the latest Perception release). Is this issue a blocker for your project?

**Comment by ChristianWiele** [comment]
Hey @aryan-mann, thanks for the update. When is the release planned? If I know it is coming, I can start implementing the work around. And I have enough other things to implement before I really need the feature. So, an upfront delivery is probably not necessary.

**Comment by ChristianWiele** [comment]
I got the compute shader working, only need the overriding of the layer mask. 
![ocean_sematic_segmentation](https://user-images.githubusercontent.com/6951534/172369869-f6fad169-1ee8-4f3b-a6f2-623ffaa471f2.gif)

**Comment by aryan-mann** [comment]
Looks super slick @ChristianWiele 🎉 ! For information about the release timing and other features we have in the works, you can reach out to @shounakmitra at [shounak.mitra@unity3d.com](shounak.mitra@unity3d.com). Otherwise, let me know if the perception team or I can help out with anything else 😄!

**Comment by StevenBorkman** [comment]
Hey all! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! Along with all of the new major improvements, we have fixed a lot of other bugs that we have discovered along the way, including this one reported by you. Thanks for being an active user and reporting this issue.

There are a bunch of cool features to check out such as ray tracing, depth, a new output format SOLO, normals, and more! Here is the full list of changes: [Perception 1.0 Changelog](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/CHANGELOG.md)

**Comment by davidfant** [comment]
@ChristianWiele how would one exclude certain objects from some ground truth renders? I'm trying to do something similar here where I want to remove Synthetic Human clothes: https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/issues/3

**Comment by csun** [comment]
Looks like you go into the perception camera component and look for a field called "layerMaskOverride". Not sure if you can set it for just the depth labeler or if it needs to apply to that + the color image as well.

From there, you can move all of your clothing objects to a specific layer. I detailed how to do that in your i[ssue on the synthetichumans repo](https://github.com/Unity-Technologies/com.unity.cv.synthetichumans/issues/3)
