### ISSUE TITLE
Disable Labelling Half Visible Objects 

### ISSUE THREAD

**Issue by anchal-28** [Unity-Technologies/com.unity.perception#497]
Hi , Is there any way in which we can disable the labelling of the objects that are half visible. Like, for every iteration unity perception will check whether a particular object is fully visible or not and if partially visible, then it wont get labelled in that image frame. 
I have tried this using couple of ways but none of them seems to work fine.

**Comment by Robotatron** [comment]
I'd like to know too. This problem is even worse, because Perception labels an objects that might only be visible for 0.1%, being just couple of pixels. And the 2d bounding box will cover only these 10 pixels, not the whole occluded object

**Comment by aryan-mann** [comment]
Hey @anchal-28 and @Robotatron, in the latest Perception release although there are ways to approximate how visible/occluded a labeled object is (such as adding keypoints to all objects and seeing how many keypoints are visible out of the total), they are a bit inconvenient to implement. 

:tada: However, we have an occlusion labeler in the works that can you give you visibility information. 🎉  You can get the percentage of an object visible in the frame or behind another object etc. that can be used to filter out bounding boxes of partially visible labeled objects! 

If this seems of interest, feel free to drop an email to @shounakmitra [(shounak.mitra@unity3d.com)](mailto:shounak.mitra@unity3d.com) and he can take it from there!

**Comment by FedericoVasile1** [comment]
Thank you for the update aryan, I'm also interested in this occlusion labeler 😄

**Comment by methier-CPR** [comment]
Hi @aryan-mann, thanks for the good news! I sent an email about a month ago to @shounakmitra asking for timeline estimates for the visibility calculations and still have not gotten an answer. Would you be able to provide an estimate on when we can expect this feature to be released?

**Comment by shounakmitra** [comment]
Hi Methier,

I'll reply to your original email thread.

Shounak

**Comment by AnchalT28** [comment]
Hi @shounakmitra ,
I had also sent a mail to you regarding the same. But haven't received any reply yet.

**Comment by shounakmitra** [comment]
Pls check your email Anchal. I’ve requested for a time to chat this week.

**Comment by AnchalT28** [comment]
Sorry for the misunderstanding

**Comment by Robotatron** [comment]
> Hey @anchal-28 and @Robotatron, in the latest Perception release although there are ways to approximate how visible/occluded a labeled object is (such as adding keypoints to all objects and seeing how many keypoints are visible out of the total), they are a bit inconvenient to implement.
> 
> 🎉 However, we have an occlusion labeler in the works that can you give you visibility information. 🎉 You can get the percentage of an object visible in the frame or behind another object etc. that can be used to filter out bounding boxes of partially visible labeled objects!
> 
> If this seems of interest, feel free to drop an email to @shounakmitra [(shounak.mitra@unity3d.com)](mailto:shounak.mitra@unity3d.com) and he can take it from there!

Sounds great! Will the occlusion labeller also provide a bounding box (and a mask for instance segmentation) when the object is partly occluded? Or is it beyond the scope of the occlusion labeller?

**Comment by FedericoVasile1** [comment]
@shounakmitra Hi :smile: I sent you an email too

**Comment by RuiyuZ** [comment]
@Robotatron It is beyond the scope of the occlusion labeler, but the bounding box labeler and the instance segmentation labeler will still work as usual which applies to the case when the object is partly occluded

**Comment by StevenBorkman** [comment]
Hey all! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! With this release we have introduced a new occlusion labeler which will provide the occluded amount (as a percentage) to all labeled objects.

There are a bunch of cool features to check out such as ray tracing, depth, a new output format SOLO, normals, and more! Here is the full list of changes: [Perception 1.0 Changelog](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/CHANGELOG.md)
