### ISSUE TITLE
3D annotations Human pose data

### ISSUE THREAD

**Issue by pulsingcoder** [Unity-Technologies/com.unity.perception#500]
Is there any way to generate 3D annotation of human key points synthesized dataset?

**Comment by StevenBorkman** [comment]
Can you clarify a little on what do you mean by 3D annotation. Currently our keypoints are recorded in pixel coordinates. We have had a previous request to also support recording keypoints in 3D cartesian coordinate space from the camera's perspective.

If this is what you are looking for, and you are willing to modify code then I think this could be as simple as modifying [KeypointLabeler.cs](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Runtime/GroundTruth/Labelers/Keypoints/KeypointLabeler.cs#L660) (around this line) and replace the call of ConvertToScreenSpace(position) with something like:
```
var pt = perceptionCamera.attachedCamera.transform.InverseTransformPoint(worldLocation).
```
This should give you the coordinate in 3D space based on camera location. From there, you will have to modify the data structures that report the data out to json to support the new data type.

**Comment by pulsingcoder** [comment]
Hi Steven, Thanks for the reply. Yeah I was looking for the same thing!

**Comment by yangeer** [comment]
When I run the project, I get both location and cameraCartesianLocation. Does that mean cameraCartesianLocation is 3D annotation of human key points？

![keypoint](https://github.com/Unity-Technologies/com.unity.perception/assets/50071336/43aa733b-c575-43c8-9188-3bdae0832682)
