### ISSUE TITLE
Generalising to real life sittuations

### ISSUE THREAD

**Issue by VirajVaitha123** [Unity-Technologies/com.unity.perception#501]
Hey,

In your tutorials it doesnt show the use of the trained model on real life images. Did the grocery or retail dataset help train object detectors that predict groceries in real life?

Thanks,

Viraj

**Comment by vvernygora-unity3d** [comment]
Hi Viraj!

You can read articles about the benefits of synthetic data usage here:

https://unity-technologies.github.io/PeopleSansPeople/
https://blog.unity.com/technology/training-a-performant-object-detection-ml-model-on-synthetic-data-using-unity-perception
