### ISSUE TITLE
Synthetic data doesn't generalise to real images (Was going to present this solution globally at my company)

### ISSUE THREAD

**Issue by VirajVaitha123** [Unity-Technologies/com.unity.perception#503]
Hi,

I was going to present this technology at a global event at work. Unfortunately the results have been disappointing. There isn't one example in the documentation/tutorials of using a detector trained synthetic images performing on REAL images, I was wondering why that was.

I even downloaded your dataset containing images of housing images (chairs, sofa,dining table etc..) that used HDRP, and realistic conditions. You would think a detector trained on a dataset you've already carefully created would generalise right?

I trained the model (even with pretraining) and receiving amazing statistics on the synthetic test/validation data)

90.4%
mAP

95.7%
precision

83.5%
recall

However, whenever I upload a real picture of a dining table or other, it fails to detect them. The most it really detects is chairs, which is misleading as I had used pre-training with COCO dataset that had learnt representations of chairs through this dataset anyway.

Whenever I've tried to ask for help i've been being sent a link of a blog post that has been fabricated to hide the fact there are no tutorials or examples of showing how this detector works on real images!

**Comment by esgnn** [comment]
Hi Viraj,

Links below might be helpful. (I am not from Unity btw).

1. [Unity Perception: Generate Synthetic Data for Computer Vision](https://arxiv.org/abs/2107.04259) + [accompanying real dataset](https://github.com/Unity-Technologies/SynthDet/blob/master/docs/UnityGroceriesReal.md)
2. [PeopleSansPeople: A Synthetic Data Generator for Human-Centric Computer Vision](https://arxiv.org/abs/2112.09290) + [repo](https://github.com/Unity-Technologies/PeopleSansPeople)
3. [Indoor Pet Detection Example (repo)](https://github.com/Unity-Technologies/Indoor-Pet-Detection)

**Comment by VirajVaitha123** [comment]
This helps a lot thank you esgnn
