### ISSUE TITLE
Understanding the randomizer attributes

### ISSUE THREAD

**Issue by lchunleo** [Unity-Technologies/com.unity.perception#508]
Hi,

  I would like to understand the properties for the Object Placement randomizer for Animation Curve, Constant, Uniform and Normal.  Though from the wordings, i can more of less infer but would appreciate some way of referring to some documentation or writing on this , with examples preferred. Thank you

**Comment by JonathanHUnity** [comment]
Good suggestion! I'll keep this open until we are able to add this documentation. In the meantime if you do have any questions let us know.

**Comment by aryan-mann** [comment]
Hey @lchunleo! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! We added documentation on the various aspects of randomization (scenarios, samplers, etc.) You can find that information over here [Randomization](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/Randomization/Index.md). 

There's a new section on Samplers (such as Constant, Uniform, etc.): [Samplers](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/Randomization/Samplers.md)
