### ISSUE TITLE
Generate a dataset using a Lidar/Radar/Sonar sensor instead of a camera

### ISSUE THREAD

**Issue by XarisGeorgiadis** [Unity-Technologies/com.unity.perception#510]
Hello,

Is it possible to generate a dataset where the sensor is a lidar, radar or sonar instead of a camera? The Synthetic Dataset Schema page mentions lidar, radar and sonar sensors but I am not sure if and how a non-camera sensor can be added to Unity.

**Comment by JonathanHUnity** [comment]
Hi @XarisGeorgiadis , while the schema is flexible to support other sensors, there are no other sensor implementations available at the moment. Some users have implemented their own sensors by doing custom rendering or using Physics raycasts and reported their data via the [DatasetCapture API](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/DatasetCapture.md)

**Comment by XarisGeorgiadis** [comment]
Got it. Thank you for your reply!
