### ISSUE TITLE
Controlling Scenarios of randomizations

### ISSUE THREAD

**Issue by VirajVaitha123** [Unity-Technologies/com.unity.perception#512]
Hi there,

I hope you're well.

I was wondering if we could:
-Control number of foreground images in the scene
-  do specific randomizations for X iterations. For example random objects with random textures for 1000 images, then google image backgrounds for next 1000 etc.. If I was to run simulations seperately the labelling always starts from same index so I would have to change them for image and labels.
- Don't include image if image isn't completely in scene (may occur if i use a camera  position randomization to change scale of items)

Thanks,

Viraj

**Comment by StevenBorkman** [comment]
Hey Viraj,

Thanks for reaching out. I think you could accomplish your first question with a custom randomizer (please see custom randomization section of the [tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/Tutorial/Phase2.md)). I think in your custom randomizer you could have some logic like (this is all very pseudo-codey:
```c#
protected override void OnIterationStart()
{
    m_CurrentCount++;
    
    if (m_CurrentCount % 1000 == 0)
    {
        texture_pool = switch_to_other_texture_pool();
    }

    renderer.material.SetTexture(k_BaseMap, texture.Sample());
}
```
Also see [TextureRandomizer.cs](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/TextureRandomizer.cs) for and example on how to make a texture randomizer.

You would need to set up your scene's scenario manager to run for 2000 (or whatever number you would like) frames.

For your second question, that's a little more difficult to accomplish with our current set of labelers. It is fairly easy to check if an object is completely out of the scene, but partial out of bounds is not as easy. One way to pseudo accomplish this is to put keypoints on the corners of an object. The keypoint labeler will report if a keypoint is on screen or not. You could look at the results and determine if all of the keypoints are visible. But this will only provide results as good as your keypoint placement.

You may also be able to use the 3D bounding box labeler, and project the corners of the bounding box into pixel space and check if the pixel coordinates are in the scene.

I hope this helps a at least a little bit, and please respond with anymore questions.

Steve
