### ISSUE TITLE
Occlusion in Human Pose not working

### ISSUE THREAD

**Issue by SteveGaukrodger** [Unity-Technologies/com.unity.perception#513]
Hi,

I've been trying to follow the tutorial for Human Pose Labelling, but I can't seem to get the occlusion to work. When points are offscreen they are in state 0, when they are onscreen they are in state 2, whether they are visible or not.

I should add that all occlusion is self-occlusion there are no other objects in the scene. Is there any way to make this work?

Kind regards,

Steve

**Comment by StevenBorkman** [comment]
Hey all! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! With this release we have introduced a new depth labeler that records the depth of all objects. This depth labeler works with the keypoint labeler.

There are a bunch of cool features to check out such as ray tracing, depth, a new output format SOLO, normals, and more! Here is the full list of changes: [Perception 1.0 Changelog](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/CHANGELOG.md)
