### ISSUE TITLE
How can i get the labels' infomation of a frame at unity runtime with c#.

### ISSUE THREAD

**Issue by Abluceli** [Unity-Technologies/com.unity.perception#521]
Hi,
How can i get the labels' infomation of a frame at unity runtime with c#.
Thank you in advance.

**Comment by StevenBorkman** [comment]
Hi @Abluceli, I will be glad to help, but I'm not really sure what you are asking for right now. Can you maybe add some more detail to your question?

**Comment by aryan-mann** [comment]
Hi @Abluceli 👋 , closing this issue for now.
If you still need assistance, feel free to continue this thread with more details and I can open the issue back up.

Thanks for trying out the Perception package!
