### ISSUE TITLE
Unity Perception images are not visible in the RGB output folder, how can I fix this?

### ISSUE THREAD

**Issue by geocolon** [Unity-Technologies/com.unity.perception#527]
I want to create synthetic data images for a machine learning project. I am following this tutorial from Roboflow. https://blog.roboflow.com/unity-perception-synthetic-dataset-tutorial/

When I go to the output files to see these images, they are blank PNG files. So why can I not see the models I created for this project? Below is a screenshot of my output.

<img width="640" alt="Screen Shot 2022-09-14 at 12 19 59 PM" src="https://user-images.githubusercontent.com/7282802/190244914-54875bcb-16d8-42b6-8618-22b66d40f4ef.png">

The images should look like the example below. 

<img width="662" alt="Screen Shot 2022-09-14 at 12 32 01 PM" src="https://user-images.githubusercontent.com/7282802/190245935-b6753760-857e-49fd-b8f4-1d00d3158652.png">

Please let me know how I may fix this issue.

Thank you!

**Comment by aryan-mann** [comment]
Hey @geocolon! What Operating System, Unity version, and Perception version are you using?
We had a bug in a specific combination of these three (see #502) which can be fixed by updating to the latest package version.

**Comment by aryan-mann** [comment]
Closing this issue for now! Feel free to open up this thread if this issue still persists. 😄
