### ISSUE TITLE
Output Directory Solution Changed

### ISSUE THREAD

**Issue by rrmlgroup** [Unity-Technologies/com.unity.perception#528]
This is a new issue based on issue #107 Output Directory:

I recently moved from using version 0.7 to version 0.11.2 and when I tried to use the previous solution to set my own custom output directory I now get the following error:

Assets\Scripts\SetOutputDirectory.cs(11,9): error CS0103: The name 'Configuration' does not exist in the current context

Did Unity.Simulation.Configuration change? Or move? Please let me know what changed. I've tried looking at the API and such and can't seem to figure it out. Thanks.

**Comment by enickel00** [comment]
Do you need to change the output directory with a script, or could you just set it in the Project Settings? I believe older versions didn't have the capacity to change the directory, but in 0.11.2 you can change it in _Project Settings > Perception_

**Comment by StevenBorkman** [comment]
Hey all! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! A part of our user endpoint system rolled out in previous releases, but now with Perception 1.0, the full implementation is complete. As @enickel00 pointed out you can use Project Settings > Perception to change the endpoint location. Additionally, this [method ](https://github.com/Unity-Technologies/com.unity.perception/blob/f45895f7dcad27dee545d6165a2f6c237554600a/com.unity.perception/Runtime/Settings/PerceptionSettings.cs#L143 )should allow to change the output directory from a script.

There are a bunch of cool features to check out such as ray tracing, depth, a new output format SOLO, normals, and more! Here is the full list of changes: [Perception 1.0 Changelog](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/CHANGELOG.md)
