### ISSUE TITLE
Synthetic labelled data using Images

### ISSUE THREAD

**Issue by VirajVaitha123** [Unity-Technologies/com.unity.perception#533]
Hey there,

For my usecase I want to import some 2D images (as my foreground objects) and randomize the location of these images. 

Is it possible to use this tool for this 2D usecase or is it only using 3D models?

If so the only way around this is to create a 3D model and attach the image onto it?

Thanks,

Viraj

**Comment by StevenBorkman** [comment]
Hey Viraj,

You should be able to accomplish this by creating quad geometry and then applying your 2D images to them as textures.

**Comment by aryan-mann** [comment]
Hey Viraj, closing this issue for now. Feel free to open it up if the issue still persists.
