### ISSUE TITLE
How to get the label for euler rotations of all keypoints?

### ISSUE THREAD

**Issue by cjerry1243** [Unity-Technologies/com.unity.perception#535]
I am trying to get the euler rotations of all the joints for my character. 
Currently the keypoint labeler only provides 2D joint positions. The bounding box 3D labeler has 3D orientation of the character.

I would like to get the 3D information (positions/rotations) for all joints of the character.
Is there a way to do it?

**Comment by aryan-mann** [comment]
Hey @cjerry1243! With our latest release Perception 1.0, we did add another field to the keypoint annotations to capture the position of the keypoint in camera-space. Unfortunately, it does not include rotation information of the keypoints. 

The best way to solve your issue would be to add rotation value in yourself after cloning our package. You can look at how we gather keypoint position information (`cameraCartesianLocation` in the `KeypointValue` class) and use that to guide your implementation which would involve changing a few lines of code in a few classes here and there.

**Comment by mshooter** [comment]
@aryan-mann 
Could you tell me if there is a guideline on how to modify the code and how to run the modified code?

**Comment by cjerry1243** [comment]
Thank you. 
I followed the tutorial for DatasetCapture and looked into how the 2D keypoints are calculated in the package.
Now it's solved.
