### ISSUE TITLE
Unable to add labels to the IDLabelConfig via Script

### ISSUE THREAD

**Issue by AnchalT28** [Unity-Technologies/com.unity.perception#537]
I want to add more labels to LabelConfig List via Script but i am unable to do this.
The labelEntries list inside LabelConfig is resposible for containing all the labels but it has only the getter, there is no setter function.

Is there a way to change or add labels to the LabelConfig during runtime?

**Comment by aryan-mann** [comment]
Hey @AnchalT28, thanks for trying out the Perception package. A LabelConfig can be dynamically updated by calling the `Init` function which basically acts as the setter in this case. However, this needs to be done at the start of the first frame.

Let me know if you have further questions!

**Comment by AnchalT28** [comment]
Hey @aryan-mann , Thanks for the info. It serves my purpose, I am able to add labels at runtime.

**Comment by aryan-mann** [comment]
Glad to hear that @AnchalT28, closing the issue 😄
