### ISSUE TITLE
Instance Segmentation annotations with contour points of mask

### ISSUE THREAD

**Issue by dootiedoot** [Unity-Technologies/com.unity.perception#538]
Hi, I am trying to figure out a way to generate array of points along the contour of each object in an instance mask such as example below where every instance is assigned a unique color id:

<img src="https://user-images.githubusercontent.com/1284333/204041273-dca18a32-8b5d-4749-b8eb-f97d949cfe1c.png" width=50% height=50%>

What I'm looking for is points that run along the contour of the instance mask for example below where the white dots encompass the region defines a couch and another region defining the chair:
<img src="https://user-images.githubusercontent.com/1284333/204042209-40f414e7-d9b3-44f2-94af-2626204d3a63.png" width=50% height=50%>

Currently, the SOLO output of the dataset includes path to segmentation image, instance id, and label color but no points unlike 2D bounding box XY coordinates unless I am missing this information somewhere.

My goal is to create dataset to train with Yolov5's latest v7.0 release that supports instance segmentation and inputs an array of contour points as ground truth data.

I'm thinking it may be possible to run post-process image difference and generate a polygon for each color or finding where the perception camera captures the instance mask and generating points from the mesh's bounding box? 

I can see some big caveats with these approaches, so any advice is appreciated.

**Comment by StevenBorkman** [comment]
We create our segmentation masks to be pixel perfect. Our philosophy is to create the most accurate data as possible, and then use post processing (generally in python) to generalize the data to meet a user's needs. We have a new python package, [pysolotools](https://github.com/Unity-Technologies/pysolotools) which allows you to parse a solo dataset and to do some conversions. We include a solo2coco [converter](https://github.com/Unity-Technologies/pysolotools/blob/main/pysolotools/converters/solo2coco.py) that, as a part of the conversion, converts our instance png images to RLE (run length encoded) masks. We don't have any examples of converting to polyline masks, just because they are not as accurate and have to generalize the data too much.

I have found this example (I am not really sure if it works, because I haven't tried it) that will go from RLEs to polygons: https://www.kaggle.com/code/linrds/convert-rle-to-polygons

Anyway, I think your best bet is to post process the data in python, and go from images -> RLEs -> polygons. I hope this helps.

Steve

**Comment by dootiedoot** [comment]
Hi Steve, 

Thank you for the advice, this was exactly what I was looking for and I believe this issue can be closed. 

SOLVED: For anybody who is having the same issue, below is a rough python script I expanded from the kaggle example link that (hopefully) translates Unity's SOLO segmentation RLEs (after coco conversion) into YOLOv5 label files.

```
import cv2
import os
import sys
import glob
import pycocotools.mask as mask_util
import json

PATH_TO_CONVERTED_COCO_DIR = 'datasets/coco/'

#   converts RLE data to polygon array
def polygonFromMask(maskedArr): # https://www.kaggle.com/code/linrds/convert-rle-to-polygons/notebook

    contours, _ = cv2.findContours(maskedArr, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

    segmentation = []
    for contour in contours:
        # Valid polygons have >= 6 coordinates (3 points)
        if contour.size >= 6:
            segmentation.append(contour.flatten().tolist())
    #   base cases
    if len(segmentation) <= 0:
        return
    RLEs = mask_util.frPyObjects(segmentation, maskedArr.shape[0], maskedArr.shape[1])
    RLE = mask_util.merge(RLEs)
    # RLE = mask.encode(np.asfortranarray(maskedArr))
    area = mask_util.area(RLE)
    [x, y, w, h] = cv2.boundingRect(maskedArr)

    return segmentation[0] #, [x, y, w, h], area

#   converts polygon array to json
def write_polygons_to_yolo_format(json_file, save_dir):
    #   file base cases
    if not os.path.exists(PATH_TO_CONVERTED_COCO_DIR):
        print("coco directory does not exists: '{}'".format(PATH_TO_CONVERTED_COCO_DIR), file=sys.stderr)
        return
    labels_file_path = os.path.join(PATH_TO_CONVERTED_COCO_DIR, 'labels')
    if not os.path.exists(labels_file_path):
        os.makedirs(labels_file_path)

    #   clear any left over files
    files_to_delete = glob.glob(os.path.join(labels_file_path, '*'))
    for f in files_to_delete:
        os.remove(f)

    #   load annotations JSON, parse into polygons, then write polygons to file in YOLO format
    with open(json_file) as f:
        imgs_anns = json.load(f)
    for i, annotation in enumerate(imgs_anns["annotations"]):
        print('Processing annotation {}/{}'.format(i, len(imgs_anns["annotations"])))
        
        #   initialize variables
        image_id = annotation["image_id"]
        category_id = annotation["category_id"]
        rle = annotation["segmentation"]
        height = rle.get('size')[0]
        width = rle.get('size')[1]
        #compressed_rle = mask_util.frPyObjects(rle, rle.get('size')[0], rle.get('size')[1])
        #mymask = mask_util.decode(compressed_rle)
        mymask = mask_util.decode(rle)
        polygons = polygonFromMask(mymask)
        #annotation["segmentation"] = [polygons]

        #   post process polygons so their scaled by decimal offset from the image rather then perfect pixel coordinates
        if polygons is None:
            continue
        for i, coorindate in enumerate(polygons):
            if i % 2 == 0:
                polygons[i] = coorindate / width
            else:
                polygons[i] = coorindate / height

        #   clear file then write to file
        file_name = 'camera_{}.txt'.format(image_id)
        file_path = os.path.join(labels_file_path, file_name)
        with open(file_path, 'a') as file:
            polygonStr = ' '.join(map(str, polygons))
            file.write('{} {}\n'.format(category_id - 1, polygonStr))

def main():
    # Opening JSON file
    json_path = os.path.join(PATH_TO_CONVERTED_COCO_DIR, 'instances.json')
    write_polygons_to_yolo_format(json_path, 'annoation_results.json')

if __name__ == "__main__":
    main()
```
