### ISSUE TITLE
Pysolotools-Fiftyone installation not working 

### ISSUE THREAD

**Issue by mshooter** [Unity-Technologies/com.unity.perception#544]
when following the installation process of pysolotools-fiftyone we are getting this error:

"ERROR: Could not find a version that satisfies the requirement pysolotools>=0.10.0 (from pysolotools-fiftyone) (from versions: 0.0.1, 0.3.16, 0.3.17)
ERROR: No matching distribution found for pysolotools>=0.10.0"

[#issue installing](https://github.com/Unity-Technologies/pysolotools-fiftyone/issues/11#issue-1467235396)

**Comment by StevenBorkman** [comment]
Thanks for pointing this out to us. We are working on fixing this now, and I'll let you know when we have it fixed.

**Comment by StevenBorkman** [comment]
Hey @mshooter, I think I have fixed the issue, so please try again when you get a chance. You may have to tell it use a newer version explicitly when you pip install because pip will want to use a cached version if available.

`pip install pysolotools-fiftyone==0.3.25`

**Comment by gespona** [comment]
@mshooter Last week I faced the same issue and I was able to fix some inconsistency between pillow versions on the pysolotools-fiftyone repo . Just change requeriments.txt file to point the right version. Setup something like pillow~=9.3.0 worked for me

**Comment by mshooter** [comment]
It's working thank you!

**Comment by mshooter** [comment]
It's working thanks!
