### ISSUE TITLE
Custom label: report every iteration instead of frames

### ISSUE THREAD

**Issue by mshooter** [Unity-Technologies/com.unity.perception#551]
Hi, 

I am trying to generate a file every iteration of the simulation how would I do that? 

Thanks!

**Comment by mshooter** [comment]
@mark1ng123 thank you for your suggestions I'll give it a try. 
I was hoping that the CameraLabeler class would have had a OnBeginIteration Function.

**Comment by mark1ng123** [comment]
@mshooter It has one, OnIerationStart you can implement a capture with PerceptionCamera class with my 1st soultion suggested, but then you need to inherit from randomizer and scenario, i would suggested goin in the monobehaviour instead and checking in the update method wheter you switched iteration or not with the classes i suggested above, seems like an easier and faster approach, but maybe the staff here has a better idea.

**Comment by mshooter** [comment]
@mark1ng123 based on your comment regarding the Update function - I was able to do what I needed to do :) 
Thank you very much

**Comment by mark1ng123** [comment]
Great, glad you manged to solve it :)
