### ISSUE TITLE
Unity Terrain not Rendering when used with Perception

### ISSUE THREAD

**Issue by vladSavenco-dotLumen** [Unity-Technologies/com.unity.perception#564]
I am using the latest version of perception which is supposed top have support for unity terrain. 
![step4 camera semantic segmentation](https://user-images.githubusercontent.com/108801308/212666715-99efb9b4-f4c4-496e-9065-7381ab1c0c65.png)
![step4 camera](https://user-images.githubusercontent.com/108801308/212666729-4901e22e-ad47-4f8f-8022-2e8dd3a5d683.png)
Those 2 pictures show the scene with no segmentation and with segmentation. In the segmented one you can see that the terrain is not being rendered.
I have added the labelling component to the terrain game object and set its labels, is there anything more to that?
![image](https://user-images.githubusercontent.com/108801308/212667171-057d579c-f570-474b-9d98-68fcb84e17a1.png)

**Comment by loulouzny** [comment]
I am having exactly the same issue. It would be really appreciated if anyone can help. 

Besides, for terrain, is there a way to separate objects and the ground? I wanted to do semantic segmentation on a forest environment. But it has all the trees and grass "belong" to one big terrain component, and therefore I cannot label the objects.

**Comment by ningyuanz** [comment]
I partially solved this by disabling "Draw Instanced" in Terrain -> Terrain Settings. But still cannot label trees and details for segmentation.

**Comment by vladSavenco-dotLumen** [comment]
> I partially solved this by disabling "Draw Instanced" in Terrain -> Terrain Settings. But still cannot label trees and details for segmentation.

Oh, ok will take a look. Thank you!
