### ISSUE TITLE
Can you use perception to segmentate objects based on their textures?

### ISSUE THREAD

**Issue by vladSavenco-dotLumen** [Unity-Technologies/com.unity.perception#569]
I have a very large object and it has a splatmap with multiple materials. I would like each material to be segmented as a different colour. Is this something that perception can do? I was unable to find an answer to this in the documentation.

**Comment by StevenBorkman** [comment]
Hi @vladSavenco-dotLumen, perception uses game objects for segmentation, and does not support texture based segmentation.

**Comment by vladSavenco-dotLumen** [comment]
Ok, I see. Thank you @StevenBorkman !
