### ISSUE TITLE
Problems with running simulation after adding new prefab

### ISSUE THREAD

**Issue by elaborate-username** [Unity-Technologies/com.unity.perception#570]
I have been using the steps in the tutorial to create and play a simulation scenario with my own prefabs. The first one I used went well, and I generated 500 synthetic images. When I replaced the first prefab with another one (Both were imported fbx objects, textures were extracted and then converted to prefab as recommend in the tutorial). I have added the labels and the randomiser tags exactly as before and changed nothing else. 
Now though instead of the folder structure I got before (solo, with 500 sequence folders inside, with one image in each sequence) I get a solo folder with only sequence 0, and inside that I get unlimited photo's. The simulation does not end on its own and most importantly does not apply any of the randomizations. I get the same blank image every time of only my object.

I see that there are some assertion errors though, so I have added a screenshot of those.
I am relatively inexperienced so beginner-friendly guidance would be a great help. Thanks!
![Screenshot 2023-01-31 at 10 35 19](https://user-images.githubusercontent.com/26579148/215722867-905edfa7-4b3a-4336-80fe-eac129f56f6b.png)

**Comment by elaborate-username** [comment]
Extra note: It seems that when I delete the simulation game object and re-do that entirely, it works again

**Comment by mark1ng123** [comment]
Hey, do you update the list of the game object prefab before running again?
I also get this error when i forget to update the list in the randomizer, once a prefab is deleted he point to None obj in the list this obj needs to be deleted and replaced not only in the editor / folder but also on the randomizer prefab list which you set in the beginning.
Hope i heleped :)

**Comment by mkamalza** [comment]
As @mark1ng123 mentioned, it looks like there is a reference to a null object left in your randomizer, inside the scenario. Make sure no such reference exists and that your new prefab is properly linked in the randomizer.

**Comment by mark1ng123** [comment]
Hey @mkamalza, the guy who opened the issue havent replied for over a month, i suggest closing the issue if he is still struggling he may re-open it, 
Have a nice day :)
