### ISSUE TITLE
Customize bounding box script and randomization using local JSON values

### ISSUE THREAD

**Issue by benrajsdKiksARVR** [Unity-Technologies/com.unity.perception#574]
Hi, I have customized some of the scripts from perception package based on requirement, added the package from local path, package get added but shows error in Render assets as "Ground Truth Renderer Feature" not available. How can I customize the scripts of packages?

**Comment by benrajsdKiksARVR** [comment]
I want bounding box corner position values in generated JSON file

**Comment by StevenBorkman** [comment]
Hey, I'm trying to re-create your problem and I am not able to. I'll go through the steps that I took to create my project:

1. Created a new project from the `3D (HDRP)` template from Unity Hub, using Editor Version `2021.3.11.f1`
2. Cloned the perception repo (branch main) from our github
3. Added the cloned perception package to the package manager using the 'Add package from disk...' option
4. Added a perception camera to the camera gameobject.
5. Adjusted the default HD Render Pipeline Assets to use `Both` for the `Lit Shader Mode`
6. Ran and captured data as expected.

If these steps do not help to alleviate you issue, please describe your current setup. Also, be sure that you are using an HDRP scene. Perception no longer supports scenes that are not using the HDRP render pipeline.

I hope this helps
- Steve
