### ISSUE TITLE
Semantic Segmentation not working (HDRP, 2021.3.19f1)

### ISSUE THREAD

**Issue by MaximeRoedele** [Unity-Technologies/com.unity.perception#576]
Hi, I've been working with the perception package for a while now and recently sougth to remake my previous URP simulator in HDRP. I've gone through all of the steps in the [official tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/Tutorial/Phase1.md#step-4) 3-4 times now, but am not able to generate any semantic segmentations of basic objects in a scene. Would love some help as I am completely stuck 😓

The image below is the current game view in the editor. The cube has a Semantic Segmentation label which is supposed to make it Green, however nothing happens when adjusting the slider labeled **Object alpha**. The slider named **Background alpha**, however, renders the entire game-view black. I tested the Semantic Segmentation Labeler by changing the supposed color of the background, but the change does not register either. The label used in the Semantic Segmentation Labeler and on the cube are identical and the Semantic Segmentation Labeler is referenced on the Perception Camera. 

I also tried with other Labelers and 2D/3D bounding boxes, but nothing yields any results. 

![image](https://user-images.githubusercontent.com/47213803/221221338-9033bcab-515d-4dd1-8e36-c7f341b5a58e.png)

Here is a thorough description of the steps i took:

1. Downloaded the newest recommended version of Unity (2021.3.19f1) as well as the 3D (HDRP) core template before making a new project. 
2. Installed the package through the package manager through **_Add package from git URL_** with `com.unity.perception`. I did not install the tutorial files. 
3. Added the _**perception camera**_ component to the main camera. Turned off _**save RGB output**_ as I wouldn't need it and turned the _**capture trigger mode**_ to _manual_. 
4. Resolved the errors occuring by turning off _**Asynchronous Shader Compilation**_ in _**Edit -> Project Settings -> Editor**_ and changed _**Lit shader mode**_ to _both_ in the following files:
 -  _**Assets -> Settings -> HDRP High Fidelity**_
 - _**Assets -> Settings -> HDRP Balanced**_
 - _**Assets -> Settings -> HDRP Performant**_
 - _**Assets -> Settings -> HDRPDefaultResources -> HDRenderPipelineAsset**_
There is another file in the last folder: _**Assets -> Settings -> HDRPDefaultResources -> HDRenderPipelineGlobalSettings**_ with various similar fields, but these only contain the options of **Forward** or **Deferred**.
5. Made a _**Semantic Segmentation Label Config**_ in the project by _**Create -> perception -> Semantic Segmentation Label Config**_. Added a label to this config by pressing **Add new label**. 
6. Added the label config to the perception camera by pressing the (+) button under **Camera labelers** and adding a **Semantic Segmentation labeler**. Linked this to the Semantic Segmentation Labeler described in (5).
7. Added a cube to the scene and added a **_Labeling_** component to it. Added the label from the Semantic Segmentation Labeler described in (5) by pressing _**Add New Label**_ under **Added labels**.

**Comment by StevenBorkman** [comment]
Hey @MaximeRoedele, thanks for using Perception. I haven't got a chance yet to retry what your steps, but have you tried putting the perception camera back to `scheduled`. Just from your description, there doesn't seem to be anything actually causing the perception camera labelers to activate. Although you do not need the rgb captures. The perception camera still needs to trigger a capture so that the scene can be process and the selected labelers triggered.

I hope this fixes your issue.
Steve

**Comment by MaximeRoedele** [comment]
Hi @StevenBorkman, sorry for the late reply! You were absolutely right, this solved the issue! Thanks :)
