### ISSUE TITLE
Inquiry about the Perception Package's Current Status and Future Updates

### ISSUE THREAD

**Issue by Rawdreen** [Unity-Technologies/com.unity.perception#606]
Hello there!

It has been a while since the last update and there haven't been any activities from the Perception Package team.

I appreciate the effort put into developing this package, but I am concerned about its future. Could you please provide an update on whether the project will continue to be maintained and updated in the future?

I look forward to hearing from you soon.

Thank you and best regards!

**Comment by mkamalza** [comment]
Hi @Rawdreen , please see this issue
https://github.com/Unity-Technologies/com.unity.perception/issues/604#issuecomment-1654259523
