### ISSUE TITLE
Blurry foreground object

### ISSUE THREAD

**Issue by TimotheeWrightFicha** [Unity-Technologies/com.unity.perception#610]
I basically have the same issue as #498 ([Blurry captures when using with HDRP](https://github.com/Unity-Technologies/com.unity.perception/issues/498) )

I tried changing the "Post Anti-aliasing" parameter under Camera -> Rendering to something different than "No anti-aliasing" but it did not change anything.

When my object has a HDRP/Unlit  or HDRP/Lit Material it has blurry effect but if I don't use HDRP it doesn't have this blur. All the tutorial i've seen suggest using HDRP for Unity Perception. What should i do ?

**Comment by TimotheeWrightFicha** [comment]
I guess i'll just don't use HDRP, i'll keep the issue for others :)

**Comment by esgnn** [comment]
Have you tried the proposed solution (switching motion blur off)?

**Comment by TimotheeWright** [comment]
Yes, the proposed solution is to have an anti-aliasing rendering which, as mentionned in my post, was not working for me

**Comment by esgnn** [comment]
[Motion blur](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@17.0/manual/Post-Processing-Motion-Blur.html) and [AA](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@17.0/manual/Anti-Aliasing.html) are two different things. I hope this solves you problem.
