### ISSUE TITLE
Cannot find the ParameterConfiguration component.

### ISSUE THREAD

**Issue by rajshekarreddy97** [Unity-Technologies/com.unity.perception#77]
According to these docs (https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Randomization/Index.md), it mentions to create a new ParameterConfiguration. But where is this component?

**Comment by mkamalza** [comment]
Hi. Do you mean the component is not present in the project when you search for it? 

The component needs to be added to an existing game object through these steps:
1. Create an empty game object in the scene by right clicking in the Hierarchy area and clicking Create Empty.
2. Select the newly created game object and look at the inspector window. There is a button named Add Component.
3. Click Add Component, and in the search bar that shows up start typing ParameterConfiguration, you should see the component as you type. Click on it, and it will be added to your game object.

**Comment by rajshekarreddy97** [comment]
The ParameterConfiguration script isn't present in the perception package. When I search for it in the Search Bar, nothing shows up. I Installed the perception package by adding the git url in the Package Manager.

**Comment by mkamalza** [comment]
Unfortunately, I cannot replicate the issue when I go through the steps mentioned in the tutorial. Can you please compress your project into one zip file and attach it here, so that I can review and see if I can find the issue? Thanks.

**Comment by rajshekarreddy97** [comment]
Here is the link to the project, https://indianinstituteofscience-my.sharepoint.com/:u:/g/personal/rajshekarg_iisc_ac_in/ERutnh-sNsdChdYg9eJT3pMBcXklmSn8hgtWE0taf7Timw?e=U6CAnF

**Comment by mkamalza** [comment]
Thank you for the link. What I can see is your project is using the 0.3.0 version of the Perception package, which does not contain randomization tools. Randomization was added in version 0.4.0. Perhaps you downloaded the package before the latest release?
Please try downloading the package again from Github using the **com.unity.perception** URL

**Comment by rajshekarreddy97** [comment]
I did not select the version while downloading though, I just added this URL 'com.unity.perception' in Unity's Package Manager, as to how the instructions said to do it. 

The project I linked to in the previous message was created just 2 days ago when version 0.4.0 was released. Perhaps Unity's package manager is downloading a previous version?

**Comment by mkamalza** [comment]
The downloaded version of the package actually depends on the Unity version you use for the project, as each Package defines a minimum compatible Unity Editor version. I see you are using Unity 2019.3, but the latest package version requires 2019.4. 

So to get the latest version, please first install Unity 2019.4.10, and then open your project with it. When it asks if you want to upgrade your project, answer yes.

If you are using Unity Hub, just install 2019.4.10, and then choose it as the Unity version for your project.

Once the project is loaded, open Package Manager and navigate to the Perception package. You should now see a button for updating to the latest version right there, at the bottom right corner of the window.

**Comment by rajshekarreddy97** [comment]
Yes, it is present on Unity 2019.4.10. Thank you for the support.
