### ISSUE TITLE
semantic mask label generation

### ISSUE THREAD

**Issue by HaiyiMei** [Unity-Technologies/com.unity.perception#80]
Hey! Great work there!
I have an issue that I want to generate masks for semantic segmentation image, and output labels like COCO dataset.
![image](https://user-images.githubusercontent.com/35397764/93959612-ae03fd80-fd8b-11ea-8dbf-86d15bbbcec7.png)

I only found how to generate mask photos like above, but cannot generate a proper json file which include the mask information. Can you guys demonstrate it for me? Many thanks to you~

**Comment by JonathanHUnity** [comment]
@HaiyiMei The dataset is captured in a set of json files in the Dataset<GUID> directory next to the SemanticSegmentation directory containing the images. The schema for these json files is described here: https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Schema/Synthetic_Dataset_Schema.md
This is not the COCO format, however, so you may need to translate the json into COCO format yourself. We've discussed adding COCO output directly to the perception SDK but do not have any plans at the moment.

**Comment by HaiyiMei** [comment]
Thanks for replying. Looking forward to the new features.
Plus, I was hoping for a keypoint annotation feature to be added. Wishing you had some plans.

**Comment by sleal-unity** [comment]
I'm gonna go ahead and close this issue with the following comments:
1. The Perception package supports the generation of semantic segmentation masks using the SemanticSegmentationLabeler
2. The Perception package supports keypoint annotations through the KeypointLabeler
3. We do not currently have plans to support outputting COCO format datasets directly from the perception package.
