### ISSUE TITLE
Randomization Tutorial example uses wrong namespace. 

### ISSUE THREAD

**Issue by justinschlottman** [Unity-Technologies/com.unity.perception#86]
The example code in Step 4 of the Randomization Tutorial md file is wrong. The Perception.Randomization namespace is in UnityEngine.Experimental. 

Existing:
using UnityEngine.Perception.Randomization.Configuration;
using UnityEngine.Perception.Randomization.Parameters;
using UnityEngine.Perception.Randomization.Scenarios;

Correct:
using UnityEngine.Experimental.Perception.Randomization.Configuration;
using UnityEngine.Experimental.Perception.Randomization.Parameters;
using UnityEngine.Experimental.Perception.Randomization.Scenarios;

**Comment by mkamalza** [comment]
Thank you for bringing this to our attention. That tutorial is now obsolete as the randomization tools will be overhauled in the next release, which will be coming in a couple of days. You can get early access to the new randomization tools and tutorial now on the master branch: https://github.com/Unity-Technologies/com.unity.perception

**Comment by JonathanHUnity** [comment]
Closing as the new tutorial is rolled out.
