### ISSUE TITLE
No "Add Randomizer" in Fixed Length Scenario Component

### ISSUE THREAD

**Issue by gabrielibagon** [Unity-Technologies/com.unity.perception#91]
Following the [Randomization Tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Tutorial/Phase1.md#step-5), I do not see an "Add Randomizer" button in the Fixed Length Scenario Component. Attached is a screenshot of my component:

![image](https://user-images.githubusercontent.com/12654145/95782456-c8434400-0c84-11eb-812f-055c0a1d1401.png)

**Unity Version**: 2019.4.10f1 Personal
**Perception Version**: 0.4.0-preview-1
**OS**: MacOS Catalina

**Comment by sleal-unity** [comment]
Hi there! The perception package git repository is quite a few commits ahead of the currently published perception package that you likely installed from the package manager by following the tutorial. Until we officially push these new features into the Unity package manager, you can [clone this repository and add it to your project through the package manager instead](https://docs.unity3d.com/Manual/upm-ui-local.html). Though after we've published the next version of the perception package in a few days, the tutorial instructions will be valid.

**Comment by gabrielibagon** [comment]
Importing the package locally from the master branch resolved the issue. Thanks!
