### ISSUE TITLE
SemanticSegmentationLabeler Sky

### ISSUE THREAD

**Issue by HenrikWerner** [Unity-Technologies/com.unity.perception#95]
Is there a way to give the sky a label and a color for semantic segmentation? I cannot find a way to do this (using HDRP).

**Comment by JonathanHUnity** [comment]
Hi @HenrikWerner, thanks for trying this out. We have not exposed control for the sky color at the moment. We will add this to our backlog and try to get to it soon.

In the meantime, here is the line of code that you could modify to set the sky color. https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Runtime/GroundTruth/SemanticSegmentationCrossPipelinePass.cs#L58
