### ISSUE TITLE
Generate depth image

### ISSUE THREAD

**Issue by jxw-tmp** [Unity-Technologies/com.unity.perception#96]
Is generating depth image in the development roadmap ?   Simulating depth camera is important for many applications.

**Comment by JonathanHUnity** [comment]
Hi @jxw-tmp , depth output is a highly requested feature. We are looking into it this week, and depending on the amount of work it appears to be we will prioritize.

**Comment by jxw-tmp** [comment]
Thanks a lot. Good to hear that.

**Comment by paszti96** [comment]
If I try to use the DepthGrab.cs script from Unity.Simulation.Capture with the Perception, it will only save black images. Why could it be?

**Comment by mamacker** [comment]
Hi there!  Not sure if its possible to add a vote - but I need depth as well so that I can create training data for stereo pair.

Is there a branch where this work is underway?  Would love to see about working with any start to it.

Thanks!

**Comment by dsvilarkovic** [comment]
I need it as well, no responses so far

**Comment by PrashanthBathula** [comment]
@JonathanHUnity Any update on this issue? Any upcoming release has this enhancement added?

**Comment by StevenBorkman** [comment]
Sorry for the delay on the response. Right now we are currently at the point where we would like to build this in to the package but we don't currently have it on our immediate roadmap.

**Comment by frederikvaneecke1997** [comment]
Any updates on when depth data can be expected? Providing depth data should become a priority in my opinion, it's part of so many computer vision applications.

**Comment by shounakmitra** [comment]
Hi all,

Completely understand the importance of depth sensor. We're in the process of adding this to our roadmap. Drop me an email at shounak.mitra@unity3d.com if you'd like to know more details around timeline, feature set we're planning etc.

**Comment by FedericoVasile1** [comment]
Hi all,

any updates on this? Thank you.

**Comment by RuiyuZ** [comment]
Hi @frederikvaneecke1997 and @FedericoVasile1, we have a depth labeler in the works that can generate 32-bit depth images in EXR format, where each pixel contains the actual distance in Unity units (usually meters) from the camera to the object in the scene.

If this seems of interest, feel free to drop an email to @shounakmitra [(shounak.mitra@unity3d.com)](mailto:shounak.mitra@unity3d.com) and he can take it from there!

**Comment by FedericoVasile1** [comment]
Thank you for the update Ruiyu. Cool, this is exactly what I am looking for.
I hope to see this feature in your package soon 😄

**Comment by RuiyuZ** [comment]
Hi @FedericoVasile1, yes I think it will be possible. Inside the depth labeler, I had a DepthTextureReadback(), which is invoked when the channel's output texture is readback during frame capture: it has 2 parameters, the first parameter is the frameCount of the captured frame, and the second parameter is the pixel data from the channel's depth output texture that was readback from the GPU. You can access the depth data from the second parameter (which is a NativeArray<float4>).

**Comment by StevenBorkman** [comment]
Hi Steve,

First, let me apologize for not being able to get in contact with Shounak, he is no longer part of the CV team. But hopefully I can help. 

Although we do not support, nor is it on our roadmap, depth images in our free version of the perception package, we now have a paid enterprise offering, that supports depth labeling. For more information, please see the [feature comparison chart here](https://create.unity.com/cv-offerings). This should be able to get you going with depth data, along with. many other labelers, immediately.

If you are interested in learning more about our enterprise offering, please contact Phoebe He (phoebe.he@unity3d.com).

I hope this information helps,
Steve

**Comment by StevenBorkman** [comment]
Dear @FedericoVasile1,

Sorry for the miscommunication. The new enterprise offering is just now being rolled out and I'm not sure if there has been a formal announcement about it yet. And I am sorry for this miscommunication about our roadmap from earlier. In any case, I would definitely suggest contacting Phoebe and let me know if you have any further questions.

**Comment by gbattra** [comment]
@StevenBorkman the "Submit" button in the link you provide is broken, leading to a 404

**Comment by cloudlakecho** [comment]
There is an example to calculate depth from "_ProjectionParams.y" and "_ProjectionParams.z" by [Immersive-Limit](https://github.com/immersive-limit/Unity-ComputerVisionSim). The Shader code line is [here](https://github.com/immersive-limit/Unity-ComputerVisionSim/blob/263e87c9cb58141afa2692ef9bf4bfac48afeca3/Unity/Assets/ImageSynthesis/Shaders/UberReplacement.shader#L22-L27). 

Here is the approach:
&nbsp;&nbsp;&nbsp;&nbsp; depth01 = B pixel value (RGB in PNG) / ( 1 + near camera clip / far camera clip) + near camera clip / far camera clip

The accuracy of depth are varied. 

There is another example by the [Unity Technologies Japan](https://github.com/unity3d-jp/FrameCapturer). I don't check the method.

**Comment by S-Beers** [comment]
Hi,

I am a student and wanted to use RGB-D to generate synthetic data. I think the student license give me the same access as a professional license. However, I think the RGB-D sensor an enterprise-only feature. Is this true?  Thanks in advance.

**Comment by SK8Era** [comment]
> Hi,
> 
> I am a student and wanted to use RGB-D to generate synthetic data. I think the student license give me the same access as a professional license. However, I think the RGB-D sensor an enterprise-only feature. Is this true? Thanks in advance.

I also have the same problem

**Comment by S-Beers** [comment]
> > Hi,
> > I am a student and wanted to use RGB-D to generate synthetic data. I think the student license give me the same access as a professional license. However, I think the RGB-D sensor an enterprise-only feature. Is this true? Thanks in advance.
> 
> I also have the same problem

Maybe @StevenBorkman could shed some light on this question?

**Comment by aryan-mann** [comment]
Hey all! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! We now have **depth support built in** that you could try out today! 

There are a bunch of cool features to check out such as ray tracing, depth, a new output format SOLO, normals, and more! Here is the full list of changes: [Perception 1.0 Changelog](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/CHANGELOG.md)

**Comment by eugeneteoh** [comment]
> Hi @FedericoVasile1, yes I think it will be possible. Inside the depth labeler, I had a DepthTextureReadback() function, which is invoked when the channel's output texture is readback during frame capture: it has 2 parameters, the first parameter is the frameCount of the captured frame, and the second parameter is the pixel data from the channel's depth output texture that was readback from the GPU. You can access the depth data from the second parameter.

Hi there, I'm also trying to do this. Is there an example to access the texture through script?

**Comment by StevenBorkman** [comment]
@eugeneteoh, have you tried the latest Perception 1.0, we now have a depth labeler which produces a depth image each frame

**Comment by StevenBorkman** [comment]
Ok, interesting. can you give me a brief explanation of what you are trying to accomplish? I might be able to make some suggestions based on that.

**Comment by StevenBorkman** [comment]
Ok. Very cool. We have re-architected the way that perception works internally with the 1.0 release. Prior to it, generation and serialization of the data was a tightly coupled process. As a part of the SOLO work, we re-architected the simulation state and dataset capture classes to use a new endpoint based architecture. So now the data is generated and passed to an endpoint, which by default is the solo endpoint which serializes the data to disk.

I have made internal projects where I created a new endpoint that received the data, and streamed directly to a python node. This way you can completely bypass writing any data to disk.

**Comment by StevenBorkman** [comment]
I ran out of time before the release, but I wanted to write a couple of examples of how to write alternative endpoints, for instance a COCO writer, and perhaps an endpoint example of streaming the data.

**Comment by eugeneteoh** [comment]
Thanks! I'm guessing it's related to [this](https://github.com/Unity-Technologies/com.unity.perception/blob/1.0.0-preview.1/com.unity.perception/Documentation~/Features/CustomEndpoints.md)? It seems like I would have to create a C# node to be able to consume the data, which is an overkill for my use case. I believe what I need is even simpler than that, which is just reading real time captured images into a variable in C#.

**Comment by eugeneteoh** [comment]
Ok I figured out. What I needed is just:
```cs
var outputTexture = perceptionCamera.GetChannel<DepthChannel>().outputTexture;
```

**Comment by StevenBorkman** [comment]
Great news!
